// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/client_commands.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CustomNudgeDelay struct {
	DatatypeId           *int32   `protobuf:"varint,1,opt,name=datatype_id,json=datatypeId" json:"datatype_id,omitempty"`
	DelayMs              *int32   `protobuf:"varint,2,opt,name=delay_ms,json=delayMs" json:"delay_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomNudgeDelay) Reset()         { *m = CustomNudgeDelay{} }
func (m *CustomNudgeDelay) String() string { return proto.CompactTextString(m) }
func (*CustomNudgeDelay) ProtoMessage()    {}
func (*CustomNudgeDelay) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_commands_079b3cacb9726eae, []int{0}
}
func (m *CustomNudgeDelay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomNudgeDelay.Unmarshal(m, b)
}
func (m *CustomNudgeDelay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomNudgeDelay.Marshal(b, m, deterministic)
}
func (dst *CustomNudgeDelay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomNudgeDelay.Merge(dst, src)
}
func (m *CustomNudgeDelay) XXX_Size() int {
	return xxx_messageInfo_CustomNudgeDelay.Size(m)
}
func (m *CustomNudgeDelay) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomNudgeDelay.DiscardUnknown(m)
}

var xxx_messageInfo_CustomNudgeDelay proto.InternalMessageInfo

func (m *CustomNudgeDelay) GetDatatypeId() int32 {
	if m != nil && m.DatatypeId != nil {
		return *m.DatatypeId
	}
	return 0
}

func (m *CustomNudgeDelay) GetDelayMs() int32 {
	if m != nil && m.DelayMs != nil {
		return *m.DelayMs
	}
	return 0
}

type ClientCommand struct {
	// Time to wait before sending any requests to the server.
	SetSyncPollInterval *int32 `protobuf:"varint,1,opt,name=set_sync_poll_interval,json=setSyncPollInterval" json:"set_sync_poll_interval,omitempty"`
	// This has been deprecated since M75.
	SetSyncLongPollInterval *int32 `protobuf:"varint,2,opt,name=set_sync_long_poll_interval,json=setSyncLongPollInterval" json:"set_sync_long_poll_interval,omitempty"` // Deprecated: Do not use.
	MaxCommitBatchSize      *int32 `protobuf:"varint,3,opt,name=max_commit_batch_size,json=maxCommitBatchSize" json:"max_commit_batch_size,omitempty"`
	// Number of seconds to delay between a sessions action and sending a commit
	// message to the server. Can be overridden by |custom_nudge_delays|.
	SessionsCommitDelaySeconds *int32 `protobuf:"varint,4,opt,name=sessions_commit_delay_seconds,json=sessionsCommitDelaySeconds" json:"sessions_commit_delay_seconds,omitempty"`
	// Number of seconds to delay before the throttled client should retry.
	ThrottleDelaySeconds *int32 `protobuf:"varint,5,opt,name=throttle_delay_seconds,json=throttleDelaySeconds" json:"throttle_delay_seconds,omitempty"`
	// Maximum number of local nudges to buffer per-type.
	ClientInvalidationHintBufferSize *int32 `protobuf:"varint,6,opt,name=client_invalidation_hint_buffer_size,json=clientInvalidationHintBufferSize" json:"client_invalidation_hint_buffer_size,omitempty"`
	// Time to wait before issuing a retry GU.
	GuRetryDelaySeconds *int32 `protobuf:"varint,7,opt,name=gu_retry_delay_seconds,json=guRetryDelaySeconds" json:"gu_retry_delay_seconds,omitempty"`
	// A dictionary of custom nudge delays.
	// Note: if a SESSIONS value is present, this will override
	// |sessions_commit_delay_seconds|
	// New in M39.
	CustomNudgeDelays    []*CustomNudgeDelay `protobuf:"bytes,8,rep,name=custom_nudge_delays,json=customNudgeDelays" json:"custom_nudge_delays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ClientCommand) Reset()         { *m = ClientCommand{} }
func (m *ClientCommand) String() string { return proto.CompactTextString(m) }
func (*ClientCommand) ProtoMessage()    {}
func (*ClientCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_client_commands_079b3cacb9726eae, []int{1}
}
func (m *ClientCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientCommand.Unmarshal(m, b)
}
func (m *ClientCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientCommand.Marshal(b, m, deterministic)
}
func (dst *ClientCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCommand.Merge(dst, src)
}
func (m *ClientCommand) XXX_Size() int {
	return xxx_messageInfo_ClientCommand.Size(m)
}
func (m *ClientCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCommand proto.InternalMessageInfo

func (m *ClientCommand) GetSetSyncPollInterval() int32 {
	if m != nil && m.SetSyncPollInterval != nil {
		return *m.SetSyncPollInterval
	}
	return 0
}

// Deprecated: Do not use.
func (m *ClientCommand) GetSetSyncLongPollInterval() int32 {
	if m != nil && m.SetSyncLongPollInterval != nil {
		return *m.SetSyncLongPollInterval
	}
	return 0
}

func (m *ClientCommand) GetMaxCommitBatchSize() int32 {
	if m != nil && m.MaxCommitBatchSize != nil {
		return *m.MaxCommitBatchSize
	}
	return 0
}

func (m *ClientCommand) GetSessionsCommitDelaySeconds() int32 {
	if m != nil && m.SessionsCommitDelaySeconds != nil {
		return *m.SessionsCommitDelaySeconds
	}
	return 0
}

func (m *ClientCommand) GetThrottleDelaySeconds() int32 {
	if m != nil && m.ThrottleDelaySeconds != nil {
		return *m.ThrottleDelaySeconds
	}
	return 0
}

func (m *ClientCommand) GetClientInvalidationHintBufferSize() int32 {
	if m != nil && m.ClientInvalidationHintBufferSize != nil {
		return *m.ClientInvalidationHintBufferSize
	}
	return 0
}

func (m *ClientCommand) GetGuRetryDelaySeconds() int32 {
	if m != nil && m.GuRetryDelaySeconds != nil {
		return *m.GuRetryDelaySeconds
	}
	return 0
}

func (m *ClientCommand) GetCustomNudgeDelays() []*CustomNudgeDelay {
	if m != nil {
		return m.CustomNudgeDelays
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomNudgeDelay)(nil), "sync_pb.CustomNudgeDelay")
	proto.RegisterType((*ClientCommand)(nil), "sync_pb.ClientCommand")
}

func init() {
	proto.RegisterFile("components/sync/protocol/client_commands.proto", fileDescriptor_client_commands_079b3cacb9726eae)
}

var fileDescriptor_client_commands_079b3cacb9726eae = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xe1, 0x6a, 0xdb, 0x30,
	0x14, 0x85, 0x49, 0xd3, 0x2e, 0x45, 0x65, 0xb0, 0xb9, 0x5b, 0xe6, 0x6e, 0x8c, 0x85, 0xb2, 0x41,
	0x61, 0xe0, 0xb0, 0x75, 0x0f, 0xb0, 0x25, 0xfb, 0xd1, 0xc0, 0x16, 0x4a, 0xf2, 0x00, 0x42, 0x91,
	0x55, 0x47, 0x20, 0xe9, 0x1a, 0xdf, 0xeb, 0x52, 0xf7, 0xe7, 0x9e, 0x7c, 0xf8, 0xca, 0x2e, 0x8d,
	0x7f, 0x5a, 0xe7, 0x7c, 0xf7, 0xe8, 0xca, 0x47, 0x64, 0x1a, 0x7c, 0x09, 0xc1, 0x04, 0xc2, 0x39,
	0x36, 0x41, 0xcf, 0xcb, 0x0a, 0x08, 0x34, 0xb8, 0xb9, 0x76, 0xd6, 0x04, 0x92, 0x1a, 0xbc, 0x57,
	0x21, 0xc7, 0x8c, 0x85, 0x64, 0xd2, 0x9a, 0x64, 0xb9, 0xbb, 0x5c, 0x8b, 0x57, 0xcb, 0x1a, 0x09,
	0xfc, 0xba, 0xce, 0x0b, 0xf3, 0xdb, 0x38, 0xd5, 0x24, 0x9f, 0xc4, 0x59, 0xae, 0x48, 0x51, 0x53,
	0x1a, 0x69, 0xf3, 0x74, 0x34, 0x1b, 0x5d, 0x9d, 0x6c, 0x44, 0x7f, 0xb4, 0xca, 0x93, 0x0b, 0x71,
	0x9a, 0xb7, 0x4e, 0xe9, 0x31, 0x3d, 0x62, 0x75, 0xc2, 0xdf, 0x7f, 0xf1, 0xf2, 0xdf, 0xb1, 0x78,
	0xb9, 0xe4, 0xc8, 0x65, 0x4c, 0x4c, 0xae, 0xc5, 0x14, 0x0d, 0xc9, 0x18, 0x08, 0xce, 0x49, 0x1b,
	0xc8, 0x54, 0xf7, 0xca, 0x75, 0x83, 0xcf, 0xd1, 0xd0, 0xb6, 0x09, 0xfa, 0x16, 0x9c, 0x5b, 0x75,
	0x52, 0xf2, 0x53, 0x7c, 0x78, 0x82, 0x1c, 0x84, 0x62, 0x40, 0x72, 0xe8, 0xe2, 0x28, 0x1d, 0x6d,
	0xde, 0x75, 0xf4, 0x1f, 0x08, 0xc5, 0xc1, 0x84, 0x6f, 0xe2, 0xad, 0x57, 0x0f, 0xbc, 0xb7, 0x25,
	0xb9, 0x53, 0xa4, 0xf7, 0x12, 0xed, 0xa3, 0x49, 0xc7, 0x9c, 0x9a, 0x78, 0xf5, 0xb0, 0x64, 0x6d,
	0xd1, 0x4a, 0x5b, 0xfb, 0x68, 0x92, 0x5f, 0xe2, 0x23, 0x1a, 0x44, 0x0b, 0x01, 0x7b, 0x2e, 0xae,
	0x89, 0x46, 0x43, 0xc8, 0x31, 0x3d, 0x66, 0xf4, 0x7d, 0x6f, 0x8a, 0x3c, 0xbf, 0xd9, 0x36, 0x3a,
	0x92, 0x1f, 0x62, 0x4a, 0xfb, 0x0a, 0x88, 0x9c, 0x19, 0xb0, 0x27, 0xcc, 0xbe, 0xe9, 0xd5, 0x03,
	0x6a, 0x2d, 0x3e, 0x77, 0xbf, 0xc9, 0x86, 0x7b, 0xe5, 0x6c, 0xae, 0xc8, 0x42, 0x90, 0x7b, 0x1b,
	0x48, 0xee, 0xea, 0xbb, 0x3b, 0x53, 0xc5, 0xab, 0xbf, 0xe0, 0x19, 0xb3, 0xe8, 0x5d, 0x3d, 0xb3,
	0xde, 0xd8, 0x40, 0x0b, 0x36, 0xf2, 0x22, 0xd7, 0x62, 0x5a, 0xd4, 0xb2, 0x32, 0x54, 0x35, 0x83,
	0x5b, 0x4c, 0xe2, 0x93, 0x17, 0xf5, 0xa6, 0x15, 0x0f, 0x2e, 0xb1, 0x12, 0xe7, 0x9a, 0x9b, 0x20,
	0x43, 0x5b, 0x85, 0x08, 0x62, 0x7a, 0x3a, 0x1b, 0x5f, 0x9d, 0x7d, 0xbf, 0xc8, 0xba, 0xc2, 0x64,
	0xc3, 0xb6, 0x6c, 0x5e, 0xeb, 0xc1, 0x09, 0x2e, 0xbe, 0x8a, 0x2f, 0x50, 0x15, 0x99, 0xde, 0x57,
	0xe0, 0x6d, 0xed, 0x9f, 0x95, 0x93, 0xc7, 0x64, 0x7d, 0x39, 0x6f, 0xc6, 0xb7, 0xa3, 0xff, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x8f, 0x56, 0xde, 0x5f, 0xbb, 0x02, 0x00, 0x00,
}
