// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/encryption.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Encrypted sync data consists of two parts: a key name and a blob. Key name is
// the name of the key that was used to encrypt blob and blob is encrypted data
// itself.
//
// The reason we need to keep track of the key name is that a sync user can
// change their passphrase (and thus their encryption key) at any time. When
// that happens, we make a best effort to reencrypt all nodes with the new
// passphrase, but since we don't have transactions on the server-side, we
// cannot guarantee that every node will be reencrypted. As a workaround, we
// keep track of all keys, assign each key a name (by using that key to encrypt
// a well known string) and keep track of which key was used to encrypt each
// node.
type EncryptedData struct {
	KeyName              *string  `protobuf:"bytes,1,opt,name=key_name,json=keyName" json:"key_name,omitempty"`
	Blob                 *string  `protobuf:"bytes,2,opt,name=blob" json:"blob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedData) Reset()         { *m = EncryptedData{} }
func (m *EncryptedData) String() string { return proto.CompactTextString(m) }
func (*EncryptedData) ProtoMessage()    {}
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_2f8007da2a94ce72, []int{0}
}
func (m *EncryptedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedData.Unmarshal(m, b)
}
func (m *EncryptedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedData.Marshal(b, m, deterministic)
}
func (dst *EncryptedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedData.Merge(dst, src)
}
func (m *EncryptedData) XXX_Size() int {
	return xxx_messageInfo_EncryptedData.Size(m)
}
func (m *EncryptedData) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedData.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedData proto.InternalMessageInfo

func (m *EncryptedData) GetKeyName() string {
	if m != nil && m.KeyName != nil {
		return *m.KeyName
	}
	return ""
}

func (m *EncryptedData) GetBlob() string {
	if m != nil && m.Blob != nil {
		return *m.Blob
	}
	return ""
}

func init() {
	proto.RegisterType((*EncryptedData)(nil), "sync_pb.EncryptedData")
}

func init() {
	proto.RegisterFile("components/sync/protocol/encryption.proto", fileDescriptor_encryption_2f8007da2a94ce72)
}

var fileDescriptor_encryption_2f8007da2a94ce72 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0xce, 0xcf, 0x2d,
	0xc8, 0xcf, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2f, 0xae, 0xcc, 0x4b, 0xd6, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x4f, 0xcd, 0x4b, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0xcc, 0xcf, 0xd3,
	0x03, 0x8b, 0x09, 0xb1, 0x83, 0xe4, 0xe3, 0x0b, 0x92, 0x94, 0xec, 0xb8, 0x78, 0x5d, 0x21, 0x92,
	0xa9, 0x29, 0x2e, 0x89, 0x25, 0x89, 0x42, 0x92, 0x5c, 0x1c, 0xd9, 0xa9, 0x95, 0xf1, 0x79, 0x89,
	0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xec, 0xd9, 0xa9, 0x95, 0x7e, 0x89, 0xb9,
	0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x49, 0x39, 0xf9, 0x49, 0x12, 0x4c, 0x60, 0x61, 0x30, 0xdb, 0x49,
	0x9b, 0x4b, 0x35, 0xbf, 0x28, 0x5d, 0x2f, 0x39, 0xa3, 0x28, 0x3f, 0x37, 0xb3, 0x34, 0x57, 0x0f,
	0xe1, 0x04, 0x3d, 0x90, 0x15, 0x7a, 0x30, 0x27, 0x78, 0x30, 0x07, 0x30, 0x02, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x78, 0x82, 0x4e, 0x94, 0xa1, 0x00, 0x00, 0x00,
}
