// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/get_updates_caller_info.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// This enum was deprecated in M28.  The preferred represenation of this
// information is now the GetUpdatesOrigin enum, which is defined in
// sync_enums.proto.
// TODO(crbug.com/510165): Remove all values except for UNKNOWN and stop
// filling the field once the server doesn't depend on it anymore.
type GetUpdatesCallerInfo_GetUpdatesSource int32

const (
	GetUpdatesCallerInfo_UNKNOWN      GetUpdatesCallerInfo_GetUpdatesSource = 0
	GetUpdatesCallerInfo_FIRST_UPDATE GetUpdatesCallerInfo_GetUpdatesSource = 1
	// be confused with "NEW_CLIENT".
	GetUpdatesCallerInfo_LOCAL                    GetUpdatesCallerInfo_GetUpdatesSource = 2
	GetUpdatesCallerInfo_NOTIFICATION             GetUpdatesCallerInfo_GetUpdatesSource = 3
	GetUpdatesCallerInfo_PERIODIC                 GetUpdatesCallerInfo_GetUpdatesSource = 4
	GetUpdatesCallerInfo_SYNC_CYCLE_CONTINUATION  GetUpdatesCallerInfo_GetUpdatesSource = 5
	GetUpdatesCallerInfo_NEWLY_SUPPORTED_DATATYPE GetUpdatesCallerInfo_GetUpdatesSource = 7
	// because it's syncing all datatypes, and
	// support for a new datatype was recently
	// released via a software auto-update.
	GetUpdatesCallerInfo_MIGRATION GetUpdatesCallerInfo_GetUpdatesSource = 8
	// MIGRATION_DONE error previously returned by the
	// server necessitated resynchronization.
	GetUpdatesCallerInfo_NEW_CLIENT GetUpdatesCallerInfo_GetUpdatesSource = 9
	// user enabled sync for the first time.  Not to be
	// confused with FIRST_UPDATE.
	GetUpdatesCallerInfo_RECONFIGURATION GetUpdatesCallerInfo_GetUpdatesSource = 10
	// user opted to sync a different set of datatypes.
	GetUpdatesCallerInfo_DATATYPE_REFRESH GetUpdatesCallerInfo_GetUpdatesSource = 11
	// typically used when datatype's have custom
	// sync UI, e.g. sessions.
	GetUpdatesCallerInfo_RETRY        GetUpdatesCallerInfo_GetUpdatesSource = 13
	GetUpdatesCallerInfo_PROGRAMMATIC GetUpdatesCallerInfo_GetUpdatesSource = 14
)

var GetUpdatesCallerInfo_GetUpdatesSource_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "FIRST_UPDATE",
	2:  "LOCAL",
	3:  "NOTIFICATION",
	4:  "PERIODIC",
	5:  "SYNC_CYCLE_CONTINUATION",
	7:  "NEWLY_SUPPORTED_DATATYPE",
	8:  "MIGRATION",
	9:  "NEW_CLIENT",
	10: "RECONFIGURATION",
	11: "DATATYPE_REFRESH",
	13: "RETRY",
	14: "PROGRAMMATIC",
}
var GetUpdatesCallerInfo_GetUpdatesSource_value = map[string]int32{
	"UNKNOWN":                  0,
	"FIRST_UPDATE":             1,
	"LOCAL":                    2,
	"NOTIFICATION":             3,
	"PERIODIC":                 4,
	"SYNC_CYCLE_CONTINUATION":  5,
	"NEWLY_SUPPORTED_DATATYPE": 7,
	"MIGRATION":                8,
	"NEW_CLIENT":               9,
	"RECONFIGURATION":          10,
	"DATATYPE_REFRESH":         11,
	"RETRY":                    13,
	"PROGRAMMATIC":             14,
}

func (x GetUpdatesCallerInfo_GetUpdatesSource) Enum() *GetUpdatesCallerInfo_GetUpdatesSource {
	p := new(GetUpdatesCallerInfo_GetUpdatesSource)
	*p = x
	return p
}
func (x GetUpdatesCallerInfo_GetUpdatesSource) String() string {
	return proto.EnumName(GetUpdatesCallerInfo_GetUpdatesSource_name, int32(x))
}
func (x *GetUpdatesCallerInfo_GetUpdatesSource) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GetUpdatesCallerInfo_GetUpdatesSource_value, data, "GetUpdatesCallerInfo_GetUpdatesSource")
	if err != nil {
		return err
	}
	*x = GetUpdatesCallerInfo_GetUpdatesSource(value)
	return nil
}
func (GetUpdatesCallerInfo_GetUpdatesSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_get_updates_caller_info_6383ca9edb8e1e27, []int{0, 0}
}

type GetUpdatesCallerInfo struct {
	Source *GetUpdatesCallerInfo_GetUpdatesSource `protobuf:"varint,1,req,name=source,enum=sync_pb.GetUpdatesCallerInfo_GetUpdatesSource" json:"source,omitempty"` // Deprecated: Do not use.
	// True only if notifications were enabled for this GetUpdateMessage.
	// TODO(crbug.com/510165): Move this bool out of GetUpdatesCallerInfo so that
	// GetUpdatesCallerInfo can eventually be removed.
	NotificationsEnabled *bool    `protobuf:"varint,2,opt,name=notifications_enabled,json=notificationsEnabled" json:"notifications_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUpdatesCallerInfo) Reset()         { *m = GetUpdatesCallerInfo{} }
func (m *GetUpdatesCallerInfo) String() string { return proto.CompactTextString(m) }
func (*GetUpdatesCallerInfo) ProtoMessage()    {}
func (*GetUpdatesCallerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_updates_caller_info_6383ca9edb8e1e27, []int{0}
}
func (m *GetUpdatesCallerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUpdatesCallerInfo.Unmarshal(m, b)
}
func (m *GetUpdatesCallerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUpdatesCallerInfo.Marshal(b, m, deterministic)
}
func (dst *GetUpdatesCallerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUpdatesCallerInfo.Merge(dst, src)
}
func (m *GetUpdatesCallerInfo) XXX_Size() int {
	return xxx_messageInfo_GetUpdatesCallerInfo.Size(m)
}
func (m *GetUpdatesCallerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUpdatesCallerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetUpdatesCallerInfo proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *GetUpdatesCallerInfo) GetSource() GetUpdatesCallerInfo_GetUpdatesSource {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return GetUpdatesCallerInfo_UNKNOWN
}

func (m *GetUpdatesCallerInfo) GetNotificationsEnabled() bool {
	if m != nil && m.NotificationsEnabled != nil {
		return *m.NotificationsEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*GetUpdatesCallerInfo)(nil), "sync_pb.GetUpdatesCallerInfo")
	proto.RegisterEnum("sync_pb.GetUpdatesCallerInfo_GetUpdatesSource", GetUpdatesCallerInfo_GetUpdatesSource_name, GetUpdatesCallerInfo_GetUpdatesSource_value)
}

func init() {
	proto.RegisterFile("components/sync/protocol/get_updates_caller_info.proto", fileDescriptor_get_updates_caller_info_6383ca9edb8e1e27)
}

var fileDescriptor_get_updates_caller_info_6383ca9edb8e1e27 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd1, 0x4f, 0x6b, 0xdb, 0x30,
	0x18, 0x06, 0xf0, 0x39, 0x59, 0x97, 0xe4, 0x6d, 0x9b, 0x09, 0x2d, 0x63, 0x81, 0xed, 0x50, 0x0a,
	0x83, 0xc2, 0xc0, 0x81, 0x0d, 0x76, 0x77, 0x15, 0x25, 0xd5, 0xe6, 0x48, 0x46, 0x96, 0x09, 0x3e,
	0x89, 0xd4, 0x55, 0x3a, 0x83, 0x23, 0x19, 0xdb, 0x39, 0xec, 0x9b, 0xec, 0xd3, 0x8e, 0x61, 0x3b,
	0x65, 0x7f, 0xd8, 0x55, 0xcf, 0x4f, 0x0f, 0x2f, 0x3c, 0xf0, 0x39, 0x73, 0x87, 0xd2, 0x59, 0x63,
	0x9b, 0x7a, 0x51, 0x7f, 0xb7, 0xd9, 0xa2, 0xac, 0x5c, 0xe3, 0x32, 0x57, 0x2c, 0x1e, 0x4d, 0xa3,
	0x8f, 0xe5, 0xc3, 0xae, 0x31, 0xb5, 0xce, 0x76, 0x45, 0x61, 0x2a, 0x9d, 0xdb, 0xbd, 0xf3, 0x3b,
	0x80, 0x47, 0x2d, 0xd6, 0xe5, 0xfd, 0xf5, 0x8f, 0x21, 0xcc, 0xd6, 0xa6, 0x49, 0x7a, 0x49, 0x3a,
	0xc8, 0xec, 0xde, 0xe1, 0x2f, 0xf0, 0xa2, 0x76, 0xc7, 0x2a, 0x33, 0x73, 0xef, 0x6a, 0x70, 0x33,
	0xfd, 0xe8, 0xfb, 0xa7, 0x2f, 0xfe, 0xff, 0xf8, 0x1f, 0x8f, 0x71, 0xf7, 0xeb, 0x76, 0x30, 0xf7,
	0xe4, 0xa9, 0x01, 0x7f, 0x82, 0xd7, 0xd6, 0x35, 0xf9, 0x3e, 0xcf, 0x76, 0x4d, 0xee, 0x6c, 0xad,
	0x8d, 0xdd, 0xdd, 0x17, 0xe6, 0x61, 0x3e, 0xb8, 0xf2, 0x6e, 0xc6, 0x72, 0xf6, 0x57, 0x48, 0xfb,
	0xec, 0xfa, 0xa7, 0x07, 0xe8, 0xdf, 0x56, 0x7c, 0x0e, 0xa3, 0x84, 0x7f, 0xe5, 0x62, 0xcb, 0xd1,
	0x33, 0x8c, 0xe0, 0x62, 0xc5, 0x64, 0xac, 0x74, 0x12, 0x2d, 0x03, 0x45, 0x91, 0x87, 0x27, 0x70,
	0x16, 0x0a, 0x12, 0x84, 0x68, 0xd0, 0x86, 0x5c, 0x28, 0xb6, 0x62, 0x24, 0x50, 0x4c, 0x70, 0x34,
	0xc4, 0x17, 0x30, 0x8e, 0xa8, 0x64, 0x62, 0xc9, 0x08, 0x7a, 0x8e, 0xdf, 0xc2, 0x9b, 0x38, 0xe5,
	0x44, 0x93, 0x94, 0x84, 0x54, 0x13, 0xc1, 0x15, 0xe3, 0x49, 0x4f, 0xcf, 0xf0, 0x3b, 0x98, 0x73,
	0xba, 0x0d, 0x53, 0x1d, 0x27, 0x51, 0x24, 0xa4, 0xa2, 0x4b, 0xbd, 0x0c, 0x54, 0xa0, 0xd2, 0x88,
	0xa2, 0x11, 0xbe, 0x84, 0xc9, 0x86, 0xad, 0x65, 0x8f, 0xc7, 0x78, 0x0a, 0xc0, 0xe9, 0x56, 0x93,
	0x90, 0x51, 0xae, 0xd0, 0x04, 0xbf, 0x82, 0x97, 0x92, 0x12, 0xc1, 0x57, 0x6c, 0x9d, 0x9c, 0x10,
	0xe0, 0x19, 0xa0, 0xa7, 0x06, 0x2d, 0xe9, 0x4a, 0xd2, 0xf8, 0x0e, 0x9d, 0xb7, 0xf7, 0x4a, 0xaa,
	0x64, 0x8a, 0x2e, 0xdb, 0x7b, 0x23, 0x29, 0xd6, 0x32, 0xd8, 0x6c, 0x02, 0xc5, 0x08, 0x9a, 0xde,
	0x7e, 0x80, 0xf7, 0xae, 0x7a, 0xf4, 0xb3, 0x6f, 0x95, 0x3b, 0xe4, 0xc7, 0x83, 0xff, 0x7b, 0xea,
	0x6e, 0x0a, 0xff, 0x69, 0xea, 0xbb, 0x61, 0xe4, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x67,
	0x0b, 0x1f, 0x09, 0x02, 0x00, 0x00,
}
