// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/history_status.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HistoryStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryStatusRequest) Reset()         { *m = HistoryStatusRequest{} }
func (m *HistoryStatusRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryStatusRequest) ProtoMessage()    {}
func (*HistoryStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_history_status_d70de1d1c88bb040, []int{0}
}
func (m *HistoryStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryStatusRequest.Unmarshal(m, b)
}
func (m *HistoryStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryStatusRequest.Marshal(b, m, deterministic)
}
func (dst *HistoryStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryStatusRequest.Merge(dst, src)
}
func (m *HistoryStatusRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryStatusRequest.Size(m)
}
func (m *HistoryStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryStatusRequest proto.InternalMessageInfo

// Response to a history status request.
type HistoryStatusResponse struct {
	// Minimal time to wait before issuing another request.
	MinPollIntervalSeconds *int32 `protobuf:"varint,1,opt,name=min_poll_interval_seconds,json=minPollIntervalSeconds,def=3600" json:"min_poll_interval_seconds,omitempty"`
	// Indicates whether the history corpuses have any derived data for a user.
	HasDerivedData       *bool    `protobuf:"varint,2,opt,name=has_derived_data,json=hasDerivedData" json:"has_derived_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryStatusResponse) Reset()         { *m = HistoryStatusResponse{} }
func (m *HistoryStatusResponse) String() string { return proto.CompactTextString(m) }
func (*HistoryStatusResponse) ProtoMessage()    {}
func (*HistoryStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_history_status_d70de1d1c88bb040, []int{1}
}
func (m *HistoryStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryStatusResponse.Unmarshal(m, b)
}
func (m *HistoryStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryStatusResponse.Marshal(b, m, deterministic)
}
func (dst *HistoryStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryStatusResponse.Merge(dst, src)
}
func (m *HistoryStatusResponse) XXX_Size() int {
	return xxx_messageInfo_HistoryStatusResponse.Size(m)
}
func (m *HistoryStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryStatusResponse proto.InternalMessageInfo

const Default_HistoryStatusResponse_MinPollIntervalSeconds int32 = 3600

func (m *HistoryStatusResponse) GetMinPollIntervalSeconds() int32 {
	if m != nil && m.MinPollIntervalSeconds != nil {
		return *m.MinPollIntervalSeconds
	}
	return Default_HistoryStatusResponse_MinPollIntervalSeconds
}

func (m *HistoryStatusResponse) GetHasDerivedData() bool {
	if m != nil && m.HasDerivedData != nil {
		return *m.HasDerivedData
	}
	return false
}

func init() {
	proto.RegisterType((*HistoryStatusRequest)(nil), "sync_pb.HistoryStatusRequest")
	proto.RegisterType((*HistoryStatusResponse)(nil), "sync_pb.HistoryStatusResponse")
}

func init() {
	proto.RegisterFile("components/sync/protocol/history_status.proto", fileDescriptor_history_status_d70de1d1c88bb040)
}

var fileDescriptor_history_status_d70de1d1c88bb040 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0x05, 0x70, 0xe2, 0x1f, 0x94, 0x1c, 0x44, 0x16, 0x2d, 0xf5, 0x56, 0x0a, 0xc2, 0x82, 0x98,
	0x2d, 0x08, 0x1e, 0xbc, 0x08, 0xd2, 0x43, 0xbd, 0x95, 0xed, 0x07, 0x08, 0x31, 0x3b, 0xb8, 0x81,
	0x64, 0x26, 0x66, 0x66, 0x0b, 0xbd, 0xfa, 0xc9, 0xa5, 0x5d, 0x45, 0xe8, 0xf5, 0xbd, 0xdf, 0xe1,
	0x3d, 0xfd, 0xe8, 0x29, 0x65, 0x42, 0x40, 0xe1, 0x86, 0x77, 0xe8, 0x9b, 0x5c, 0x48, 0xc8, 0x53,
	0x6c, 0xfa, 0xc0, 0x42, 0x65, 0x67, 0x59, 0x9c, 0x0c, 0x6c, 0x0e, 0x79, 0x75, 0xb1, 0x37, 0x36,
	0x7f, 0xcc, 0x27, 0xfa, 0x66, 0x35, 0x82, 0xcd, 0xa1, 0x6f, 0xe1, 0x6b, 0x00, 0x96, 0xf9, 0xb7,
	0xd2, 0xb7, 0x47, 0x05, 0x67, 0x42, 0x86, 0xea, 0x55, 0xdf, 0xa5, 0x80, 0x36, 0x53, 0x8c, 0x36,
	0xa0, 0x40, 0xd9, 0xba, 0x68, 0x19, 0x3c, 0x61, 0xc7, 0x53, 0x35, 0x53, 0xf5, 0xf9, 0xcb, 0xd9,
	0xd3, 0xf3, 0x62, 0xd1, 0x4e, 0x52, 0xc0, 0x35, 0xc5, 0xf8, 0xfe, 0x8b, 0x36, 0xa3, 0xa9, 0x6a,
	0x7d, 0xdd, 0x3b, 0xb6, 0x1d, 0x94, 0xb0, 0x85, 0xce, 0x76, 0x4e, 0xdc, 0xf4, 0x64, 0xa6, 0xea,
	0xcb, 0xf6, 0xaa, 0x77, 0xbc, 0x1c, 0xe3, 0xa5, 0x13, 0xf7, 0xf6, 0xa0, 0xef, 0xa9, 0x7c, 0x1a,
	0xdf, 0x17, 0x4a, 0x61, 0x48, 0xe6, 0xff, 0xa3, 0xd9, 0xef, 0x37, 0x7f, 0x1f, 0x57, 0xa7, 0x6b,
	0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0x82, 0xd5, 0xf9, 0xbb, 0x02, 0x01, 0x00, 0x00,
}
