// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/managed_user_specifics.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Properties of managed user sync objects.
type ManagedUserSpecifics struct {
	// A randomly-generated identifier for the managed user.
	Id *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The human-visible name of the managed user
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// This flag is set by the server to acknowledge that it has committed a
	// newly created managed user.
	Acknowledged *bool `protobuf:"varint,3,opt,name=acknowledged,def=0" json:"acknowledged,omitempty"`
	// Master key for managed user cryptohome.
	MasterKey *string `protobuf:"bytes,4,opt,name=master_key,json=masterKey" json:"master_key,omitempty"`
	// A string representing the index of the supervised user avatar on Chrome.
	// It has the following format:
	// "chrome-avatar-index:INDEX" where INDEX is an integer.
	ChromeAvatar *string `protobuf:"bytes,5,opt,name=chrome_avatar,json=chromeAvatar" json:"chrome_avatar,omitempty"`
	// A string representing the index of the supervised user avatar on Chrome OS.
	// It has the following format:
	// "chromeos-avatar-index:INDEX" where INDEX is an integer.
	ChromeosAvatar *string `protobuf:"bytes,6,opt,name=chromeos_avatar,json=chromeosAvatar" json:"chromeos_avatar,omitempty"`
	// Key for signing supervised user's password.
	PasswordSignatureKey *string `protobuf:"bytes,7,opt,name=password_signature_key,json=passwordSignatureKey" json:"password_signature_key,omitempty"`
	// Key for encrypting supervised user's password.
	PasswordEncryptionKey *string  `protobuf:"bytes,8,opt,name=password_encryption_key,json=passwordEncryptionKey" json:"password_encryption_key,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ManagedUserSpecifics) Reset()         { *m = ManagedUserSpecifics{} }
func (m *ManagedUserSpecifics) String() string { return proto.CompactTextString(m) }
func (*ManagedUserSpecifics) ProtoMessage()    {}
func (*ManagedUserSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_managed_user_specifics_c3baf771fffac35c, []int{0}
}
func (m *ManagedUserSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedUserSpecifics.Unmarshal(m, b)
}
func (m *ManagedUserSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedUserSpecifics.Marshal(b, m, deterministic)
}
func (dst *ManagedUserSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedUserSpecifics.Merge(dst, src)
}
func (m *ManagedUserSpecifics) XXX_Size() int {
	return xxx_messageInfo_ManagedUserSpecifics.Size(m)
}
func (m *ManagedUserSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedUserSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedUserSpecifics proto.InternalMessageInfo

const Default_ManagedUserSpecifics_Acknowledged bool = false

func (m *ManagedUserSpecifics) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ManagedUserSpecifics) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ManagedUserSpecifics) GetAcknowledged() bool {
	if m != nil && m.Acknowledged != nil {
		return *m.Acknowledged
	}
	return Default_ManagedUserSpecifics_Acknowledged
}

func (m *ManagedUserSpecifics) GetMasterKey() string {
	if m != nil && m.MasterKey != nil {
		return *m.MasterKey
	}
	return ""
}

func (m *ManagedUserSpecifics) GetChromeAvatar() string {
	if m != nil && m.ChromeAvatar != nil {
		return *m.ChromeAvatar
	}
	return ""
}

func (m *ManagedUserSpecifics) GetChromeosAvatar() string {
	if m != nil && m.ChromeosAvatar != nil {
		return *m.ChromeosAvatar
	}
	return ""
}

func (m *ManagedUserSpecifics) GetPasswordSignatureKey() string {
	if m != nil && m.PasswordSignatureKey != nil {
		return *m.PasswordSignatureKey
	}
	return ""
}

func (m *ManagedUserSpecifics) GetPasswordEncryptionKey() string {
	if m != nil && m.PasswordEncryptionKey != nil {
		return *m.PasswordEncryptionKey
	}
	return ""
}

func init() {
	proto.RegisterType((*ManagedUserSpecifics)(nil), "sync_pb.ManagedUserSpecifics")
}

func init() {
	proto.RegisterFile("components/sync/protocol/managed_user_specifics.proto", fileDescriptor_managed_user_specifics_c3baf771fffac35c)
}

var fileDescriptor_managed_user_specifics_c3baf771fffac35c = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0xb7, 0xb9, 0xed, 0x31, 0x27, 0x84, 0xa9, 0xbd, 0x08, 0x43, 0x11, 0x27, 0x42,
	0x77, 0x51, 0x0f, 0xde, 0x14, 0x04, 0x61, 0x08, 0xb2, 0xe1, 0xb9, 0xc4, 0xf4, 0xad, 0x86, 0xad,
	0x49, 0xc9, 0xcb, 0x1c, 0xfd, 0x76, 0x7e, 0x34, 0xd9, 0xab, 0x99, 0x78, 0x6b, 0xff, 0xbf, 0xdf,
	0x3f, 0x79, 0xe4, 0xc1, 0x9d, 0xb2, 0x65, 0x65, 0x0d, 0x1a, 0x4f, 0x53, 0xaa, 0x8d, 0x9a, 0x56,
	0xce, 0x7a, 0xab, 0xec, 0x7a, 0x5a, 0x4a, 0x23, 0x0b, 0xcc, 0xb3, 0x0d, 0xa1, 0xcb, 0xa8, 0x42,
	0xa5, 0x97, 0x5a, 0x51, 0xca, 0x5c, 0x74, 0x77, 0x6e, 0x56, 0x7d, 0x9c, 0x7f, 0xc7, 0x30, 0x7a,
	0x6d, 0xcc, 0x77, 0x42, 0xb7, 0x08, 0x9e, 0x18, 0x42, 0xac, 0xf3, 0x24, 0x1a, 0x47, 0x93, 0xfe,
	0x3c, 0xd6, 0xb9, 0x10, 0xd0, 0x36, 0xb2, 0xc4, 0x24, 0xe6, 0x84, 0xbf, 0xc5, 0x35, 0x0c, 0xa4,
	0x5a, 0x19, 0xbb, 0x5d, 0x63, 0x5e, 0x60, 0x9e, 0xb4, 0xc6, 0xd1, 0xa4, 0xf7, 0xd0, 0x59, 0xca,
	0x35, 0xe1, 0xfc, 0x1f, 0x12, 0x67, 0x00, 0xa5, 0x24, 0x8f, 0x2e, 0x5b, 0x61, 0x9d, 0xb4, 0xf9,
	0x90, 0x7e, 0x93, 0xcc, 0xb0, 0x16, 0x17, 0x70, 0xa8, 0x3e, 0x9d, 0x2d, 0x31, 0x93, 0x5f, 0xd2,
	0x4b, 0x97, 0x74, 0xd8, 0x18, 0x34, 0xe1, 0x23, 0x67, 0xe2, 0x0a, 0x8e, 0x9a, 0x7f, 0x4b, 0x41,
	0x3b, 0x60, 0x6d, 0x18, 0xe2, 0x5f, 0xf1, 0x16, 0x4e, 0x2a, 0x49, 0xb4, 0xb5, 0x2e, 0xcf, 0x48,
	0x17, 0x46, 0xfa, 0x8d, 0x43, 0xbe, 0xb8, 0xcb, 0xfe, 0x28, 0xd0, 0x45, 0x80, 0xbb, 0x19, 0xee,
	0xe1, 0x74, 0xdf, 0x42, 0xa3, 0x5c, 0x5d, 0x79, 0x6d, 0x0d, 0xd7, 0x7a, 0x5c, 0x3b, 0x0e, 0xf8,
	0x79, 0x4f, 0x67, 0x58, 0x3f, 0xdd, 0xc0, 0xa5, 0x75, 0x45, 0xca, 0x33, 0xe8, 0x4d, 0x99, 0xfe,
	0x6d, 0x24, 0xdd, 0xbd, 0x72, 0x1a, 0x36, 0xf2, 0xd2, 0x7a, 0x8b, 0x7e, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x3a, 0x85, 0xb7, 0x33, 0xb0, 0x01, 0x00, 0x00,
}
