// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/managed_user_setting_specifics.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Properties of managed user setting sync objects.
type ManagedUserSettingSpecifics struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManagedUserSettingSpecifics) Reset()         { *m = ManagedUserSettingSpecifics{} }
func (m *ManagedUserSettingSpecifics) String() string { return proto.CompactTextString(m) }
func (*ManagedUserSettingSpecifics) ProtoMessage()    {}
func (*ManagedUserSettingSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_managed_user_setting_specifics_8976155b70099e53, []int{0}
}
func (m *ManagedUserSettingSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManagedUserSettingSpecifics.Unmarshal(m, b)
}
func (m *ManagedUserSettingSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManagedUserSettingSpecifics.Marshal(b, m, deterministic)
}
func (dst *ManagedUserSettingSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManagedUserSettingSpecifics.Merge(dst, src)
}
func (m *ManagedUserSettingSpecifics) XXX_Size() int {
	return xxx_messageInfo_ManagedUserSettingSpecifics.Size(m)
}
func (m *ManagedUserSettingSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_ManagedUserSettingSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_ManagedUserSettingSpecifics proto.InternalMessageInfo

func (m *ManagedUserSettingSpecifics) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ManagedUserSettingSpecifics) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ManagedUserSettingSpecifics)(nil), "sync_pb.ManagedUserSettingSpecifics")
}

func init() {
	proto.RegisterFile("components/sync/protocol/managed_user_setting_specifics.proto", fileDescriptor_managed_user_setting_specifics_8976155b70099e53)
}

var fileDescriptor_managed_user_setting_specifics_8976155b70099e53 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4d, 0xce, 0xcf, 0x2d,
	0xc8, 0xcf, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2f, 0xae, 0xcc, 0x4b, 0xd6, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0xcf, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x4d, 0x89, 0x2f, 0x2d, 0x4e,
	0x2d, 0x8a, 0x2f, 0x4e, 0x2d, 0x29, 0xc9, 0xcc, 0x4b, 0x8f, 0x2f, 0x2e, 0x48, 0x4d, 0xce, 0x4c,
	0xcb, 0x4c, 0x2e, 0xd6, 0x03, 0xab, 0x13, 0x62, 0x07, 0xe9, 0x89, 0x2f, 0x48, 0x52, 0x72, 0xe7,
	0x92, 0xf6, 0x85, 0x68, 0x08, 0x2d, 0x4e, 0x2d, 0x0a, 0x86, 0x28, 0x0f, 0x86, 0xa9, 0x16, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x82, 0x10, 0x8e, 0x93, 0x36,
	0x97, 0x6a, 0x7e, 0x51, 0xba, 0x5e, 0x72, 0x46, 0x51, 0x7e, 0x6e, 0x66, 0x69, 0xae, 0x1e, 0xc2,
	0x7d, 0x7a, 0x20, 0xbb, 0xf4, 0x60, 0xee, 0xf3, 0x60, 0x0e, 0x60, 0x04, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x66, 0x1a, 0x4d, 0x9b, 0xbe, 0x00, 0x00, 0x00,
}
