// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/model_type_store_schema_descriptor.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModelTypeStoreSchemaDescriptor struct {
	VersionNumber        *int64   `protobuf:"varint,1,opt,name=version_number,json=versionNumber" json:"version_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelTypeStoreSchemaDescriptor) Reset()         { *m = ModelTypeStoreSchemaDescriptor{} }
func (m *ModelTypeStoreSchemaDescriptor) String() string { return proto.CompactTextString(m) }
func (*ModelTypeStoreSchemaDescriptor) ProtoMessage()    {}
func (*ModelTypeStoreSchemaDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_type_store_schema_descriptor_590a03c58c05a8af, []int{0}
}
func (m *ModelTypeStoreSchemaDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelTypeStoreSchemaDescriptor.Unmarshal(m, b)
}
func (m *ModelTypeStoreSchemaDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelTypeStoreSchemaDescriptor.Marshal(b, m, deterministic)
}
func (dst *ModelTypeStoreSchemaDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelTypeStoreSchemaDescriptor.Merge(dst, src)
}
func (m *ModelTypeStoreSchemaDescriptor) XXX_Size() int {
	return xxx_messageInfo_ModelTypeStoreSchemaDescriptor.Size(m)
}
func (m *ModelTypeStoreSchemaDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelTypeStoreSchemaDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_ModelTypeStoreSchemaDescriptor proto.InternalMessageInfo

func (m *ModelTypeStoreSchemaDescriptor) GetVersionNumber() int64 {
	if m != nil && m.VersionNumber != nil {
		return *m.VersionNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*ModelTypeStoreSchemaDescriptor)(nil), "sync_pb.ModelTypeStoreSchemaDescriptor")
}

func init() {
	proto.RegisterFile("components/sync/protocol/model_type_store_schema_descriptor.proto", fileDescriptor_model_type_store_schema_descriptor_590a03c58c05a8af)
}

var fileDescriptor_model_type_store_schema_descriptor_590a03c58c05a8af = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0xcd, 0xaa, 0xc2, 0x30,
	0x10, 0x86, 0x61, 0x4a, 0x17, 0x07, 0x02, 0xc7, 0x45, 0x57, 0xae, 0x44, 0x84, 0x82, 0x20, 0xa4,
	0xd7, 0xa0, 0x08, 0xba, 0x51, 0xc4, 0xba, 0x0f, 0x36, 0x1d, 0x6c, 0xa1, 0xc9, 0x0c, 0x33, 0xa9,
	0xd0, 0xbb, 0x97, 0x04, 0x7f, 0xb6, 0x1f, 0xf3, 0x30, 0xaf, 0xda, 0x5a, 0x74, 0x84, 0x1e, 0x7c,
	0x90, 0x4a, 0x26, 0x6f, 0x2b, 0x62, 0x0c, 0x68, 0x71, 0xa8, 0x1c, 0xb6, 0x30, 0x98, 0x30, 0x11,
	0x18, 0x09, 0xc8, 0x60, 0xc4, 0x76, 0xe0, 0xee, 0xa6, 0x05, 0xb1, 0xdc, 0x53, 0x40, 0xd6, 0xe9,
	0xb6, 0xf8, 0x8b, 0xce, 0x50, 0xb3, 0x3a, 0xa8, 0xc5, 0x29, 0xa2, 0xdb, 0x44, 0x50, 0x47, 0x52,
	0x27, 0xb1, 0xff, 0x82, 0xa2, 0x54, 0xb3, 0x27, 0xb0, 0xf4, 0xe8, 0x8d, 0x1f, 0x5d, 0x03, 0x3c,
	0xcf, 0x96, 0xd9, 0x3a, 0xbf, 0xfe, 0xbf, 0xd7, 0x73, 0x1a, 0x77, 0x1b, 0x55, 0x22, 0x3f, 0xb4,
	0xed, 0x18, 0x5d, 0x3f, 0x3a, 0xfd, 0x6b, 0xd4, 0xf1, 0x97, 0xfe, 0x34, 0x1e, 0xf3, 0x4b, 0xf6,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xe1, 0x59, 0x8d, 0xc2, 0x00, 0x00, 0x00,
}
