// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/nigori_specifics.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The state of the passphrase required to decrypt |encryption_keybag|.
type NigoriSpecifics_PassphraseType int32

const (
	// Proto enums should begin with an 'unknown' value for switch statements,
	// unknown fields, etc.
	NigoriSpecifics_UNKNOWN NigoriSpecifics_PassphraseType = 0
	// Gaia-based encryption passphrase. Legacy.
	NigoriSpecifics_IMPLICIT_PASSPHRASE NigoriSpecifics_PassphraseType = 1
	// Keystore key encryption passphrase. Uses |keystore_bootstrap| to
	// decrypt |encryption_keybag|.
	NigoriSpecifics_KEYSTORE_PASSPHRASE NigoriSpecifics_PassphraseType = 2
	// Previous Gaia-based passphrase frozen and treated as a custom passphrase.
	NigoriSpecifics_FROZEN_IMPLICIT_PASSPHRASE NigoriSpecifics_PassphraseType = 3
	// User provided custom passphrase.
	NigoriSpecifics_CUSTOM_PASSPHRASE NigoriSpecifics_PassphraseType = 4
	// Encryption key provided by a trusted vault.
	NigoriSpecifics_TRUSTED_VAULT_PASSPHRASE NigoriSpecifics_PassphraseType = 5
)

var NigoriSpecifics_PassphraseType_name = map[int32]string{
	0: "UNKNOWN",
	1: "IMPLICIT_PASSPHRASE",
	2: "KEYSTORE_PASSPHRASE",
	3: "FROZEN_IMPLICIT_PASSPHRASE",
	4: "CUSTOM_PASSPHRASE",
	5: "TRUSTED_VAULT_PASSPHRASE",
}
var NigoriSpecifics_PassphraseType_value = map[string]int32{
	"UNKNOWN":                    0,
	"IMPLICIT_PASSPHRASE":        1,
	"KEYSTORE_PASSPHRASE":        2,
	"FROZEN_IMPLICIT_PASSPHRASE": 3,
	"CUSTOM_PASSPHRASE":          4,
	"TRUSTED_VAULT_PASSPHRASE":   5,
}

func (x NigoriSpecifics_PassphraseType) Enum() *NigoriSpecifics_PassphraseType {
	p := new(NigoriSpecifics_PassphraseType)
	*p = x
	return p
}
func (x NigoriSpecifics_PassphraseType) String() string {
	return proto.EnumName(NigoriSpecifics_PassphraseType_name, int32(x))
}
func (x *NigoriSpecifics_PassphraseType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NigoriSpecifics_PassphraseType_value, data, "NigoriSpecifics_PassphraseType")
	if err != nil {
		return err
	}
	*x = NigoriSpecifics_PassphraseType(value)
	return nil
}
func (NigoriSpecifics_PassphraseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nigori_specifics_4c8fb066a5eef55c, []int{2, 0}
}

type NigoriSpecifics_KeyDerivationMethod int32

const (
	// This comes from a <= M69 client, who does not know about the field
	// (but implicitly uses PBKDF2_HMAC_SHA1_1003).
	NigoriSpecifics_UNSPECIFIED NigoriSpecifics_KeyDerivationMethod = 0
	// PBKDF2-HMAC-SHA1 with 1003 iterations and constant hardcoded salt. Was
	// implicitly used in <= M69.
	NigoriSpecifics_PBKDF2_HMAC_SHA1_1003 NigoriSpecifics_KeyDerivationMethod = 1
	// scrypt with N = 2^13, r = 8, p = 11 and random salt. Was added in M70.
	NigoriSpecifics_SCRYPT_8192_8_11 NigoriSpecifics_KeyDerivationMethod = 2
)

var NigoriSpecifics_KeyDerivationMethod_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "PBKDF2_HMAC_SHA1_1003",
	2: "SCRYPT_8192_8_11",
}
var NigoriSpecifics_KeyDerivationMethod_value = map[string]int32{
	"UNSPECIFIED":           0,
	"PBKDF2_HMAC_SHA1_1003": 1,
	"SCRYPT_8192_8_11":      2,
}

func (x NigoriSpecifics_KeyDerivationMethod) Enum() *NigoriSpecifics_KeyDerivationMethod {
	p := new(NigoriSpecifics_KeyDerivationMethod)
	*p = x
	return p
}
func (x NigoriSpecifics_KeyDerivationMethod) String() string {
	return proto.EnumName(NigoriSpecifics_KeyDerivationMethod_name, int32(x))
}
func (x *NigoriSpecifics_KeyDerivationMethod) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NigoriSpecifics_KeyDerivationMethod_value, data, "NigoriSpecifics_KeyDerivationMethod")
	if err != nil {
		return err
	}
	*x = NigoriSpecifics_KeyDerivationMethod(value)
	return nil
}
func (NigoriSpecifics_KeyDerivationMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_nigori_specifics_4c8fb066a5eef55c, []int{2, 1}
}

type NigoriKey struct {
	// Note that M78 and before rely on the name being populated, at least for
	// the main encrypted keybag within NigoriSpecifics.
	DeprecatedName       *string  `protobuf:"bytes,1,opt,name=deprecated_name,json=deprecatedName" json:"deprecated_name,omitempty"`            // Deprecated: Do not use.
	DeprecatedUserKey    []byte   `protobuf:"bytes,2,opt,name=deprecated_user_key,json=deprecatedUserKey" json:"deprecated_user_key,omitempty"` // Deprecated: Do not use.
	EncryptionKey        []byte   `protobuf:"bytes,3,opt,name=encryption_key,json=encryptionKey" json:"encryption_key,omitempty"`
	MacKey               []byte   `protobuf:"bytes,4,opt,name=mac_key,json=macKey" json:"mac_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NigoriKey) Reset()         { *m = NigoriKey{} }
func (m *NigoriKey) String() string { return proto.CompactTextString(m) }
func (*NigoriKey) ProtoMessage()    {}
func (*NigoriKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_nigori_specifics_4c8fb066a5eef55c, []int{0}
}
func (m *NigoriKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NigoriKey.Unmarshal(m, b)
}
func (m *NigoriKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NigoriKey.Marshal(b, m, deterministic)
}
func (dst *NigoriKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NigoriKey.Merge(dst, src)
}
func (m *NigoriKey) XXX_Size() int {
	return xxx_messageInfo_NigoriKey.Size(m)
}
func (m *NigoriKey) XXX_DiscardUnknown() {
	xxx_messageInfo_NigoriKey.DiscardUnknown(m)
}

var xxx_messageInfo_NigoriKey proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *NigoriKey) GetDeprecatedName() string {
	if m != nil && m.DeprecatedName != nil {
		return *m.DeprecatedName
	}
	return ""
}

// Deprecated: Do not use.
func (m *NigoriKey) GetDeprecatedUserKey() []byte {
	if m != nil {
		return m.DeprecatedUserKey
	}
	return nil
}

func (m *NigoriKey) GetEncryptionKey() []byte {
	if m != nil {
		return m.EncryptionKey
	}
	return nil
}

func (m *NigoriKey) GetMacKey() []byte {
	if m != nil {
		return m.MacKey
	}
	return nil
}

type NigoriKeyBag struct {
	Key                  []*NigoriKey `protobuf:"bytes,2,rep,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NigoriKeyBag) Reset()         { *m = NigoriKeyBag{} }
func (m *NigoriKeyBag) String() string { return proto.CompactTextString(m) }
func (*NigoriKeyBag) ProtoMessage()    {}
func (*NigoriKeyBag) Descriptor() ([]byte, []int) {
	return fileDescriptor_nigori_specifics_4c8fb066a5eef55c, []int{1}
}
func (m *NigoriKeyBag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NigoriKeyBag.Unmarshal(m, b)
}
func (m *NigoriKeyBag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NigoriKeyBag.Marshal(b, m, deterministic)
}
func (dst *NigoriKeyBag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NigoriKeyBag.Merge(dst, src)
}
func (m *NigoriKeyBag) XXX_Size() int {
	return xxx_messageInfo_NigoriKeyBag.Size(m)
}
func (m *NigoriKeyBag) XXX_DiscardUnknown() {
	xxx_messageInfo_NigoriKeyBag.DiscardUnknown(m)
}

var xxx_messageInfo_NigoriKeyBag proto.InternalMessageInfo

func (m *NigoriKeyBag) GetKey() []*NigoriKey {
	if m != nil {
		return m.Key
	}
	return nil
}

// Properties of nigori sync object.
type NigoriSpecifics struct {
	EncryptionKeybag *EncryptedData `protobuf:"bytes,1,opt,name=encryption_keybag,json=encryptionKeybag" json:"encryption_keybag,omitempty"`
	// Once keystore migration is performed, we have to freeze the keybag so that
	// older clients (that don't support keystore encryption) do not attempt to
	// update the keybag.
	// Previously |using_explicit_passphrase|.
	KeybagIsFrozen *bool `protobuf:"varint,2,opt,name=keybag_is_frozen,json=keybagIsFrozen" json:"keybag_is_frozen,omitempty"`
	// Booleans corresponding to whether a datatype should be encrypted.
	// Passwords and Wi-Fi configurations are always encrypted, so we don't need
	// a field here.  History delete directives need to be consumable by the
	// server, and thus can't be encrypted.
	EncryptBookmarks       *bool `protobuf:"varint,13,opt,name=encrypt_bookmarks,json=encryptBookmarks" json:"encrypt_bookmarks,omitempty"`
	EncryptPreferences     *bool `protobuf:"varint,14,opt,name=encrypt_preferences,json=encryptPreferences" json:"encrypt_preferences,omitempty"`
	EncryptAutofillProfile *bool `protobuf:"varint,15,opt,name=encrypt_autofill_profile,json=encryptAutofillProfile" json:"encrypt_autofill_profile,omitempty"`
	EncryptAutofill        *bool `protobuf:"varint,16,opt,name=encrypt_autofill,json=encryptAutofill" json:"encrypt_autofill,omitempty"`
	EncryptThemes          *bool `protobuf:"varint,17,opt,name=encrypt_themes,json=encryptThemes" json:"encrypt_themes,omitempty"`
	EncryptTypedUrls       *bool `protobuf:"varint,18,opt,name=encrypt_typed_urls,json=encryptTypedUrls" json:"encrypt_typed_urls,omitempty"`
	EncryptExtensions      *bool `protobuf:"varint,19,opt,name=encrypt_extensions,json=encryptExtensions" json:"encrypt_extensions,omitempty"`
	EncryptSessions        *bool `protobuf:"varint,20,opt,name=encrypt_sessions,json=encryptSessions" json:"encrypt_sessions,omitempty"`
	EncryptApps            *bool `protobuf:"varint,21,opt,name=encrypt_apps,json=encryptApps" json:"encrypt_apps,omitempty"`
	EncryptSearchEngines   *bool `protobuf:"varint,22,opt,name=encrypt_search_engines,json=encryptSearchEngines" json:"encrypt_search_engines,omitempty"`
	// If true, all current and future datatypes will be encrypted.
	EncryptEverything        *bool `protobuf:"varint,24,opt,name=encrypt_everything,json=encryptEverything" json:"encrypt_everything,omitempty"`
	EncryptExtensionSettings *bool `protobuf:"varint,25,opt,name=encrypt_extension_settings,json=encryptExtensionSettings" json:"encrypt_extension_settings,omitempty"`
	EncryptAppNotifications  *bool `protobuf:"varint,26,opt,name=encrypt_app_notifications,json=encryptAppNotifications" json:"encrypt_app_notifications,omitempty"` // Deprecated: Do not use.
	EncryptAppSettings       *bool `protobuf:"varint,27,opt,name=encrypt_app_settings,json=encryptAppSettings" json:"encrypt_app_settings,omitempty"`
	// Enable syncing favicons as part of tab sync.
	SyncTabFavicons *bool `protobuf:"varint,29,opt,name=sync_tab_favicons,json=syncTabFavicons" json:"sync_tab_favicons,omitempty"`
	// An |int| field is used instead of enum PassphraseType so we can better
	// handle unknown values coming from later versions. Prior to M77, this was an
	// enum so old clients will assume IMPLICIT_PASSPHRASE for values greater than
	// 4.
	PassphraseType *int32 `protobuf:"varint,30,opt,name=passphrase_type,json=passphraseType,def=1" json:"passphrase_type,omitempty"`
	// The keystore decryptor token blob. Encrypted with the keystore key, and
	// contains the encryption key used to decrypt |encryption_keybag|.
	// Only set if passphrase_state == KEYSTORE_PASSPHRASE.
	KeystoreDecryptorToken *EncryptedData `protobuf:"bytes,31,opt,name=keystore_decryptor_token,json=keystoreDecryptorToken" json:"keystore_decryptor_token,omitempty"`
	// The time (in milliseconds since Unix epoch) at which the keystore migration
	// was performed.
	KeystoreMigrationTime *int64 `protobuf:"varint,32,opt,name=keystore_migration_time,json=keystoreMigrationTime" json:"keystore_migration_time,omitempty"`
	// The time (in milliseconds since Unix epoch) at which a custom passphrase
	// was set. Note: this field may not be set if the custom passphrase was
	// applied before this field was introduced.
	CustomPassphraseTime *int64 `protobuf:"varint,33,opt,name=custom_passphrase_time,json=customPassphraseTime" json:"custom_passphrase_time,omitempty"`
	// Boolean corresponding to whether custom spelling dictionary should be
	// encrypted.
	EncryptDictionary *bool `protobuf:"varint,34,opt,name=encrypt_dictionary,json=encryptDictionary" json:"encrypt_dictionary,omitempty"`
	// Boolean corresponding to whether app list items should be encrypted.
	EncryptAppList *bool `protobuf:"varint,38,opt,name=encrypt_app_list,json=encryptAppList" json:"encrypt_app_list,omitempty"`
	// Boolean corresponding to whether usage count and last use date of Wallet
	// data should be encrypted.
	EncryptAutofillWalletMetadata *bool `protobuf:"varint,39,opt,name=encrypt_autofill_wallet_metadata,json=encryptAutofillWalletMetadata" json:"encrypt_autofill_wallet_metadata,omitempty"`
	// Boolean indicating whether this node was originally missing a
	// |keystore_migration_time| field value, and was fixed on the server by
	// giving the field a value.
	// THIS FIELD SHOULD ONLY BE SET BY THE SERVER.
	ServerOnlyWasMissingKeystoreMigrationTime *bool `protobuf:"varint,40,opt,name=server_only_was_missing_keystore_migration_time,json=serverOnlyWasMissingKeystoreMigrationTime" json:"server_only_was_missing_keystore_migration_time,omitempty"`
	// Boolean corresponding to whether arc pakcage items should be encrypted.
	EncryptArcPackage *bool `protobuf:"varint,41,opt,name=encrypt_arc_package,json=encryptArcPackage" json:"encrypt_arc_package,omitempty"`
	// Boolean corresponding to whether printer items should be encrypted.
	EncryptPrinters *bool `protobuf:"varint,42,opt,name=encrypt_printers,json=encryptPrinters" json:"encrypt_printers,omitempty"`
	// Boolean corresponding to whether reading list items should be encrypted.
	EncryptReadingList *bool `protobuf:"varint,43,opt,name=encrypt_reading_list,json=encryptReadingList" json:"encrypt_reading_list,omitempty"`
	// ID of the method used to derive the encryption key from a custom
	// passphrase. Should be set only when |passphrase_type| is CUSTOM_PASSPHRASE
	// and only based on CustomPassphraseKeyDerivationMethod. This field has been
	// added in M70. All previous versions just ignore it, attempt to use
	// PBKDF2_HMAC_SHA1_1003 and, thus, reject any passphrase if a different
	// method has been used. The default corresponds to UNSPECIFIED. An |int|
	// field is used so we can detect unknown values coming from later versions.
	CustomPassphraseKeyDerivationMethod *int32 `protobuf:"varint,45,opt,name=custom_passphrase_key_derivation_method,json=customPassphraseKeyDerivationMethod,def=0" json:"custom_passphrase_key_derivation_method,omitempty"`
	// Base64-encoded salt used for the derivation of the key from the custom
	// passphrase. Valid only if custom_passphrase_key_derivation_method ==
	// SCRYPT_8192_8_11, ignored in other cases.
	CustomPassphraseKeyDerivationSalt *string `protobuf:"bytes,46,opt,name=custom_passphrase_key_derivation_salt,json=customPassphraseKeyDerivationSalt" json:"custom_passphrase_key_derivation_salt,omitempty"`
	// Boolean corresponding to whether send tab should be encrypted.
	EncryptSendTabToSelf *bool `protobuf:"varint,47,opt,name=encrypt_send_tab_to_self,json=encryptSendTabToSelf" json:"encrypt_send_tab_to_self,omitempty"`
	// Boolean corresponding to whether Web Apps data should be encrypted.
	EncryptWebApps *bool `protobuf:"varint,48,opt,name=encrypt_web_apps,json=encryptWebApps" json:"encrypt_web_apps,omitempty"`
	// Boolean corresponding to whether OS preferences should be encrypted.
	EncryptOsPreferences  *bool                                  `protobuf:"varint,49,opt,name=encrypt_os_preferences,json=encryptOsPreferences" json:"encrypt_os_preferences,omitempty"`
	TrustedVaultDebugInfo *NigoriSpecifics_TrustedVaultDebugInfo `protobuf:"bytes,50,opt,name=trusted_vault_debug_info,json=trustedVaultDebugInfo" json:"trusted_vault_debug_info,omitempty"`
	// Boolean corresponding to whether workspace desk should be encrypted.
	EncryptWorkspaceDesk *bool    `protobuf:"varint,51,opt,name=encrypt_workspace_desk,json=encryptWorkspaceDesk" json:"encrypt_workspace_desk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NigoriSpecifics) Reset()         { *m = NigoriSpecifics{} }
func (m *NigoriSpecifics) String() string { return proto.CompactTextString(m) }
func (*NigoriSpecifics) ProtoMessage()    {}
func (*NigoriSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_nigori_specifics_4c8fb066a5eef55c, []int{2}
}
func (m *NigoriSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NigoriSpecifics.Unmarshal(m, b)
}
func (m *NigoriSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NigoriSpecifics.Marshal(b, m, deterministic)
}
func (dst *NigoriSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NigoriSpecifics.Merge(dst, src)
}
func (m *NigoriSpecifics) XXX_Size() int {
	return xxx_messageInfo_NigoriSpecifics.Size(m)
}
func (m *NigoriSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_NigoriSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_NigoriSpecifics proto.InternalMessageInfo

const Default_NigoriSpecifics_PassphraseType int32 = 1
const Default_NigoriSpecifics_CustomPassphraseKeyDerivationMethod int32 = 0

func (m *NigoriSpecifics) GetEncryptionKeybag() *EncryptedData {
	if m != nil {
		return m.EncryptionKeybag
	}
	return nil
}

func (m *NigoriSpecifics) GetKeybagIsFrozen() bool {
	if m != nil && m.KeybagIsFrozen != nil {
		return *m.KeybagIsFrozen
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptBookmarks() bool {
	if m != nil && m.EncryptBookmarks != nil {
		return *m.EncryptBookmarks
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptPreferences() bool {
	if m != nil && m.EncryptPreferences != nil {
		return *m.EncryptPreferences
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptAutofillProfile() bool {
	if m != nil && m.EncryptAutofillProfile != nil {
		return *m.EncryptAutofillProfile
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptAutofill() bool {
	if m != nil && m.EncryptAutofill != nil {
		return *m.EncryptAutofill
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptThemes() bool {
	if m != nil && m.EncryptThemes != nil {
		return *m.EncryptThemes
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptTypedUrls() bool {
	if m != nil && m.EncryptTypedUrls != nil {
		return *m.EncryptTypedUrls
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptExtensions() bool {
	if m != nil && m.EncryptExtensions != nil {
		return *m.EncryptExtensions
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptSessions() bool {
	if m != nil && m.EncryptSessions != nil {
		return *m.EncryptSessions
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptApps() bool {
	if m != nil && m.EncryptApps != nil {
		return *m.EncryptApps
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptSearchEngines() bool {
	if m != nil && m.EncryptSearchEngines != nil {
		return *m.EncryptSearchEngines
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptEverything() bool {
	if m != nil && m.EncryptEverything != nil {
		return *m.EncryptEverything
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptExtensionSettings() bool {
	if m != nil && m.EncryptExtensionSettings != nil {
		return *m.EncryptExtensionSettings
	}
	return false
}

// Deprecated: Do not use.
func (m *NigoriSpecifics) GetEncryptAppNotifications() bool {
	if m != nil && m.EncryptAppNotifications != nil {
		return *m.EncryptAppNotifications
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptAppSettings() bool {
	if m != nil && m.EncryptAppSettings != nil {
		return *m.EncryptAppSettings
	}
	return false
}

func (m *NigoriSpecifics) GetSyncTabFavicons() bool {
	if m != nil && m.SyncTabFavicons != nil {
		return *m.SyncTabFavicons
	}
	return false
}

func (m *NigoriSpecifics) GetPassphraseType() int32 {
	if m != nil && m.PassphraseType != nil {
		return *m.PassphraseType
	}
	return Default_NigoriSpecifics_PassphraseType
}

func (m *NigoriSpecifics) GetKeystoreDecryptorToken() *EncryptedData {
	if m != nil {
		return m.KeystoreDecryptorToken
	}
	return nil
}

func (m *NigoriSpecifics) GetKeystoreMigrationTime() int64 {
	if m != nil && m.KeystoreMigrationTime != nil {
		return *m.KeystoreMigrationTime
	}
	return 0
}

func (m *NigoriSpecifics) GetCustomPassphraseTime() int64 {
	if m != nil && m.CustomPassphraseTime != nil {
		return *m.CustomPassphraseTime
	}
	return 0
}

func (m *NigoriSpecifics) GetEncryptDictionary() bool {
	if m != nil && m.EncryptDictionary != nil {
		return *m.EncryptDictionary
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptAppList() bool {
	if m != nil && m.EncryptAppList != nil {
		return *m.EncryptAppList
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptAutofillWalletMetadata() bool {
	if m != nil && m.EncryptAutofillWalletMetadata != nil {
		return *m.EncryptAutofillWalletMetadata
	}
	return false
}

func (m *NigoriSpecifics) GetServerOnlyWasMissingKeystoreMigrationTime() bool {
	if m != nil && m.ServerOnlyWasMissingKeystoreMigrationTime != nil {
		return *m.ServerOnlyWasMissingKeystoreMigrationTime
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptArcPackage() bool {
	if m != nil && m.EncryptArcPackage != nil {
		return *m.EncryptArcPackage
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptPrinters() bool {
	if m != nil && m.EncryptPrinters != nil {
		return *m.EncryptPrinters
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptReadingList() bool {
	if m != nil && m.EncryptReadingList != nil {
		return *m.EncryptReadingList
	}
	return false
}

func (m *NigoriSpecifics) GetCustomPassphraseKeyDerivationMethod() int32 {
	if m != nil && m.CustomPassphraseKeyDerivationMethod != nil {
		return *m.CustomPassphraseKeyDerivationMethod
	}
	return Default_NigoriSpecifics_CustomPassphraseKeyDerivationMethod
}

func (m *NigoriSpecifics) GetCustomPassphraseKeyDerivationSalt() string {
	if m != nil && m.CustomPassphraseKeyDerivationSalt != nil {
		return *m.CustomPassphraseKeyDerivationSalt
	}
	return ""
}

func (m *NigoriSpecifics) GetEncryptSendTabToSelf() bool {
	if m != nil && m.EncryptSendTabToSelf != nil {
		return *m.EncryptSendTabToSelf
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptWebApps() bool {
	if m != nil && m.EncryptWebApps != nil {
		return *m.EncryptWebApps
	}
	return false
}

func (m *NigoriSpecifics) GetEncryptOsPreferences() bool {
	if m != nil && m.EncryptOsPreferences != nil {
		return *m.EncryptOsPreferences
	}
	return false
}

func (m *NigoriSpecifics) GetTrustedVaultDebugInfo() *NigoriSpecifics_TrustedVaultDebugInfo {
	if m != nil {
		return m.TrustedVaultDebugInfo
	}
	return nil
}

func (m *NigoriSpecifics) GetEncryptWorkspaceDesk() bool {
	if m != nil && m.EncryptWorkspaceDesk != nil {
		return *m.EncryptWorkspaceDesk
	}
	return false
}

// Some debug-only fields for passphrase type TRUSTED_VAULT_PASSPHRASE.
type NigoriSpecifics_TrustedVaultDebugInfo struct {
	// The time (in milliseconds since Unix epoch) at which the trusted vault
	// migration was performed.
	MigrationTime *int64 `protobuf:"varint,1,opt,name=migration_time,json=migrationTime" json:"migration_time,omitempty"`
	// The version (aka key epoch) corresponding to the Nigori keybag.
	KeyVersion           *int32   `protobuf:"varint,2,opt,name=key_version,json=keyVersion" json:"key_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NigoriSpecifics_TrustedVaultDebugInfo) Reset()         { *m = NigoriSpecifics_TrustedVaultDebugInfo{} }
func (m *NigoriSpecifics_TrustedVaultDebugInfo) String() string { return proto.CompactTextString(m) }
func (*NigoriSpecifics_TrustedVaultDebugInfo) ProtoMessage()    {}
func (*NigoriSpecifics_TrustedVaultDebugInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_nigori_specifics_4c8fb066a5eef55c, []int{2, 0}
}
func (m *NigoriSpecifics_TrustedVaultDebugInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NigoriSpecifics_TrustedVaultDebugInfo.Unmarshal(m, b)
}
func (m *NigoriSpecifics_TrustedVaultDebugInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NigoriSpecifics_TrustedVaultDebugInfo.Marshal(b, m, deterministic)
}
func (dst *NigoriSpecifics_TrustedVaultDebugInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NigoriSpecifics_TrustedVaultDebugInfo.Merge(dst, src)
}
func (m *NigoriSpecifics_TrustedVaultDebugInfo) XXX_Size() int {
	return xxx_messageInfo_NigoriSpecifics_TrustedVaultDebugInfo.Size(m)
}
func (m *NigoriSpecifics_TrustedVaultDebugInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NigoriSpecifics_TrustedVaultDebugInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NigoriSpecifics_TrustedVaultDebugInfo proto.InternalMessageInfo

func (m *NigoriSpecifics_TrustedVaultDebugInfo) GetMigrationTime() int64 {
	if m != nil && m.MigrationTime != nil {
		return *m.MigrationTime
	}
	return 0
}

func (m *NigoriSpecifics_TrustedVaultDebugInfo) GetKeyVersion() int32 {
	if m != nil && m.KeyVersion != nil {
		return *m.KeyVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*NigoriKey)(nil), "sync_pb.NigoriKey")
	proto.RegisterType((*NigoriKeyBag)(nil), "sync_pb.NigoriKeyBag")
	proto.RegisterType((*NigoriSpecifics)(nil), "sync_pb.NigoriSpecifics")
	proto.RegisterType((*NigoriSpecifics_TrustedVaultDebugInfo)(nil), "sync_pb.NigoriSpecifics.TrustedVaultDebugInfo")
	proto.RegisterEnum("sync_pb.NigoriSpecifics_PassphraseType", NigoriSpecifics_PassphraseType_name, NigoriSpecifics_PassphraseType_value)
	proto.RegisterEnum("sync_pb.NigoriSpecifics_KeyDerivationMethod", NigoriSpecifics_KeyDerivationMethod_name, NigoriSpecifics_KeyDerivationMethod_value)
}

func init() {
	proto.RegisterFile("components/sync/protocol/nigori_specifics.proto", fileDescriptor_nigori_specifics_4c8fb066a5eef55c)
}

var fileDescriptor_nigori_specifics_4c8fb066a5eef55c = []byte{
	// 1432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0x6b, 0x4f, 0x1b, 0x3d,
	0x16, 0x6e, 0x60, 0x28, 0x83, 0xc3, 0x65, 0x30, 0x37, 0x43, 0x4b, 0x0b, 0xb4, 0xb4, 0x50, 0xda,
	0x70, 0x69, 0x55, 0x75, 0x57, 0xab, 0x95, 0x02, 0x09, 0x0b, 0x43, 0x09, 0xd1, 0x24, 0x14, 0x75,
	0xbf, 0x58, 0xce, 0xc4, 0x09, 0xa3, 0xcc, 0x4d, 0xb6, 0x03, 0x9b, 0xfd, 0x3d, 0xfb, 0x71, 0xff,
	0xe3, 0xfb, 0xca, 0x9e, 0xcc, 0x2d, 0xa4, 0x7d, 0x3f, 0x8d, 0x74, 0x9e, 0xe7, 0x39, 0x3e, 0xe7,
	0xf8, 0x1c, 0xdb, 0x03, 0x0e, 0xed, 0xc0, 0x0b, 0x03, 0x9f, 0xfa, 0x82, 0x1f, 0xf2, 0x81, 0x6f,
	0x1f, 0x86, 0x2c, 0x10, 0x81, 0x1d, 0xb8, 0x87, 0xbe, 0xd3, 0x0d, 0x98, 0x83, 0x79, 0x48, 0x6d,
	0xa7, 0xe3, 0xd8, 0xbc, 0xa4, 0x10, 0x38, 0x2d, 0x59, 0x38, 0x6c, 0x6d, 0xec, 0xff, 0x52, 0x49,
	0x7d, 0x9b, 0x0d, 0x42, 0xe1, 0x04, 0x7e, 0xa4, 0xd9, 0xf9, 0x7f, 0x01, 0xcc, 0xd4, 0x94, 0xbb,
	0x2b, 0x3a, 0x80, 0x07, 0x60, 0xa1, 0x4d, 0x43, 0x46, 0x6d, 0x22, 0x68, 0x1b, 0xfb, 0xc4, 0xa3,
	0xa8, 0xb0, 0x55, 0xd8, 0x9b, 0x39, 0x9d, 0x40, 0x05, 0x6b, 0x3e, 0x85, 0x6a, 0xc4, 0xa3, 0xf0,
	0x04, 0x2c, 0x65, 0xc8, 0x7d, 0x4e, 0x19, 0xee, 0xd1, 0x01, 0x9a, 0xd8, 0x2a, 0xec, 0xcd, 0x2a,
	0xc1, 0x62, 0x0a, 0xdf, 0x72, 0xca, 0xe4, 0x02, 0xbb, 0x60, 0x3e, 0x0d, 0x41, 0xd1, 0x27, 0x25,
	0xdd, 0x9a, 0x4b, 0xad, 0x92, 0xb6, 0x06, 0xa6, 0x3d, 0x62, 0x2b, 0x5c, 0x53, 0xf8, 0x73, 0x8f,
	0xd8, 0x57, 0x74, 0xb0, 0xf3, 0x05, 0xcc, 0x26, 0xd1, 0x9e, 0x92, 0x2e, 0x7c, 0x0b, 0x26, 0xa3,
	0x35, 0x27, 0xf7, 0x8a, 0x27, 0xb0, 0x34, 0x2c, 0x40, 0x29, 0xe1, 0x58, 0x12, 0xde, 0xf9, 0x63,
	0x05, 0x2c, 0x44, 0xa6, 0x46, 0x5c, 0x32, 0x78, 0x06, 0x16, 0xf3, 0x91, 0xb4, 0x48, 0x57, 0x25,
	0x5b, 0x3c, 0x59, 0x4d, 0xfc, 0x54, 0x23, 0x06, 0x6d, 0x57, 0x88, 0x20, 0x96, 0x91, 0x0b, 0xb2,
	0x45, 0xba, 0x70, 0x0f, 0x18, 0x91, 0x12, 0x3b, 0x1c, 0x77, 0x58, 0xf0, 0x5f, 0xea, 0xab, 0xfc,
	0x75, 0x6b, 0x3e, 0xb2, 0x5f, 0xf2, 0x73, 0x65, 0x85, 0x07, 0xc9, 0x72, 0xb8, 0x15, 0x04, 0x3d,
	0x8f, 0xb0, 0x1e, 0x47, 0x73, 0x8a, 0x1a, 0xbb, 0x3d, 0x8d, 0xed, 0xf0, 0x10, 0x2c, 0xc5, 0xe4,
	0x90, 0xd1, 0x0e, 0x65, 0xd4, 0xb7, 0x29, 0x47, 0xf3, 0x8a, 0x0e, 0x87, 0x50, 0x3d, 0x45, 0xe0,
	0x37, 0x80, 0x62, 0x01, 0xe9, 0x8b, 0xa0, 0xe3, 0xb8, 0x2e, 0x0e, 0x99, 0xfc, 0x52, 0xb4, 0xa0,
	0x54, 0xab, 0x43, 0xbc, 0x3c, 0x84, 0xeb, 0x11, 0x0a, 0xf7, 0x81, 0x31, 0xaa, 0x44, 0x86, 0x52,
	0x2c, 0x8c, 0x28, 0x32, 0x7b, 0x87, 0xc5, 0x3d, 0xf5, 0x28, 0x47, 0x8b, 0x8a, 0x18, 0xef, 0x5d,
	0x53, 0x19, 0xe1, 0x47, 0x00, 0x13, 0xda, 0x20, 0x94, 0x9d, 0xc1, 0x5c, 0x8e, 0x60, 0x2e, 0xd5,
	0xa6, 0x04, 0x6e, 0x99, 0xcb, 0xe1, 0xa7, 0x94, 0x4d, 0xff, 0x23, 0xa8, 0xcf, 0x9d, 0xc0, 0xe7,
	0x68, 0x49, 0xb1, 0xe3, 0x8a, 0x55, 0x13, 0x20, 0x1b, 0x2e, 0xa7, 0x3c, 0x22, 0x2f, 0xe7, 0xc2,
	0x6d, 0x0c, 0xcd, 0x70, 0x1b, 0xcc, 0x26, 0x99, 0x85, 0x21, 0x47, 0x2b, 0x8a, 0x56, 0x8c, 0xb3,
	0x0a, 0x43, 0x0e, 0xbf, 0x80, 0xd5, 0xd4, 0x1b, 0x61, 0xf6, 0x3d, 0xa6, 0x7e, 0xd7, 0xf1, 0x29,
	0x47, 0xab, 0x8a, 0xbc, 0x9c, 0xf8, 0x94, 0x60, 0x35, 0xc2, 0x72, 0x21, 0x3f, 0x50, 0x36, 0x10,
	0xf7, 0x8e, 0xdf, 0x45, 0x28, 0x1f, 0x72, 0x02, 0xc0, 0x7f, 0x80, 0x8d, 0x27, 0x19, 0x62, 0x4e,
	0x85, 0x70, 0xfc, 0x2e, 0x47, 0xeb, 0x4a, 0x86, 0x46, 0x33, 0x6d, 0x0c, 0x71, 0xf8, 0x4f, 0xb0,
	0x9e, 0xc9, 0x02, 0xfb, 0x81, 0x90, 0xed, 0x4b, 0x84, 0xca, 0x7c, 0x43, 0x8a, 0xd5, 0xa8, 0xad,
	0xa5, 0x69, 0xd5, 0xb2, 0x14, 0x78, 0x04, 0x96, 0xb3, 0xfa, 0x64, 0xdd, 0x17, 0xb9, 0x5e, 0x2a,
	0x87, 0x61, 0xb2, 0xe2, 0x07, 0xb0, 0xa8, 0xda, 0x5f, 0x90, 0x16, 0xee, 0x90, 0x07, 0xc7, 0x96,
	0x2b, 0x6d, 0x46, 0x35, 0x96, 0x40, 0x93, 0xb4, 0xce, 0x87, 0x66, 0xf8, 0x01, 0x2c, 0x84, 0x84,
	0xf3, 0xf0, 0x9e, 0x11, 0x4e, 0xd5, 0x76, 0xa3, 0x57, 0x5b, 0x85, 0xbd, 0xa9, 0xbf, 0x17, 0x8e,
	0xad, 0xf9, 0x14, 0x91, 0xdb, 0x0d, 0xeb, 0x00, 0xf5, 0xe8, 0x80, 0x8b, 0x80, 0x51, 0xdc, 0xa6,
	0x6a, 0xd9, 0x80, 0x61, 0x11, 0xf4, 0xa8, 0x8f, 0x5e, 0xff, 0x76, 0xee, 0x56, 0x63, 0x5d, 0x25,
	0x96, 0x35, 0xa5, 0x0a, 0x7e, 0x05, 0x6b, 0x89, 0x47, 0xcf, 0xe9, 0x32, 0x95, 0x32, 0x16, 0x8e,
	0x47, 0xd1, 0xd6, 0x56, 0x61, 0x6f, 0xd2, 0x5a, 0x89, 0xe1, 0xeb, 0x18, 0x6d, 0x3a, 0x1e, 0x95,
	0xdb, 0x6e, 0xf7, 0xb9, 0x08, 0x3c, 0x9c, 0x0d, 0x5e, 0xca, 0xb6, 0x95, 0x6c, 0x39, 0x42, 0xeb,
	0x69, 0xfc, 0x52, 0x95, 0xd9, 0xf6, 0xb6, 0x63, 0x4b, 0x67, 0x84, 0x0d, 0xd0, 0x4e, 0x6e, 0xdb,
	0x2b, 0x09, 0x20, 0x8f, 0x86, 0x6c, 0xe1, 0x5d, 0x87, 0x0b, 0xf4, 0x2e, 0x3a, 0x1a, 0xd2, 0xa2,
	0x7f, 0x77, 0xb8, 0x80, 0xff, 0x02, 0x5b, 0x4f, 0x86, 0xf7, 0x91, 0xb8, 0x2e, 0x15, 0xd8, 0xa3,
	0x82, 0xb4, 0x89, 0x20, 0xe8, 0xbd, 0x52, 0x6e, 0x8e, 0x8c, 0xe4, 0x9d, 0x62, 0x5d, 0x0f, 0x49,
	0xb0, 0x05, 0x0e, 0x39, 0x65, 0x0f, 0x94, 0xe1, 0xc0, 0x77, 0x07, 0xf8, 0x91, 0x70, 0xec, 0x39,
	0x9c, 0x3b, 0x7e, 0x17, 0xff, 0xaa, 0x4e, 0x7b, 0xca, 0xef, 0x7e, 0x24, 0xbb, 0xf1, 0xdd, 0xc1,
	0x1d, 0xe1, 0xd7, 0x91, 0xe6, 0x6a, 0x6c, 0xed, 0x4a, 0xe9, 0xd1, 0x44, 0x98, 0x8d, 0x43, 0x62,
	0xf7, 0x48, 0x97, 0xa2, 0xfd, 0x5c, 0x19, 0xca, 0xcc, 0xae, 0x47, 0x40, 0x76, 0x60, 0x43, 0xe6,
	0xf8, 0x82, 0x32, 0x8e, 0x3e, 0xe4, 0x06, 0xb6, 0x3e, 0x34, 0x67, 0x5b, 0x95, 0x51, 0xd2, 0x96,
	0x61, 0xab, 0xaa, 0x1d, 0xe4, 0x5a, 0xd5, 0x8a, 0x20, 0x55, 0xb9, 0x3b, 0xf0, 0xfe, 0xe9, 0x46,
	0xf6, 0xe8, 0x00, 0xb7, 0x29, 0x73, 0x1e, 0xa2, 0x34, 0x3d, 0x2a, 0xee, 0x83, 0x36, 0xfa, 0x14,
	0xb5, 0xe5, 0x91, 0xf5, 0x66, 0x74, 0x73, 0xaf, 0xe8, 0xa0, 0x92, 0xd0, 0xaf, 0x15, 0x1b, 0xd6,
	0xc1, 0xee, 0x5f, 0x3a, 0xe6, 0xc4, 0x15, 0xa8, 0x24, 0x6f, 0x47, 0x6b, 0xfb, 0xb7, 0x3e, 0x1b,
	0xc4, 0x15, 0xf0, 0x6b, 0x7a, 0x42, 0x73, 0xea, 0xb7, 0xd5, 0x74, 0x89, 0x00, 0x73, 0xea, 0x76,
	0xd0, 0xe1, 0xc8, 0x61, 0xe3, 0xb7, 0x9b, 0xa4, 0xd5, 0x0c, 0x1a, 0xd4, 0xed, 0x64, 0xdb, 0xe8,
	0x91, 0xb6, 0xa2, 0x93, 0xec, 0x28, 0xd7, 0x46, 0x77, 0xb4, 0x35, 0x7a, 0x98, 0x05, 0x3c, 0x77,
	0x6f, 0x1c, 0xe7, 0xfc, 0xdf, 0xf0, 0xec, 0xcd, 0xd1, 0x05, 0x48, 0xb0, 0x3e, 0x97, 0x37, 0xf8,
	0x03, 0xe9, 0xbb, 0x02, 0xb7, 0x69, 0xab, 0xdf, 0xc5, 0x8e, 0xdf, 0x09, 0xd0, 0x89, 0x9a, 0xca,
	0xd2, 0xc8, 0xad, 0x9a, 0x5c, 0xa1, 0xa5, 0x66, 0x24, 0xfc, 0x21, 0x75, 0x15, 0x29, 0xbb, 0xf4,
	0x3b, 0x81, 0xb5, 0x22, 0xc6, 0x99, 0xb3, 0xe1, 0x3d, 0x06, 0xac, 0xc7, 0x43, 0x62, 0xcb, 0x73,
	0x80, 0xf7, 0xd0, 0xe7, 0x5c, 0x78, 0x77, 0x31, 0x58, 0xa1, 0xbc, 0xb7, 0x81, 0xc1, 0xca, 0xd8,
	0x55, 0xe4, 0x65, 0x34, 0xd2, 0xca, 0x05, 0x35, 0xbb, 0x73, 0x5e, 0xae, 0x5d, 0x5f, 0x83, 0xa2,
	0xdc, 0xb6, 0x07, 0xca, 0xe4, 0xa9, 0xaa, 0xee, 0xe6, 0x29, 0x0b, 0xf4, 0xe8, 0xe0, 0x47, 0x64,
	0xd9, 0xf9, 0x5f, 0x01, 0xcc, 0xd7, 0xf3, 0x07, 0x55, 0x11, 0x4c, 0xdf, 0xd6, 0xae, 0x6a, 0x37,
	0x77, 0x35, 0xe3, 0x19, 0x5c, 0x03, 0x4b, 0x97, 0xd7, 0xf5, 0xef, 0x97, 0x67, 0x97, 0x4d, 0x5c,
	0x2f, 0x37, 0x1a, 0xf5, 0x0b, 0xab, 0xdc, 0xa8, 0x1a, 0x05, 0x09, 0x5c, 0x55, 0x7f, 0x36, 0x9a,
	0x37, 0x56, 0x35, 0x0b, 0x4c, 0xc0, 0x57, 0x60, 0xe3, 0xdc, 0xba, 0xf9, 0x77, 0xb5, 0x86, 0xc7,
	0x09, 0x27, 0xe1, 0x0a, 0x58, 0x3c, 0xbb, 0x6d, 0x34, 0x6f, 0xae, 0xb3, 0x66, 0x0d, 0xbe, 0x04,
	0xa8, 0x69, 0xdd, 0x36, 0x9a, 0xd5, 0x0a, 0xfe, 0x51, 0xbe, 0xfd, 0x9e, 0x13, 0x4d, 0xed, 0xdc,
	0x81, 0xa5, 0x71, 0x7d, 0xba, 0x00, 0x8a, 0xb7, 0xb5, 0x46, 0xbd, 0x7a, 0x76, 0x79, 0x7e, 0x59,
	0xad, 0x18, 0xcf, 0xe0, 0x3a, 0x58, 0xa9, 0x9f, 0x5e, 0x55, 0xce, 0x4f, 0xf0, 0xc5, 0x75, 0xf9,
	0x0c, 0x37, 0x2e, 0xca, 0xc7, 0xf8, 0xf8, 0xe8, 0xe8, 0xb3, 0x51, 0x80, 0xcb, 0xc0, 0x68, 0x9c,
	0x59, 0x3f, 0xeb, 0x4d, 0xfc, 0xed, 0xf8, 0x6f, 0x27, 0xf8, 0x1b, 0x3e, 0x3e, 0x36, 0x26, 0x4c,
	0x4d, 0x9f, 0x34, 0x34, 0x53, 0xd3, 0x35, 0x63, 0xca, 0xd4, 0xf4, 0x29, 0xe3, 0xb9, 0xa9, 0xe9,
	0xcf, 0x8d, 0x69, 0x53, 0xd3, 0xa7, 0x0d, 0xdd, 0xd4, 0x74, 0xdd, 0x98, 0x31, 0x35, 0x7d, 0xc6,
	0x00, 0xa6, 0xa6, 0x03, 0xa3, 0x68, 0x6a, 0x7a, 0xd1, 0x98, 0x35, 0x35, 0x7d, 0xd6, 0x98, 0x33,
	0x35, 0x7d, 0xcd, 0x40, 0xa6, 0xa6, 0xbf, 0x34, 0x36, 0x4d, 0x4d, 0x7f, 0x63, 0xbc, 0x35, 0x35,
	0xfd, 0xad, 0xb1, 0x6b, 0x6a, 0xfa, 0xae, 0xf1, 0xce, 0xd4, 0xf4, 0x8f, 0xc6, 0x27, 0xeb, 0x65,
	0xe6, 0x89, 0xf8, 0xe4, 0x01, 0x64, 0xbd, 0x1a, 0x83, 0x66, 0x3a, 0xd7, 0x7a, 0x33, 0x06, 0x1f,
	0x7d, 0xe0, 0x58, 0x2f, 0x7e, 0x43, 0xb2, 0xd6, 0xc7, 0x80, 0xd1, 0xeb, 0xc5, 0xda, 0x1c, 0x07,
	0x25, 0x2f, 0x96, 0xb1, 0x70, 0xfa, 0x44, 0x19, 0xbb, 0x6a, 0xfc, 0x24, 0xb1, 0xd6, 0xc6, 0x85,
	0x14, 0x86, 0xdc, 0xda, 0x1e, 0xab, 0xca, 0x3e, 0x3d, 0xac, 0x99, 0xf8, 0xf6, 0xcd, 0x87, 0xd0,
	0xa6, 0x0f, 0x8e, 0x4d, 0xd5, 0x60, 0x32, 0x4f, 0xf5, 0x80, 0x95, 0x5e, 0x30, 0x4c, 0x38, 0xb6,
	0x4b, 0x79, 0xf2, 0x0c, 0xc0, 0x5e, 0xd0, 0xf7, 0x05, 0x71, 0x7c, 0xcc, 0xef, 0x09, 0xa3, 0xfc,
	0xf4, 0x00, 0xec, 0x06, 0xac, 0x5b, 0xb2, 0xef, 0x59, 0xe0, 0x39, 0x7d, 0xaf, 0x94, 0xfe, 0x20,
	0xa8, 0xe9, 0x2e, 0xc5, 0x3f, 0x08, 0x17, 0x93, 0xf5, 0xc2, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x4a, 0x79, 0x08, 0x3f, 0x79, 0x0c, 0x00, 0x00,
}
