// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/persisted_entity_data.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Sync proto to store entity data similar to what the legacy Directory used
// to store, used to persist data locally and never sent through the wire.
//
// Because it's conceptually similar to SyncEntity (actual protocol) and it's
// unclear how big this'll grow, we've kept compatibility with SyncEntity by
// using the same field numbers.
type PersistedEntityData struct {
	// See corresponding fields in SyncEntity for details.
	Name                 *string          `protobuf:"bytes,8,opt,name=name" json:"name,omitempty"`
	Specifics            *EntitySpecifics `protobuf:"bytes,21,opt,name=specifics" json:"specifics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PersistedEntityData) Reset()         { *m = PersistedEntityData{} }
func (m *PersistedEntityData) String() string { return proto.CompactTextString(m) }
func (*PersistedEntityData) ProtoMessage()    {}
func (*PersistedEntityData) Descriptor() ([]byte, []int) {
	return fileDescriptor_persisted_entity_data_ead1c5ddc391e0dd, []int{0}
}
func (m *PersistedEntityData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistedEntityData.Unmarshal(m, b)
}
func (m *PersistedEntityData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistedEntityData.Marshal(b, m, deterministic)
}
func (dst *PersistedEntityData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistedEntityData.Merge(dst, src)
}
func (m *PersistedEntityData) XXX_Size() int {
	return xxx_messageInfo_PersistedEntityData.Size(m)
}
func (m *PersistedEntityData) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistedEntityData.DiscardUnknown(m)
}

var xxx_messageInfo_PersistedEntityData proto.InternalMessageInfo

func (m *PersistedEntityData) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PersistedEntityData) GetSpecifics() *EntitySpecifics {
	if m != nil {
		return m.Specifics
	}
	return nil
}

func init() {
	proto.RegisterType((*PersistedEntityData)(nil), "sync_pb.PersistedEntityData")
}

func init() {
	proto.RegisterFile("components/sync/protocol/persisted_entity_data.proto", fileDescriptor_persisted_entity_data_ead1c5ddc391e0dd)
}

var fileDescriptor_persisted_entity_data_ead1c5ddc391e0dd = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x49, 0xce, 0xcf, 0x2d,
	0xc8, 0xcf, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2f, 0xae, 0xcc, 0x4b, 0xd6, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0x2c, 0x2e, 0x49, 0x4d, 0x89, 0x4f,
	0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x8c, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0x4b, 0x0b, 0xb1, 0x83,
	0x94, 0xc6, 0x17, 0x24, 0x49, 0x29, 0xe3, 0xd4, 0x0e, 0xe2, 0x41, 0x54, 0x2b, 0x25, 0x72, 0x09,
	0x07, 0xc0, 0x0c, 0x73, 0x05, 0x9b, 0xe5, 0x92, 0x58, 0x92, 0x28, 0x24, 0xc4, 0xc5, 0x92, 0x97,
	0x98, 0x9b, 0x2a, 0xc1, 0xa1, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x99, 0x71, 0x71, 0x16,
	0x17, 0xa4, 0x26, 0x67, 0xa6, 0x65, 0x26, 0x17, 0x4b, 0x88, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x49,
	0xe8, 0x41, 0x2d, 0xd3, 0x83, 0xe8, 0x0d, 0x86, 0xc9, 0x07, 0x21, 0x94, 0x3a, 0x69, 0x73, 0xa9,
	0xe6, 0x17, 0xa5, 0xeb, 0x25, 0x67, 0x14, 0xe5, 0xe7, 0x66, 0x96, 0xe6, 0xea, 0x21, 0x9c, 0xa5,
	0x87, 0x70, 0x48, 0x72, 0x7e, 0x8e, 0x07, 0x73, 0x00, 0x23, 0x20, 0x00, 0x00, 0xff, 0xff, 0xaa,
	0xbb, 0x40, 0x36, 0xf4, 0x00, 0x00, 0x00,
}
