// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/sharing_message_specifics.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// This enum is used in histograms. Entries should not be renumbered and
// numeric values should never be reused. Also remember to update in
// tools/metrics/histograms/enums.xml SyncSharingMessageCommitErrorCode enum.
type SharingMessageCommitError_ErrorCode int32

const (
	SharingMessageCommitError_NONE               SharingMessageCommitError_ErrorCode = 0
	SharingMessageCommitError_INVALID_ARGUMENT   SharingMessageCommitError_ErrorCode = 1
	SharingMessageCommitError_NOT_FOUND          SharingMessageCommitError_ErrorCode = 2
	SharingMessageCommitError_INTERNAL           SharingMessageCommitError_ErrorCode = 3
	SharingMessageCommitError_UNAVAILABLE        SharingMessageCommitError_ErrorCode = 4
	SharingMessageCommitError_RESOURCE_EXHAUSTED SharingMessageCommitError_ErrorCode = 5
	SharingMessageCommitError_UNAUTHENTICATED    SharingMessageCommitError_ErrorCode = 6
	SharingMessageCommitError_PERMISSION_DENIED  SharingMessageCommitError_ErrorCode = 7
	// Client-specific error codes.
	SharingMessageCommitError_SYNC_TURNED_OFF    SharingMessageCommitError_ErrorCode = 8
	SharingMessageCommitError_SYNC_NETWORK_ERROR SharingMessageCommitError_ErrorCode = 9
	// Deprecated UMA bucket, prior to splitting between SYNC_SERVER_ERROR and
	// SYNC_AUTH_ERROR.
	SharingMessageCommitError_DEPRECATED_SYNC_SERVER_OR_AUTH_ERROR SharingMessageCommitError_ErrorCode = 10
	// Message wasn't committed before timeout.
	SharingMessageCommitError_SYNC_TIMEOUT SharingMessageCommitError_ErrorCode = 11
	// Error code for server error or unparsable server response.
	SharingMessageCommitError_SYNC_SERVER_ERROR SharingMessageCommitError_ErrorCode = 12
	// Auth error when communicating with the server.
	SharingMessageCommitError_SYNC_AUTH_ERROR SharingMessageCommitError_ErrorCode = 13
)

var SharingMessageCommitError_ErrorCode_name = map[int32]string{
	0:  "NONE",
	1:  "INVALID_ARGUMENT",
	2:  "NOT_FOUND",
	3:  "INTERNAL",
	4:  "UNAVAILABLE",
	5:  "RESOURCE_EXHAUSTED",
	6:  "UNAUTHENTICATED",
	7:  "PERMISSION_DENIED",
	8:  "SYNC_TURNED_OFF",
	9:  "SYNC_NETWORK_ERROR",
	10: "DEPRECATED_SYNC_SERVER_OR_AUTH_ERROR",
	11: "SYNC_TIMEOUT",
	12: "SYNC_SERVER_ERROR",
	13: "SYNC_AUTH_ERROR",
}
var SharingMessageCommitError_ErrorCode_value = map[string]int32{
	"NONE":                                 0,
	"INVALID_ARGUMENT":                     1,
	"NOT_FOUND":                            2,
	"INTERNAL":                             3,
	"UNAVAILABLE":                          4,
	"RESOURCE_EXHAUSTED":                   5,
	"UNAUTHENTICATED":                      6,
	"PERMISSION_DENIED":                    7,
	"SYNC_TURNED_OFF":                      8,
	"SYNC_NETWORK_ERROR":                   9,
	"DEPRECATED_SYNC_SERVER_OR_AUTH_ERROR": 10,
	"SYNC_TIMEOUT":                         11,
	"SYNC_SERVER_ERROR":                    12,
	"SYNC_AUTH_ERROR":                      13,
}

func (x SharingMessageCommitError_ErrorCode) Enum() *SharingMessageCommitError_ErrorCode {
	p := new(SharingMessageCommitError_ErrorCode)
	*p = x
	return p
}
func (x SharingMessageCommitError_ErrorCode) String() string {
	return proto.EnumName(SharingMessageCommitError_ErrorCode_name, int32(x))
}
func (x *SharingMessageCommitError_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SharingMessageCommitError_ErrorCode_value, data, "SharingMessageCommitError_ErrorCode")
	if err != nil {
		return err
	}
	*x = SharingMessageCommitError_ErrorCode(value)
	return nil
}
func (SharingMessageCommitError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sharing_message_specifics_394b77e57b137985, []int{1, 0}
}

type SharingMessageSpecifics struct {
	// Unique identifier of message.
	MessageId            *string                                       `protobuf:"bytes,1,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	ChannelConfiguration *SharingMessageSpecifics_ChannelConfiguration `protobuf:"bytes,2,opt,name=channel_configuration,json=channelConfiguration" json:"channel_configuration,omitempty"`
	// Payload encrypted using the target user keys according to WebPush
	// encryption scheme. The payload has to be a valid
	// chrome/browser/sharing/proto/sharing_message.proto serialized using
	// SerializeToString.
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharingMessageSpecifics) Reset()         { *m = SharingMessageSpecifics{} }
func (m *SharingMessageSpecifics) String() string { return proto.CompactTextString(m) }
func (*SharingMessageSpecifics) ProtoMessage()    {}
func (*SharingMessageSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_sharing_message_specifics_394b77e57b137985, []int{0}
}
func (m *SharingMessageSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharingMessageSpecifics.Unmarshal(m, b)
}
func (m *SharingMessageSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharingMessageSpecifics.Marshal(b, m, deterministic)
}
func (dst *SharingMessageSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingMessageSpecifics.Merge(dst, src)
}
func (m *SharingMessageSpecifics) XXX_Size() int {
	return xxx_messageInfo_SharingMessageSpecifics.Size(m)
}
func (m *SharingMessageSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingMessageSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_SharingMessageSpecifics proto.InternalMessageInfo

func (m *SharingMessageSpecifics) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *SharingMessageSpecifics) GetChannelConfiguration() *SharingMessageSpecifics_ChannelConfiguration {
	if m != nil {
		return m.ChannelConfiguration
	}
	return nil
}

func (m *SharingMessageSpecifics) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SharingMessageSpecifics_ChannelConfiguration struct {
	// Types that are valid to be assigned to ChannelConfiguration:
	//	*SharingMessageSpecifics_ChannelConfiguration_Fcm
	//	*SharingMessageSpecifics_ChannelConfiguration_Server
	ChannelConfiguration isSharingMessageSpecifics_ChannelConfiguration_ChannelConfiguration `protobuf_oneof:"channel_configuration"`
	XXX_NoUnkeyedLiteral struct{}                                                            `json:"-"`
	XXX_unrecognized     []byte                                                              `json:"-"`
	XXX_sizecache        int32                                                               `json:"-"`
}

func (m *SharingMessageSpecifics_ChannelConfiguration) Reset() {
	*m = SharingMessageSpecifics_ChannelConfiguration{}
}
func (m *SharingMessageSpecifics_ChannelConfiguration) String() string {
	return proto.CompactTextString(m)
}
func (*SharingMessageSpecifics_ChannelConfiguration) ProtoMessage() {}
func (*SharingMessageSpecifics_ChannelConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_sharing_message_specifics_394b77e57b137985, []int{0, 0}
}
func (m *SharingMessageSpecifics_ChannelConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration.Unmarshal(m, b)
}
func (m *SharingMessageSpecifics_ChannelConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration.Marshal(b, m, deterministic)
}
func (dst *SharingMessageSpecifics_ChannelConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration.Merge(dst, src)
}
func (m *SharingMessageSpecifics_ChannelConfiguration) XXX_Size() int {
	return xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration.Size(m)
}
func (m *SharingMessageSpecifics_ChannelConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration proto.InternalMessageInfo

type isSharingMessageSpecifics_ChannelConfiguration_ChannelConfiguration interface {
	isSharingMessageSpecifics_ChannelConfiguration_ChannelConfiguration()
}

type SharingMessageSpecifics_ChannelConfiguration_Fcm struct {
	Fcm *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration `protobuf:"bytes,1,opt,name=fcm,oneof"`
}
type SharingMessageSpecifics_ChannelConfiguration_Server struct {
	Server []byte `protobuf:"bytes,2,opt,name=server,oneof"`
}

func (*SharingMessageSpecifics_ChannelConfiguration_Fcm) isSharingMessageSpecifics_ChannelConfiguration_ChannelConfiguration() {
}
func (*SharingMessageSpecifics_ChannelConfiguration_Server) isSharingMessageSpecifics_ChannelConfiguration_ChannelConfiguration() {
}

func (m *SharingMessageSpecifics_ChannelConfiguration) GetChannelConfiguration() isSharingMessageSpecifics_ChannelConfiguration_ChannelConfiguration {
	if m != nil {
		return m.ChannelConfiguration
	}
	return nil
}

func (m *SharingMessageSpecifics_ChannelConfiguration) GetFcm() *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration {
	if x, ok := m.GetChannelConfiguration().(*SharingMessageSpecifics_ChannelConfiguration_Fcm); ok {
		return x.Fcm
	}
	return nil
}

func (m *SharingMessageSpecifics_ChannelConfiguration) GetServer() []byte {
	if x, ok := m.GetChannelConfiguration().(*SharingMessageSpecifics_ChannelConfiguration_Server); ok {
		return x.Server
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SharingMessageSpecifics_ChannelConfiguration) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SharingMessageSpecifics_ChannelConfiguration_OneofMarshaler, _SharingMessageSpecifics_ChannelConfiguration_OneofUnmarshaler, _SharingMessageSpecifics_ChannelConfiguration_OneofSizer, []interface{}{
		(*SharingMessageSpecifics_ChannelConfiguration_Fcm)(nil),
		(*SharingMessageSpecifics_ChannelConfiguration_Server)(nil),
	}
}

func _SharingMessageSpecifics_ChannelConfiguration_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SharingMessageSpecifics_ChannelConfiguration)
	// channel_configuration
	switch x := m.ChannelConfiguration.(type) {
	case *SharingMessageSpecifics_ChannelConfiguration_Fcm:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fcm); err != nil {
			return err
		}
	case *SharingMessageSpecifics_ChannelConfiguration_Server:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Server)
	case nil:
	default:
		return fmt.Errorf("SharingMessageSpecifics_ChannelConfiguration.ChannelConfiguration has unexpected type %T", x)
	}
	return nil
}

func _SharingMessageSpecifics_ChannelConfiguration_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SharingMessageSpecifics_ChannelConfiguration)
	switch tag {
	case 1: // channel_configuration.fcm
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration)
		err := b.DecodeMessage(msg)
		m.ChannelConfiguration = &SharingMessageSpecifics_ChannelConfiguration_Fcm{msg}
		return true, err
	case 2: // channel_configuration.server
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.ChannelConfiguration = &SharingMessageSpecifics_ChannelConfiguration_Server{x}
		return true, err
	default:
		return false, nil
	}
}

func _SharingMessageSpecifics_ChannelConfiguration_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SharingMessageSpecifics_ChannelConfiguration)
	// channel_configuration
	switch x := m.ChannelConfiguration.(type) {
	case *SharingMessageSpecifics_ChannelConfiguration_Fcm:
		s := proto.Size(x.Fcm)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *SharingMessageSpecifics_ChannelConfiguration_Server:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Server)))
		n += len(x.Server)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration struct {
	// FCM registration token of target device.
	Token *string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	// Time to live for a FCM message (in seconds) - if specified, the message
	// will expire based on the TTL.
	Ttl *int32 `protobuf:"varint,2,opt,name=ttl" json:"ttl,omitempty"`
	// Priority level of a FCM message. 5 = normal, 10 = high.
	Priority             *int32   `protobuf:"varint,3,opt,name=priority" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) Reset() {
	*m = SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration{}
}
func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) String() string {
	return proto.CompactTextString(m)
}
func (*SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) ProtoMessage() {}
func (*SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_sharing_message_specifics_394b77e57b137985, []int{0, 0, 0}
}
func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration.Unmarshal(m, b)
}
func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration.Marshal(b, m, deterministic)
}
func (dst *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration.Merge(dst, src)
}
func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) XXX_Size() int {
	return xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration.Size(m)
}
func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration proto.InternalMessageInfo

func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) GetTtl() int32 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

func (m *SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

// Used for the server to return fine grained commit errors back to the client.
type SharingMessageCommitError struct {
	ErrorCode            *SharingMessageCommitError_ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,enum=sync_pb.SharingMessageCommitError_ErrorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *SharingMessageCommitError) Reset()         { *m = SharingMessageCommitError{} }
func (m *SharingMessageCommitError) String() string { return proto.CompactTextString(m) }
func (*SharingMessageCommitError) ProtoMessage()    {}
func (*SharingMessageCommitError) Descriptor() ([]byte, []int) {
	return fileDescriptor_sharing_message_specifics_394b77e57b137985, []int{1}
}
func (m *SharingMessageCommitError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharingMessageCommitError.Unmarshal(m, b)
}
func (m *SharingMessageCommitError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharingMessageCommitError.Marshal(b, m, deterministic)
}
func (dst *SharingMessageCommitError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharingMessageCommitError.Merge(dst, src)
}
func (m *SharingMessageCommitError) XXX_Size() int {
	return xxx_messageInfo_SharingMessageCommitError.Size(m)
}
func (m *SharingMessageCommitError) XXX_DiscardUnknown() {
	xxx_messageInfo_SharingMessageCommitError.DiscardUnknown(m)
}

var xxx_messageInfo_SharingMessageCommitError proto.InternalMessageInfo

func (m *SharingMessageCommitError) GetErrorCode() SharingMessageCommitError_ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return SharingMessageCommitError_NONE
}

func init() {
	proto.RegisterType((*SharingMessageSpecifics)(nil), "sync_pb.SharingMessageSpecifics")
	proto.RegisterType((*SharingMessageSpecifics_ChannelConfiguration)(nil), "sync_pb.SharingMessageSpecifics.ChannelConfiguration")
	proto.RegisterType((*SharingMessageSpecifics_ChannelConfiguration_FCMChannelConfiguration)(nil), "sync_pb.SharingMessageSpecifics.ChannelConfiguration.FCMChannelConfiguration")
	proto.RegisterType((*SharingMessageCommitError)(nil), "sync_pb.SharingMessageCommitError")
	proto.RegisterEnum("sync_pb.SharingMessageCommitError_ErrorCode", SharingMessageCommitError_ErrorCode_name, SharingMessageCommitError_ErrorCode_value)
}

func init() {
	proto.RegisterFile("components/sync/protocol/sharing_message_specifics.proto", fileDescriptor_sharing_message_specifics_394b77e57b137985)
}

var fileDescriptor_sharing_message_specifics_394b77e57b137985 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xdf, 0x6a, 0xdb, 0x3c,
	0x14, 0x6f, 0xe2, 0xa6, 0x8d, 0x4f, 0xd2, 0xaf, 0xfa, 0xb4, 0x74, 0xcd, 0x0a, 0x83, 0x52, 0x36,
	0x08, 0x6c, 0xb8, 0x50, 0x18, 0xec, 0xd6, 0xb5, 0x95, 0xc5, 0x34, 0x96, 0x8b, 0x6c, 0x77, 0xdb,
	0xc5, 0x10, 0x9e, 0xa3, 0xa6, 0xde, 0x62, 0xcb, 0xc8, 0xee, 0xa0, 0xcf, 0xb0, 0x67, 0xd8, 0x4b,
	0xec, 0x39, 0xf6, 0x50, 0xc3, 0x76, 0xd2, 0x65, 0x90, 0xdc, 0xec, 0xc6, 0x9c, 0xf3, 0xf3, 0xef,
	0x8f, 0xce, 0x11, 0x82, 0xb7, 0xb1, 0x4c, 0x73, 0x99, 0x89, 0xac, 0x2c, 0xce, 0x8b, 0x87, 0x2c,
	0x3e, 0xcf, 0x95, 0x2c, 0x65, 0x2c, 0x17, 0xe7, 0xc5, 0x5d, 0xa4, 0x92, 0x6c, 0xce, 0x53, 0x51,
	0x14, 0xd1, 0x5c, 0xf0, 0x22, 0x17, 0x71, 0x72, 0x9b, 0xc4, 0x85, 0x51, 0x53, 0xf0, 0x7e, 0x45,
	0xe7, 0xf9, 0xe7, 0xb3, 0x5f, 0x1a, 0x1c, 0xfb, 0x0d, 0xd9, 0x6d, 0xb8, 0xfe, 0x8a, 0x8a, 0x9f,
	0x03, 0xac, 0xf4, 0xc9, 0x6c, 0xd8, 0x3a, 0x6d, 0x8d, 0x74, 0xa6, 0x2f, 0x11, 0x67, 0x86, 0xbf,
	0xc0, 0x51, 0x7c, 0x17, 0x65, 0x99, 0x58, 0xf0, 0x58, 0x66, 0xb7, 0xc9, 0xfc, 0x5e, 0x45, 0x65,
	0x22, 0xb3, 0x61, 0xfb, 0xb4, 0x35, 0xea, 0x5d, 0xbc, 0x31, 0x96, 0x19, 0xc6, 0x16, 0x7f, 0xc3,
	0x6a, 0xd4, 0xd6, 0xba, 0x98, 0x0d, 0xe2, 0x0d, 0x28, 0x1e, 0xc2, 0x7e, 0x1e, 0x3d, 0x2c, 0x64,
	0x34, 0x1b, 0x6a, 0xa7, 0xad, 0x51, 0x9f, 0xad, 0xda, 0x93, 0xef, 0x6d, 0x18, 0x6c, 0x32, 0xc2,
	0x11, 0x68, 0xb7, 0x71, 0x5a, 0x1f, 0xbb, 0x77, 0xe1, 0xfe, 0xd3, 0x61, 0x8c, 0xb1, 0xe5, 0x6e,
	0xc2, 0x27, 0x3b, 0xac, 0xf2, 0xc6, 0x43, 0xd8, 0x2b, 0x84, 0xfa, 0x26, 0x54, 0x3d, 0x72, 0x7f,
	0xb2, 0xc3, 0x96, 0xfd, 0xc9, 0x27, 0x38, 0xde, 0xa2, 0xc5, 0x03, 0xe8, 0x94, 0xf2, 0xab, 0xc8,
	0x96, 0x0b, 0x6d, 0x1a, 0x8c, 0x40, 0x2b, 0xcb, 0x45, 0xed, 0xd3, 0x61, 0x55, 0x89, 0x4f, 0xa0,
	0x9b, 0xab, 0x44, 0xaa, 0xa4, 0x7c, 0xa8, 0x67, 0xee, 0xb0, 0xc7, 0xfe, 0xf2, 0x78, 0xcb, 0xea,
	0xcf, 0x7e, 0x68, 0xf0, 0xec, 0xef, 0x09, 0x2d, 0x99, 0xa6, 0x49, 0x49, 0x94, 0x92, 0x0a, 0x5f,
	0x01, 0x88, 0xaa, 0xe0, 0xb1, 0x9c, 0x89, 0x3a, 0xff, 0xbf, 0x8b, 0xd7, 0x5b, 0x36, 0xb3, 0xa6,
	0x33, 0xea, 0xaf, 0x25, 0x67, 0x82, 0xe9, 0x62, 0x55, 0x9e, 0xfd, 0x6c, 0x83, 0xfe, 0xf8, 0x03,
	0x77, 0x61, 0x97, 0x7a, 0x94, 0xa0, 0x1d, 0x3c, 0x00, 0xe4, 0xd0, 0x1b, 0x73, 0xea, 0xd8, 0xdc,
	0x64, 0xef, 0x42, 0x97, 0xd0, 0x00, 0xb5, 0xf0, 0x01, 0xe8, 0xd4, 0x0b, 0xf8, 0xd8, 0x0b, 0xa9,
	0x8d, 0xda, 0xb8, 0x0f, 0x5d, 0x87, 0x06, 0x84, 0x51, 0x73, 0x8a, 0x34, 0x7c, 0x08, 0xbd, 0x90,
	0x9a, 0x37, 0xa6, 0x33, 0x35, 0x2f, 0xa7, 0x04, 0xed, 0xe2, 0xa7, 0x80, 0x19, 0xf1, 0xbd, 0x90,
	0x59, 0x84, 0x93, 0x0f, 0x13, 0x33, 0xf4, 0x03, 0x62, 0xa3, 0x0e, 0x7e, 0x02, 0x87, 0x21, 0x35,
	0xc3, 0x60, 0x42, 0x68, 0xe0, 0x58, 0x66, 0x05, 0xee, 0xe1, 0x23, 0xf8, 0xff, 0x9a, 0x30, 0xd7,
	0xf1, 0x7d, 0xc7, 0xa3, 0xdc, 0x26, 0xd4, 0x21, 0x36, 0xda, 0xaf, 0xb8, 0xfe, 0x47, 0x6a, 0xf1,
	0x20, 0x64, 0x94, 0xd8, 0xdc, 0x1b, 0x8f, 0x51, 0xb7, 0x32, 0xae, 0x41, 0x4a, 0x82, 0xf7, 0x1e,
	0xbb, 0xe2, 0x84, 0x31, 0x8f, 0x21, 0x1d, 0x8f, 0xe0, 0x85, 0x4d, 0xae, 0x19, 0xa9, 0x3d, 0x79,
	0x4d, 0xf1, 0x09, 0xbb, 0x21, 0x8c, 0x7b, 0x8c, 0x57, 0x81, 0x4b, 0x26, 0x60, 0x04, 0xfd, 0xc6,
	0xd6, 0x71, 0x89, 0x17, 0x06, 0xa8, 0x57, 0xe5, 0xaf, 0x0b, 0x1a, 0x62, 0xff, 0x31, 0x7f, 0x4d,
	0x7d, 0x70, 0xf9, 0x0a, 0x5e, 0x4a, 0x35, 0x37, 0xe2, 0x3b, 0x25, 0xd3, 0xe4, 0x3e, 0x35, 0xfe,
	0x3c, 0xe0, 0xfa, 0x1a, 0x8c, 0xd5, 0x03, 0x9e, 0x68, 0xd7, 0xad, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x2b, 0x18, 0xd0, 0x2b, 0xdf, 0x03, 0x00, 0x00,
}
