// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/sync_invalidations_payload.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The payload coming from the server for all invalidated data types.
type SyncInvalidationsPayload struct {
	// This field contains information about each data type which needs to be
	// updated.
	DataTypeInvalidations []*SyncInvalidationsPayload_DataTypeInvalidation `protobuf:"bytes,1,rep,name=data_type_invalidations,json=dataTypeInvalidations" json:"data_type_invalidations,omitempty"`
	// Opaque field, which has to be provided as part of resulting GetUpdates
	// back to the server.
	Hint                 []byte   `protobuf:"bytes,2,opt,name=hint" json:"hint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInvalidationsPayload) Reset()         { *m = SyncInvalidationsPayload{} }
func (m *SyncInvalidationsPayload) String() string { return proto.CompactTextString(m) }
func (*SyncInvalidationsPayload) ProtoMessage()    {}
func (*SyncInvalidationsPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_sync_invalidations_payload_f114eb8f1ee0596e, []int{0}
}
func (m *SyncInvalidationsPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInvalidationsPayload.Unmarshal(m, b)
}
func (m *SyncInvalidationsPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInvalidationsPayload.Marshal(b, m, deterministic)
}
func (dst *SyncInvalidationsPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInvalidationsPayload.Merge(dst, src)
}
func (m *SyncInvalidationsPayload) XXX_Size() int {
	return xxx_messageInfo_SyncInvalidationsPayload.Size(m)
}
func (m *SyncInvalidationsPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInvalidationsPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInvalidationsPayload proto.InternalMessageInfo

func (m *SyncInvalidationsPayload) GetDataTypeInvalidations() []*SyncInvalidationsPayload_DataTypeInvalidation {
	if m != nil {
		return m.DataTypeInvalidations
	}
	return nil
}

func (m *SyncInvalidationsPayload) GetHint() []byte {
	if m != nil {
		return m.Hint
	}
	return nil
}

type SyncInvalidationsPayload_DataTypeInvalidation struct {
	// The legitimate values of this field correspond to the protobuf field
	// numbers of all EntitySpecifics fields supported by the server (see
	// components/sync/protocol/sync.proto).
	DataTypeId           *int32   `protobuf:"varint,1,opt,name=data_type_id,json=dataTypeId" json:"data_type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncInvalidationsPayload_DataTypeInvalidation) Reset() {
	*m = SyncInvalidationsPayload_DataTypeInvalidation{}
}
func (m *SyncInvalidationsPayload_DataTypeInvalidation) String() string {
	return proto.CompactTextString(m)
}
func (*SyncInvalidationsPayload_DataTypeInvalidation) ProtoMessage() {}
func (*SyncInvalidationsPayload_DataTypeInvalidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_sync_invalidations_payload_f114eb8f1ee0596e, []int{0, 0}
}
func (m *SyncInvalidationsPayload_DataTypeInvalidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncInvalidationsPayload_DataTypeInvalidation.Unmarshal(m, b)
}
func (m *SyncInvalidationsPayload_DataTypeInvalidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncInvalidationsPayload_DataTypeInvalidation.Marshal(b, m, deterministic)
}
func (dst *SyncInvalidationsPayload_DataTypeInvalidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncInvalidationsPayload_DataTypeInvalidation.Merge(dst, src)
}
func (m *SyncInvalidationsPayload_DataTypeInvalidation) XXX_Size() int {
	return xxx_messageInfo_SyncInvalidationsPayload_DataTypeInvalidation.Size(m)
}
func (m *SyncInvalidationsPayload_DataTypeInvalidation) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncInvalidationsPayload_DataTypeInvalidation.DiscardUnknown(m)
}

var xxx_messageInfo_SyncInvalidationsPayload_DataTypeInvalidation proto.InternalMessageInfo

func (m *SyncInvalidationsPayload_DataTypeInvalidation) GetDataTypeId() int32 {
	if m != nil && m.DataTypeId != nil {
		return *m.DataTypeId
	}
	return 0
}

func init() {
	proto.RegisterType((*SyncInvalidationsPayload)(nil), "sync_pb.SyncInvalidationsPayload")
	proto.RegisterType((*SyncInvalidationsPayload_DataTypeInvalidation)(nil), "sync_pb.SyncInvalidationsPayload.DataTypeInvalidation")
}

func init() {
	proto.RegisterFile("components/sync/protocol/sync_invalidations_payload.proto", fileDescriptor_sync_invalidations_payload_f114eb8f1ee0596e)
}

var fileDescriptor_sync_invalidations_payload_f114eb8f1ee0596e = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcb, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0x89, 0x47, 0x11, 0xc6, 0xb3, 0x0a, 0x8a, 0xc1, 0x55, 0x10, 0x84, 0x82, 0x90, 0x82,
	0x0b, 0xd1, 0xad, 0xb8, 0xd0, 0x5d, 0xa9, 0xee, 0xcb, 0x98, 0x14, 0x1b, 0x68, 0x67, 0x42, 0x13,
	0x85, 0xbc, 0xa9, 0x8f, 0x23, 0xc4, 0x5b, 0x85, 0x9e, 0xdd, 0x5c, 0x3e, 0x3e, 0x7e, 0x7e, 0xb8,
	0xb5, 0x3c, 0x05, 0xa6, 0x9e, 0x52, 0xac, 0x63, 0x26, 0x5b, 0x87, 0x99, 0x13, 0x5b, 0x1e, 0xcb,
	0xd6, 0x79, 0x7a, 0xc7, 0xd1, 0x3b, 0x4c, 0x9e, 0x29, 0x76, 0x01, 0xf3, 0xc8, 0xe8, 0x4c, 0x61,
	0xe4, 0x61, 0x21, 0xc2, 0xcb, 0xf9, 0x87, 0x00, 0xf5, 0x94, 0xc9, 0x3e, 0x2e, 0xe1, 0xe6, 0x8b,
	0x95, 0x04, 0xa7, 0x0e, 0x13, 0x76, 0x29, 0x87, 0xfe, 0xbf, 0x4e, 0x09, 0xbd, 0xa9, 0x8e, 0xae,
	0xae, 0xcd, 0xb7, 0xc7, 0xec, 0x72, 0x98, 0x7b, 0x4c, 0xf8, 0x9c, 0x43, 0xbf, 0x7c, 0xb6, 0x27,
	0x6e, 0xe5, 0x1a, 0xa5, 0x84, 0xfd, 0xc1, 0x53, 0x52, 0x7b, 0x5a, 0x54, 0xdb, 0xb6, 0xcc, 0x67,
	0x37, 0x70, 0xbc, 0xa6, 0x90, 0x1a, 0xb6, 0x8b, 0x6c, 0x4e, 0x09, 0x2d, 0xaa, 0x83, 0x16, 0x7e,
	0xc5, 0xee, 0xee, 0x12, 0x2e, 0x78, 0x7e, 0x35, 0x76, 0x98, 0x79, 0xf2, 0x6f, 0x93, 0xf9, 0x6b,
	0xab, 0xa4, 0x36, 0x3f, 0x6d, 0x3d, 0x6c, 0x1a, 0xf1, 0x19, 0x00, 0x00, 0xff, 0xff, 0x55, 0x8f,
	0x46, 0x70, 0x4c, 0x01, 0x00, 0x00,
}
