// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/synced_notification_specifics.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// This message is kept around for backwards compatibility sake.
type SyncedNotificationSpecifics struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncedNotificationSpecifics) Reset()         { *m = SyncedNotificationSpecifics{} }
func (m *SyncedNotificationSpecifics) String() string { return proto.CompactTextString(m) }
func (*SyncedNotificationSpecifics) ProtoMessage()    {}
func (*SyncedNotificationSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_synced_notification_specifics_e86c94ca752495f4, []int{0}
}
func (m *SyncedNotificationSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncedNotificationSpecifics.Unmarshal(m, b)
}
func (m *SyncedNotificationSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncedNotificationSpecifics.Marshal(b, m, deterministic)
}
func (dst *SyncedNotificationSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncedNotificationSpecifics.Merge(dst, src)
}
func (m *SyncedNotificationSpecifics) XXX_Size() int {
	return xxx_messageInfo_SyncedNotificationSpecifics.Size(m)
}
func (m *SyncedNotificationSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncedNotificationSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_SyncedNotificationSpecifics proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SyncedNotificationSpecifics)(nil), "sync_pb.SyncedNotificationSpecifics")
}

func init() {
	proto.RegisterFile("components/sync/protocol/synced_notification_specifics.proto", fileDescriptor_synced_notification_specifics_e86c94ca752495f4)
}

var fileDescriptor_synced_notification_specifics_e86c94ca752495f4 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x49, 0xce, 0xcf, 0x2d,
	0xc8, 0xcf, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2f, 0xae, 0xcc, 0x4b, 0xd6, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0x01, 0xf3, 0x52, 0x53, 0xe2, 0xf3, 0xf2, 0x4b, 0x32, 0xd3, 0x32, 0x93,
	0x13, 0x4b, 0x32, 0xf3, 0xf3, 0xe2, 0x8b, 0x0b, 0x52, 0x93, 0x41, 0xbc, 0x62, 0x3d, 0xb0, 0x32,
	0x21, 0x76, 0x90, 0xa2, 0xf8, 0x82, 0x24, 0x25, 0x59, 0x2e, 0xe9, 0x60, 0xb0, 0x7a, 0x3f, 0x24,
	0xe5, 0xc1, 0x30, 0xd5, 0x4e, 0xda, 0x5c, 0xaa, 0xf9, 0x45, 0xe9, 0x7a, 0xc9, 0x19, 0x45, 0xf9,
	0xb9, 0x99, 0xa5, 0xb9, 0x7a, 0x08, 0x4b, 0xf5, 0x40, 0x26, 0xe8, 0xc1, 0x2c, 0xf5, 0x60, 0x0e,
	0x60, 0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0x79, 0xdf, 0x5f, 0x70, 0x93, 0x00, 0x00, 0x00,
}
