// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/sync_enums.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// These events are sent by the DebugInfo class for singleton events.
type SyncEnums_SingletonDebugEventType int32

const (
	// Connection status change. Note this gets generated even during a
	// successful connection.
	SyncEnums_CONNECTION_STATUS_CHANGE SyncEnums_SingletonDebugEventType = 1
	// Client received an updated token.
	SyncEnums_UPDATED_TOKEN SyncEnums_SingletonDebugEventType = 2
	// Cryptographer needs passphrase.
	SyncEnums_PASSPHRASE_REQUIRED SyncEnums_SingletonDebugEventType = 3
	// Passphrase was accepted by cryptographer.
	SyncEnums_PASSPHRASE_ACCEPTED SyncEnums_SingletonDebugEventType = 4
	// Sync Initialization is complete.
	SyncEnums_INITIALIZATION_COMPLETE SyncEnums_SingletonDebugEventType = 5
	// Server sent stop syncing permanently. This event should never be seen by
	// the server in the absence of bugs.
	SyncEnums_STOP_SYNCING_PERMANENTLY SyncEnums_SingletonDebugEventType = 6
	// Client has finished encrypting all data.
	// DEPRECATED_ENCRYPTION_COMPLETE = 7;
	// Client received an actionable error.
	SyncEnums_ACTIONABLE_ERROR SyncEnums_SingletonDebugEventType = 8
	// Set of encrypted types has changed.
	SyncEnums_ENCRYPTED_TYPES_CHANGED SyncEnums_SingletonDebugEventType = 9
	// The encryption passphrase state changed.
	SyncEnums_PASSPHRASE_TYPE_CHANGED SyncEnums_SingletonDebugEventType = 10
	// A new keystore encryption token was persisted.
	SyncEnums_KEYSTORE_TOKEN_UPDATED SyncEnums_SingletonDebugEventType = 11
	// The datatype manager has finished an at least partially successful
	// configuration and is once again syncing with the server.
	SyncEnums_CONFIGURE_COMPLETE SyncEnums_SingletonDebugEventType = 12
	// A new cryptographer bootstrap token was generated.
	SyncEnums_BOOTSTRAP_TOKEN_UPDATED SyncEnums_SingletonDebugEventType = 13
	// Cryptographer needs trusted vault decryption keys.
	SyncEnums_TRUSTED_VAULT_KEY_REQUIRED SyncEnums_SingletonDebugEventType = 14
	// Cryptographer no longer needs trusted vault decryption keys.
	SyncEnums_TRUSTED_VAULT_KEY_ACCEPTED SyncEnums_SingletonDebugEventType = 15
)

var SyncEnums_SingletonDebugEventType_name = map[int32]string{
	1:  "CONNECTION_STATUS_CHANGE",
	2:  "UPDATED_TOKEN",
	3:  "PASSPHRASE_REQUIRED",
	4:  "PASSPHRASE_ACCEPTED",
	5:  "INITIALIZATION_COMPLETE",
	6:  "STOP_SYNCING_PERMANENTLY",
	8:  "ACTIONABLE_ERROR",
	9:  "ENCRYPTED_TYPES_CHANGED",
	10: "PASSPHRASE_TYPE_CHANGED",
	11: "KEYSTORE_TOKEN_UPDATED",
	12: "CONFIGURE_COMPLETE",
	13: "BOOTSTRAP_TOKEN_UPDATED",
	14: "TRUSTED_VAULT_KEY_REQUIRED",
	15: "TRUSTED_VAULT_KEY_ACCEPTED",
}
var SyncEnums_SingletonDebugEventType_value = map[string]int32{
	"CONNECTION_STATUS_CHANGE":   1,
	"UPDATED_TOKEN":              2,
	"PASSPHRASE_REQUIRED":        3,
	"PASSPHRASE_ACCEPTED":        4,
	"INITIALIZATION_COMPLETE":    5,
	"STOP_SYNCING_PERMANENTLY":   6,
	"ACTIONABLE_ERROR":           8,
	"ENCRYPTED_TYPES_CHANGED":    9,
	"PASSPHRASE_TYPE_CHANGED":    10,
	"KEYSTORE_TOKEN_UPDATED":     11,
	"CONFIGURE_COMPLETE":         12,
	"BOOTSTRAP_TOKEN_UPDATED":    13,
	"TRUSTED_VAULT_KEY_REQUIRED": 14,
	"TRUSTED_VAULT_KEY_ACCEPTED": 15,
}

func (x SyncEnums_SingletonDebugEventType) Enum() *SyncEnums_SingletonDebugEventType {
	p := new(SyncEnums_SingletonDebugEventType)
	*p = x
	return p
}
func (x SyncEnums_SingletonDebugEventType) String() string {
	return proto.EnumName(SyncEnums_SingletonDebugEventType_name, int32(x))
}
func (x *SyncEnums_SingletonDebugEventType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEnums_SingletonDebugEventType_value, data, "SyncEnums_SingletonDebugEventType")
	if err != nil {
		return err
	}
	*x = SyncEnums_SingletonDebugEventType(value)
	return nil
}
func (SyncEnums_SingletonDebugEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0, 0}
}

// Types of transitions between pages.
type SyncEnums_PageTransition int32

const (
	SyncEnums_LINK              SyncEnums_PageTransition = 0
	SyncEnums_TYPED             SyncEnums_PageTransition = 1
	SyncEnums_AUTO_BOOKMARK     SyncEnums_PageTransition = 2
	SyncEnums_AUTO_SUBFRAME     SyncEnums_PageTransition = 3
	SyncEnums_MANUAL_SUBFRAME   SyncEnums_PageTransition = 4
	SyncEnums_GENERATED         SyncEnums_PageTransition = 5
	SyncEnums_AUTO_TOPLEVEL     SyncEnums_PageTransition = 6
	SyncEnums_FORM_SUBMIT       SyncEnums_PageTransition = 7
	SyncEnums_RELOAD            SyncEnums_PageTransition = 8
	SyncEnums_KEYWORD           SyncEnums_PageTransition = 9
	SyncEnums_KEYWORD_GENERATED SyncEnums_PageTransition = 10
)

var SyncEnums_PageTransition_name = map[int32]string{
	0:  "LINK",
	1:  "TYPED",
	2:  "AUTO_BOOKMARK",
	3:  "AUTO_SUBFRAME",
	4:  "MANUAL_SUBFRAME",
	5:  "GENERATED",
	6:  "AUTO_TOPLEVEL",
	7:  "FORM_SUBMIT",
	8:  "RELOAD",
	9:  "KEYWORD",
	10: "KEYWORD_GENERATED",
}
var SyncEnums_PageTransition_value = map[string]int32{
	"LINK":              0,
	"TYPED":             1,
	"AUTO_BOOKMARK":     2,
	"AUTO_SUBFRAME":     3,
	"MANUAL_SUBFRAME":   4,
	"GENERATED":         5,
	"AUTO_TOPLEVEL":     6,
	"FORM_SUBMIT":       7,
	"RELOAD":            8,
	"KEYWORD":           9,
	"KEYWORD_GENERATED": 10,
}

func (x SyncEnums_PageTransition) Enum() *SyncEnums_PageTransition {
	p := new(SyncEnums_PageTransition)
	*p = x
	return p
}
func (x SyncEnums_PageTransition) String() string {
	return proto.EnumName(SyncEnums_PageTransition_name, int32(x))
}
func (x *SyncEnums_PageTransition) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEnums_PageTransition_value, data, "SyncEnums_PageTransition")
	if err != nil {
		return err
	}
	*x = SyncEnums_PageTransition(value)
	return nil
}
func (SyncEnums_PageTransition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0, 1}
}

// Types of redirects that triggered a transition.
type SyncEnums_PageTransitionRedirectType int32

const (
	SyncEnums_CLIENT_REDIRECT SyncEnums_PageTransitionRedirectType = 1
	SyncEnums_SERVER_REDIRECT SyncEnums_PageTransitionRedirectType = 2
)

var SyncEnums_PageTransitionRedirectType_name = map[int32]string{
	1: "CLIENT_REDIRECT",
	2: "SERVER_REDIRECT",
}
var SyncEnums_PageTransitionRedirectType_value = map[string]int32{
	"CLIENT_REDIRECT": 1,
	"SERVER_REDIRECT": 2,
}

func (x SyncEnums_PageTransitionRedirectType) Enum() *SyncEnums_PageTransitionRedirectType {
	p := new(SyncEnums_PageTransitionRedirectType)
	*p = x
	return p
}
func (x SyncEnums_PageTransitionRedirectType) String() string {
	return proto.EnumName(SyncEnums_PageTransitionRedirectType_name, int32(x))
}
func (x *SyncEnums_PageTransitionRedirectType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEnums_PageTransitionRedirectType_value, data, "SyncEnums_PageTransitionRedirectType")
	if err != nil {
		return err
	}
	*x = SyncEnums_PageTransitionRedirectType(value)
	return nil
}
func (SyncEnums_PageTransitionRedirectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0, 2}
}

type SyncEnums_ErrorType int32

const (
	SyncEnums_SUCCESS SyncEnums_ErrorType = 0
	// DEPRECATED_ACCESS_DENIED = 1;
	// Returned when the server and client disagree on the store birthday. This
	// should be interpreted as all local sync metadata requiring cleanup,
	// obviously including the locally-cached store birthday.
	SyncEnums_NOT_MY_BIRTHDAY SyncEnums_ErrorType = 2
	// Returned when the store has exceeded the allowed bandwidth utilization.
	SyncEnums_THROTTLED SyncEnums_ErrorType = 3
	// DEPRECATED_AUTH_EXPIRED = 4;
	// DEPRECATED_USER_NOT_ACTIVATED = 5;
	// DEPRECATED_AUTH_INVALID = 6;
	// A clear of the user data is pending (e.g. initiated by privacy request).
	// The client should come back later.
	SyncEnums_CLEAR_PENDING SyncEnums_ErrorType = 7
	// A transient error occurred (e.g. a backend timeout). The client should
	// try again later.
	SyncEnums_TRANSIENT_ERROR SyncEnums_ErrorType = 8
	// A server-side migration has taken place for one or more data types. The
	// client should clear the cache for these data types only and then re-sync
	// with a server.
	SyncEnums_MIGRATION_DONE SyncEnums_ErrorType = 9
	// An administrator disabled sync for this domain.
	SyncEnums_DISABLED_BY_ADMIN SyncEnums_ErrorType = 10
	// Deprecated in M50.
	// DEPRECATED_USER_ROLLBACK = 11;
	// Returned when the client wants to update several data types, but some of
	// them failed (e.g. throttled).
	SyncEnums_PARTIAL_FAILURE SyncEnums_ErrorType = 12
	// Returned when the server detects that this client's sync metadata is
	// obsolete. The client should reset local sync metadata and restart
	// syncing.
	SyncEnums_CLIENT_DATA_OBSOLETE SyncEnums_ErrorType = 13
	// Returned when the server detects that the encryption state (Nigori,
	// keystore keys) has been reset/overridden, which means the local
	// Nigori-related state is obsolete and should be cleared.
	// Introduced in M84.
	SyncEnums_ENCRYPTION_OBSOLETE SyncEnums_ErrorType = 14
	// Unknown value. This should never be explicitly used; it is the default
	// value when an out-of-date client parses a value it doesn't recognize.
	SyncEnums_UNKNOWN SyncEnums_ErrorType = 100
)

var SyncEnums_ErrorType_name = map[int32]string{
	0:   "SUCCESS",
	2:   "NOT_MY_BIRTHDAY",
	3:   "THROTTLED",
	7:   "CLEAR_PENDING",
	8:   "TRANSIENT_ERROR",
	9:   "MIGRATION_DONE",
	10:  "DISABLED_BY_ADMIN",
	12:  "PARTIAL_FAILURE",
	13:  "CLIENT_DATA_OBSOLETE",
	14:  "ENCRYPTION_OBSOLETE",
	100: "UNKNOWN",
}
var SyncEnums_ErrorType_value = map[string]int32{
	"SUCCESS":              0,
	"NOT_MY_BIRTHDAY":      2,
	"THROTTLED":            3,
	"CLEAR_PENDING":        7,
	"TRANSIENT_ERROR":      8,
	"MIGRATION_DONE":       9,
	"DISABLED_BY_ADMIN":    10,
	"PARTIAL_FAILURE":      12,
	"CLIENT_DATA_OBSOLETE": 13,
	"ENCRYPTION_OBSOLETE":  14,
	"UNKNOWN":              100,
}

func (x SyncEnums_ErrorType) Enum() *SyncEnums_ErrorType {
	p := new(SyncEnums_ErrorType)
	*p = x
	return p
}
func (x SyncEnums_ErrorType) String() string {
	return proto.EnumName(SyncEnums_ErrorType_name, int32(x))
}
func (x *SyncEnums_ErrorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEnums_ErrorType_value, data, "SyncEnums_ErrorType")
	if err != nil {
		return err
	}
	*x = SyncEnums_ErrorType(value)
	return nil
}
func (SyncEnums_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0, 3}
}

type SyncEnums_Action int32

const (
	SyncEnums_UPGRADE_CLIENT SyncEnums_Action = 0
	// DEPRECATED_CLEAR_USER_DATA_AND_RESYNC = 1;
	// DEPRECATED_ENABLE_SYNC_ON_ACCOUNT = 2;
	// DEPRECATED_STOP_AND_RESTART_SYNC = 3;
	// DEPRECATED_DISABLE_SYNC_ON_CLIENT = 4;
	SyncEnums_UNKNOWN_ACTION SyncEnums_Action = 5
)

var SyncEnums_Action_name = map[int32]string{
	0: "UPGRADE_CLIENT",
	5: "UNKNOWN_ACTION",
}
var SyncEnums_Action_value = map[string]int32{
	"UPGRADE_CLIENT": 0,
	"UNKNOWN_ACTION": 5,
}

func (x SyncEnums_Action) Enum() *SyncEnums_Action {
	p := new(SyncEnums_Action)
	*p = x
	return p
}
func (x SyncEnums_Action) String() string {
	return proto.EnumName(SyncEnums_Action_name, int32(x))
}
func (x *SyncEnums_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEnums_Action_value, data, "SyncEnums_Action")
	if err != nil {
		return err
	}
	*x = SyncEnums_Action(value)
	return nil
}
func (SyncEnums_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0, 4}
}

// Please keep in sync with chrome/android/java/.../ForeignSessionHelper.java
type SyncEnums_DeviceType int32

const (
	SyncEnums_TYPE_UNSET  SyncEnums_DeviceType = 0
	SyncEnums_TYPE_WIN    SyncEnums_DeviceType = 1
	SyncEnums_TYPE_MAC    SyncEnums_DeviceType = 2
	SyncEnums_TYPE_LINUX  SyncEnums_DeviceType = 3
	SyncEnums_TYPE_CROS   SyncEnums_DeviceType = 4
	SyncEnums_TYPE_OTHER  SyncEnums_DeviceType = 5
	SyncEnums_TYPE_PHONE  SyncEnums_DeviceType = 6
	SyncEnums_TYPE_TABLET SyncEnums_DeviceType = 7
)

var SyncEnums_DeviceType_name = map[int32]string{
	0: "TYPE_UNSET",
	1: "TYPE_WIN",
	2: "TYPE_MAC",
	3: "TYPE_LINUX",
	4: "TYPE_CROS",
	5: "TYPE_OTHER",
	6: "TYPE_PHONE",
	7: "TYPE_TABLET",
}
var SyncEnums_DeviceType_value = map[string]int32{
	"TYPE_UNSET":  0,
	"TYPE_WIN":    1,
	"TYPE_MAC":    2,
	"TYPE_LINUX":  3,
	"TYPE_CROS":   4,
	"TYPE_OTHER":  5,
	"TYPE_PHONE":  6,
	"TYPE_TABLET": 7,
}

func (x SyncEnums_DeviceType) Enum() *SyncEnums_DeviceType {
	p := new(SyncEnums_DeviceType)
	*p = x
	return p
}
func (x SyncEnums_DeviceType) String() string {
	return proto.EnumName(SyncEnums_DeviceType_name, int32(x))
}
func (x *SyncEnums_DeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEnums_DeviceType_value, data, "SyncEnums_DeviceType")
	if err != nil {
		return err
	}
	*x = SyncEnums_DeviceType(value)
	return nil
}
func (SyncEnums_DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0, 5}
}

// This is the successor to GetUpdatesSource.  It merges the "normal mode"
// values (LOCAL, NOTIFICATION and DATATYPE_REFRESH), which were never really
// mutually exclusive to being with, into the GU_TRIGGER value.  It also
// drops support for some old values that are not supported by newer clients.
//
// Mind the gaps: Some values are intentionally unused because we want to
// keep the values in sync with GetUpdatesSource as much as possible.  Please
// don't add any values < 12 unless there's a good reason for it.
//
// Introduced in M28.
type SyncEnums_GetUpdatesOrigin int32

const (
	SyncEnums_UNKNOWN_ORIGIN           SyncEnums_GetUpdatesOrigin = 0
	SyncEnums_PERIODIC                 SyncEnums_GetUpdatesOrigin = 4
	SyncEnums_NEWLY_SUPPORTED_DATATYPE SyncEnums_GetUpdatesOrigin = 7
	// because it's syncing all datatypes, and
	// support for a new datatype was recently
	// released via a software auto-update.
	SyncEnums_MIGRATION SyncEnums_GetUpdatesOrigin = 8
	// MIGRATION_DONE error previously returned by the
	// server necessitated resynchronization.
	SyncEnums_NEW_CLIENT SyncEnums_GetUpdatesOrigin = 9
	// user enabled sync for the first time.  Not to be
	// confused with FIRST_UPDATE.
	SyncEnums_RECONFIGURATION SyncEnums_GetUpdatesOrigin = 10
	// user opted to sync a different set of datatypes.
	SyncEnums_GU_TRIGGER SyncEnums_GetUpdatesOrigin = 12
	// reasons for requesting an update.  See the per-type
	// GetUpdateTriggers message for more details.
	SyncEnums_RETRY SyncEnums_GetUpdatesOrigin = 13
	// replication delay, missing hints, etc.
	SyncEnums_PROGRAMMATIC SyncEnums_GetUpdatesOrigin = 14
)

var SyncEnums_GetUpdatesOrigin_name = map[int32]string{
	0:  "UNKNOWN_ORIGIN",
	4:  "PERIODIC",
	7:  "NEWLY_SUPPORTED_DATATYPE",
	8:  "MIGRATION",
	9:  "NEW_CLIENT",
	10: "RECONFIGURATION",
	12: "GU_TRIGGER",
	13: "RETRY",
	14: "PROGRAMMATIC",
}
var SyncEnums_GetUpdatesOrigin_value = map[string]int32{
	"UNKNOWN_ORIGIN":           0,
	"PERIODIC":                 4,
	"NEWLY_SUPPORTED_DATATYPE": 7,
	"MIGRATION":                8,
	"NEW_CLIENT":               9,
	"RECONFIGURATION":          10,
	"GU_TRIGGER":               12,
	"RETRY":                    13,
	"PROGRAMMATIC":             14,
}

func (x SyncEnums_GetUpdatesOrigin) Enum() *SyncEnums_GetUpdatesOrigin {
	p := new(SyncEnums_GetUpdatesOrigin)
	*p = x
	return p
}
func (x SyncEnums_GetUpdatesOrigin) String() string {
	return proto.EnumName(SyncEnums_GetUpdatesOrigin_name, int32(x))
}
func (x *SyncEnums_GetUpdatesOrigin) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SyncEnums_GetUpdatesOrigin_value, data, "SyncEnums_GetUpdatesOrigin")
	if err != nil {
		return err
	}
	*x = SyncEnums_GetUpdatesOrigin(value)
	return nil
}
func (SyncEnums_GetUpdatesOrigin) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0, 6}
}

type SyncEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncEnums) Reset()         { *m = SyncEnums{} }
func (m *SyncEnums) String() string { return proto.CompactTextString(m) }
func (*SyncEnums) ProtoMessage()    {}
func (*SyncEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_sync_enums_277d4eab30debae2, []int{0}
}
func (m *SyncEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncEnums.Unmarshal(m, b)
}
func (m *SyncEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncEnums.Marshal(b, m, deterministic)
}
func (dst *SyncEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncEnums.Merge(dst, src)
}
func (m *SyncEnums) XXX_Size() int {
	return xxx_messageInfo_SyncEnums.Size(m)
}
func (m *SyncEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncEnums.DiscardUnknown(m)
}

var xxx_messageInfo_SyncEnums proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SyncEnums)(nil), "sync_pb.SyncEnums")
	proto.RegisterEnum("sync_pb.SyncEnums_SingletonDebugEventType", SyncEnums_SingletonDebugEventType_name, SyncEnums_SingletonDebugEventType_value)
	proto.RegisterEnum("sync_pb.SyncEnums_PageTransition", SyncEnums_PageTransition_name, SyncEnums_PageTransition_value)
	proto.RegisterEnum("sync_pb.SyncEnums_PageTransitionRedirectType", SyncEnums_PageTransitionRedirectType_name, SyncEnums_PageTransitionRedirectType_value)
	proto.RegisterEnum("sync_pb.SyncEnums_ErrorType", SyncEnums_ErrorType_name, SyncEnums_ErrorType_value)
	proto.RegisterEnum("sync_pb.SyncEnums_Action", SyncEnums_Action_name, SyncEnums_Action_value)
	proto.RegisterEnum("sync_pb.SyncEnums_DeviceType", SyncEnums_DeviceType_name, SyncEnums_DeviceType_value)
	proto.RegisterEnum("sync_pb.SyncEnums_GetUpdatesOrigin", SyncEnums_GetUpdatesOrigin_name, SyncEnums_GetUpdatesOrigin_value)
}

func init() {
	proto.RegisterFile("components/sync/protocol/sync_enums.proto", fileDescriptor_sync_enums_277d4eab30debae2)
}

var fileDescriptor_sync_enums_277d4eab30debae2 = []byte{
	// 855 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdd, 0x4e, 0x23, 0x37,
	0x14, 0x26, 0xfc, 0x85, 0x1c, 0x48, 0x30, 0x66, 0xbb, 0xac, 0x68, 0xd5, 0x8b, 0x48, 0xbd, 0xa8,
	0x2a, 0xb1, 0x7d, 0x05, 0x67, 0xe6, 0x30, 0xb1, 0x32, 0x63, 0xbb, 0xc7, 0x1e, 0xe8, 0xf4, 0xc6,
	0x62, 0xc3, 0x88, 0x46, 0x5a, 0x26, 0x28, 0x84, 0x95, 0x78, 0x83, 0x5e, 0xf5, 0xba, 0xef, 0xd1,
	0x47, 0xe8, 0xab, 0xf4, 0x41, 0x2a, 0x7b, 0x60, 0xb2, 0x5d, 0xed, 0xe5, 0xf9, 0xf5, 0x77, 0xbe,
	0xf3, 0x1d, 0xc3, 0x8f, 0xf3, 0xe5, 0xfd, 0xc3, 0xb2, 0xa9, 0x9b, 0xf5, 0xe3, 0xfb, 0xc7, 0xe7,
	0x66, 0xfe, 0xfe, 0x61, 0xb5, 0x5c, 0x2f, 0xe7, 0xcb, 0x8f, 0xd1, 0xf2, 0x75, 0xf3, 0x74, 0xff,
	0x78, 0x11, 0x7d, 0xbc, 0x1f, 0x3d, 0x0f, 0x1f, 0xc6, 0x7f, 0x02, 0x0c, 0xec, 0x73, 0x33, 0xc7,
	0x10, 0x1c, 0xff, 0xb5, 0x03, 0x67, 0x76, 0xd1, 0xdc, 0x7d, 0xac, 0xd7, 0xcb, 0x26, 0xad, 0x3f,
	0x3c, 0xdd, 0xe1, 0xa7, 0xba, 0x59, 0xbb, 0xe7, 0x87, 0x9a, 0x7f, 0x07, 0xef, 0x12, 0xad, 0x14,
	0x26, 0x4e, 0x6a, 0xe5, 0xad, 0x13, 0xae, 0xb4, 0x3e, 0x99, 0x0a, 0x95, 0x21, 0xeb, 0xf1, 0x13,
	0x18, 0x96, 0x26, 0x15, 0x0e, 0x53, 0xef, 0xf4, 0x0c, 0x15, 0xdb, 0xe6, 0x67, 0x70, 0x6a, 0x84,
	0xb5, 0x66, 0x4a, 0xc2, 0xa2, 0x27, 0xfc, 0xa5, 0x94, 0x84, 0x29, 0xdb, 0xf9, 0x22, 0x20, 0x92,
	0x04, 0x8d, 0xc3, 0x94, 0xed, 0xf2, 0x6f, 0xe1, 0x4c, 0x2a, 0xe9, 0xa4, 0xc8, 0xe5, 0x6f, 0x22,
	0x3e, 0x93, 0xe8, 0xc2, 0xe4, 0xe8, 0x90, 0xed, 0x85, 0xf7, 0xad, 0xd3, 0xc6, 0xdb, 0x4a, 0x25,
	0x52, 0x65, 0xde, 0x20, 0x15, 0x42, 0xa1, 0x72, 0x79, 0xc5, 0xf6, 0xf9, 0x1b, 0x60, 0x22, 0x22,
	0x13, 0x93, 0x1c, 0x3d, 0x12, 0x69, 0x62, 0x07, 0xa1, 0x21, 0xaa, 0x84, 0x2a, 0x13, 0x71, 0x55,
	0x06, 0x5f, 0x11, 0xa7, 0x6c, 0x10, 0x82, 0x9f, 0xc1, 0x08, 0xd1, 0x2e, 0x08, 0xfc, 0x1c, 0xde,
	0xce, 0xb0, 0xb2, 0x4e, 0x13, 0xb6, 0x03, 0xf9, 0x97, 0xf1, 0xd8, 0x21, 0x7f, 0x0b, 0x3c, 0xd1,
	0xea, 0x52, 0x66, 0x25, 0xe1, 0x06, 0xe1, 0x51, 0x68, 0x38, 0xd1, 0xda, 0x59, 0x47, 0xc2, 0x7c,
	0x51, 0x34, 0xe4, 0xdf, 0xc3, 0xb9, 0xa3, 0xd2, 0x06, 0x20, 0x57, 0xa2, 0xcc, 0x9d, 0x9f, 0x61,
	0xb5, 0x21, 0x65, 0xf4, 0xf5, 0x78, 0xc7, 0xcd, 0xf1, 0xf8, 0x9f, 0x1e, 0x8c, 0xcc, 0xcd, 0x5d,
	0xed, 0x56, 0x37, 0xcd, 0xe3, 0x62, 0xbd, 0x58, 0x36, 0xfc, 0x00, 0x76, 0x73, 0xa9, 0x66, 0x6c,
	0x8b, 0x0f, 0x60, 0x2f, 0xe0, 0x4f, 0xdb, 0x45, 0x88, 0xd2, 0x69, 0x3f, 0xd1, 0x7a, 0x56, 0x08,
	0x9a, 0xb1, 0xed, 0xce, 0x65, 0xcb, 0xc9, 0x25, 0x89, 0x02, 0xd9, 0x0e, 0x3f, 0x85, 0xe3, 0x42,
	0xa8, 0x52, 0xe4, 0x1b, 0xe7, 0x2e, 0x1f, 0xc2, 0x20, 0x43, 0x85, 0x14, 0x11, 0xef, 0x75, 0x65,
	0x4e, 0x9b, 0x1c, 0xaf, 0x30, 0x67, 0xfb, 0xfc, 0x18, 0x0e, 0x2f, 0x35, 0x15, 0xa1, 0xa8, 0x90,
	0x8e, 0xf5, 0x39, 0xc0, 0x3e, 0x61, 0xae, 0x45, 0xca, 0x0e, 0xf8, 0x21, 0xf4, 0x67, 0x58, 0x5d,
	0x6b, 0x0a, 0xe4, 0x7e, 0x03, 0x27, 0x2f, 0x86, 0xdf, 0xf4, 0x84, 0xf1, 0x25, 0x9c, 0xff, 0x7f,
	0x08, 0xaa, 0x6f, 0x17, 0xab, 0x7a, 0xde, 0x4a, 0xec, 0x14, 0x8e, 0x93, 0x5c, 0xa2, 0x72, 0x9e,
	0x30, 0x95, 0x84, 0x89, 0x63, 0xbd, 0xe0, 0xb4, 0x48, 0x57, 0x48, 0x1b, 0xe7, 0xf6, 0xf8, 0xdf,
	0x1e, 0x0c, 0x70, 0xb5, 0x5a, 0xae, 0x62, 0xdd, 0x21, 0xf4, 0x6d, 0x99, 0x24, 0x68, 0x2d, 0xdb,
	0x0a, 0xf9, 0x4a, 0x3b, 0x5f, 0x54, 0x7e, 0x22, 0xc9, 0x4d, 0x53, 0x51, 0xb1, 0xed, 0x30, 0x9a,
	0x9b, 0x92, 0x76, 0x2e, 0x8f, 0x0a, 0x3c, 0x81, 0x61, 0x92, 0xa3, 0x20, 0x6f, 0x50, 0xa5, 0x52,
	0x65, 0xac, 0x1f, 0xca, 0x1c, 0x09, 0x65, 0xe3, 0xf3, 0xaf, 0xfa, 0xe1, 0x30, 0x2a, 0x64, 0x46,
	0xad, 0x16, 0x53, 0xad, 0xb0, 0x9d, 0x2c, 0x95, 0x36, 0xc8, 0x2c, 0xf5, 0x93, 0xca, 0x8b, 0xb4,
	0x90, 0x8a, 0x41, 0xa8, 0x37, 0x82, 0x82, 0x76, 0xfd, 0xa5, 0x90, 0x79, 0x49, 0x41, 0x11, 0xef,
	0xe0, 0xcd, 0xcb, 0x40, 0xa9, 0x70, 0xc2, 0xeb, 0x89, 0xd5, 0x51, 0x2b, 0xc3, 0x70, 0x03, 0x2f,
	0xca, 0x0c, 0xad, 0xbb, 0xc0, 0x28, 0xcc, 0x52, 0xaa, 0x99, 0xd2, 0xd7, 0x8a, 0xdd, 0x8e, 0x7f,
	0x86, 0x7d, 0x31, 0x8f, 0xbb, 0xe6, 0x30, 0x2a, 0x4d, 0x46, 0x22, 0x45, 0xdf, 0x76, 0x64, 0x5b,
	0xd1, 0xd7, 0xa6, 0xfa, 0x56, 0xfb, 0x6c, 0x6f, 0xfc, 0x47, 0x0f, 0x20, 0xad, 0x3f, 0x2d, 0xe6,
	0x75, 0x64, 0x66, 0x04, 0x10, 0x85, 0x5d, 0x2a, 0x8b, 0xa1, 0xe4, 0x08, 0x0e, 0xa2, 0x7d, 0x2d,
	0x15, 0xeb, 0x75, 0x56, 0x21, 0x12, 0xb6, 0xdd, 0xe5, 0xe6, 0x52, 0x95, 0xbf, 0xb2, 0x9d, 0xc8,
	0x59, 0x3c, 0x0a, 0xd2, 0x96, 0xed, 0x76, 0x61, 0xed, 0xa6, 0x48, 0x6c, 0xaf, 0xb3, 0xcd, 0x34,
	0xf0, 0x12, 0xb5, 0x11, 0x6d, 0x17, 0xa8, 0x71, 0xac, 0x3f, 0xfe, 0xbb, 0x07, 0x2c, 0xab, 0xd7,
	0xe5, 0xc3, 0xed, 0xcd, 0xba, 0x7e, 0xd4, 0xab, 0xc5, 0xdd, 0xa2, 0xf9, 0x1c, 0xb3, 0x26, 0x99,
	0x49, 0xd5, 0x82, 0x32, 0x48, 0x52, 0xa7, 0x32, 0x61, 0xbb, 0xe1, 0xce, 0x15, 0x5e, 0xe7, 0x95,
	0xb7, 0xa5, 0x31, 0x9a, 0xc2, 0x41, 0x04, 0xf2, 0x42, 0x6f, 0xd6, 0x0f, 0xa0, 0xba, 0x8d, 0xb0,
	0x83, 0x00, 0x42, 0xe1, 0xf5, 0x2b, 0x25, 0x83, 0xb0, 0x05, 0xc2, 0xd7, 0xe3, 0x6c, 0x93, 0x20,
	0x24, 0x65, 0xa5, 0x77, 0x24, 0xb3, 0x0c, 0x89, 0x1d, 0x85, 0x6b, 0x21, 0x74, 0x54, 0xb1, 0x21,
	0x67, 0x70, 0x64, 0x48, 0x67, 0x24, 0x8a, 0x42, 0x38, 0x99, 0xb0, 0xd1, 0xe4, 0x27, 0xf8, 0x61,
	0xb9, 0xba, 0xbb, 0x98, 0xff, 0xbe, 0x5a, 0xde, 0x2f, 0x9e, 0xee, 0x2f, 0x36, 0x7f, 0xea, 0x45,
	0xf8, 0x33, 0x2f, 0x5e, 0xff, 0xd4, 0xe9, 0x8e, 0xe9, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa0,
	0xf2, 0x79, 0xb9, 0x72, 0x05, 0x00, 0x00,
}
