// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/test.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UnknownFieldsTestA struct {
	Foo                  *bool    `protobuf:"varint,1,req,name=foo" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnknownFieldsTestA) Reset()         { *m = UnknownFieldsTestA{} }
func (m *UnknownFieldsTestA) String() string { return proto.CompactTextString(m) }
func (*UnknownFieldsTestA) ProtoMessage()    {}
func (*UnknownFieldsTestA) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_13cc3ef2ca4c6d27, []int{0}
}
func (m *UnknownFieldsTestA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnknownFieldsTestA.Unmarshal(m, b)
}
func (m *UnknownFieldsTestA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnknownFieldsTestA.Marshal(b, m, deterministic)
}
func (dst *UnknownFieldsTestA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnknownFieldsTestA.Merge(dst, src)
}
func (m *UnknownFieldsTestA) XXX_Size() int {
	return xxx_messageInfo_UnknownFieldsTestA.Size(m)
}
func (m *UnknownFieldsTestA) XXX_DiscardUnknown() {
	xxx_messageInfo_UnknownFieldsTestA.DiscardUnknown(m)
}

var xxx_messageInfo_UnknownFieldsTestA proto.InternalMessageInfo

func (m *UnknownFieldsTestA) GetFoo() bool {
	if m != nil && m.Foo != nil {
		return *m.Foo
	}
	return false
}

type UnknownFieldsTestB struct {
	Foo                  *bool    `protobuf:"varint,1,req,name=foo" json:"foo,omitempty"`
	Bar                  *bool    `protobuf:"varint,2,req,name=bar" json:"bar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnknownFieldsTestB) Reset()         { *m = UnknownFieldsTestB{} }
func (m *UnknownFieldsTestB) String() string { return proto.CompactTextString(m) }
func (*UnknownFieldsTestB) ProtoMessage()    {}
func (*UnknownFieldsTestB) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_13cc3ef2ca4c6d27, []int{1}
}
func (m *UnknownFieldsTestB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnknownFieldsTestB.Unmarshal(m, b)
}
func (m *UnknownFieldsTestB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnknownFieldsTestB.Marshal(b, m, deterministic)
}
func (dst *UnknownFieldsTestB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnknownFieldsTestB.Merge(dst, src)
}
func (m *UnknownFieldsTestB) XXX_Size() int {
	return xxx_messageInfo_UnknownFieldsTestB.Size(m)
}
func (m *UnknownFieldsTestB) XXX_DiscardUnknown() {
	xxx_messageInfo_UnknownFieldsTestB.DiscardUnknown(m)
}

var xxx_messageInfo_UnknownFieldsTestB proto.InternalMessageInfo

func (m *UnknownFieldsTestB) GetFoo() bool {
	if m != nil && m.Foo != nil {
		return *m.Foo
	}
	return false
}

func (m *UnknownFieldsTestB) GetBar() bool {
	if m != nil && m.Bar != nil {
		return *m.Bar
	}
	return false
}

func init() {
	proto.RegisterType((*UnknownFieldsTestA)(nil), "sync_pb.UnknownFieldsTestA")
	proto.RegisterType((*UnknownFieldsTestB)(nil), "sync_pb.UnknownFieldsTestB")
}

func init() {
	proto.RegisterFile("components/sync/protocol/test.proto", fileDescriptor_test_13cc3ef2ca4c6d27)
}

var fileDescriptor_test_13cc3ef2ca4c6d27 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4e, 0xce, 0xcf, 0x2d,
	0xc8, 0xcf, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x2f, 0xae, 0xcc, 0x4b, 0xd6, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x03, 0xf3, 0x84, 0xd8, 0x41, 0x32,
	0xf1, 0x05, 0x49, 0x4a, 0x6a, 0x5c, 0x42, 0xa1, 0x79, 0xd9, 0x79, 0xf9, 0xe5, 0x79, 0x6e, 0x99,
	0xa9, 0x39, 0x29, 0xc5, 0x21, 0xa9, 0xc5, 0x25, 0x8e, 0x42, 0x02, 0x5c, 0xcc, 0x69, 0xf9, 0xf9,
	0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x1c, 0x41, 0x20, 0xa6, 0x92, 0x05, 0x16, 0x75, 0x4e, 0x98, 0xea,
	0x40, 0x22, 0x49, 0x89, 0x45, 0x12, 0x4c, 0x10, 0x91, 0xa4, 0xc4, 0x22, 0x27, 0x6d, 0x2e, 0xd5,
	0xfc, 0xa2, 0x74, 0xbd, 0xe4, 0x8c, 0xa2, 0xfc, 0xdc, 0xcc, 0xd2, 0x5c, 0x3d, 0x84, 0xf3, 0xf4,
	0x40, 0x8e, 0xd0, 0x83, 0x39, 0xcf, 0x83, 0x39, 0x80, 0x11, 0x10, 0x00, 0x00, 0xff, 0xff, 0x8c,
	0x26, 0xde, 0x48, 0xbd, 0x00, 0x00, 0x00,
}
