// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/sync/protocol/user_event_specifics.proto

package sync_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserEventSpecifics_Translation_Interaction int32

const (
	UserEventSpecifics_Translation_UNKNOWN UserEventSpecifics_Translation_Interaction = 0
	UserEventSpecifics_Translation_ACCEPT  UserEventSpecifics_Translation_Interaction = 1
	UserEventSpecifics_Translation_DECLINE UserEventSpecifics_Translation_Interaction = 2
	// This happens when user scroll or click outside the UI without
	// translation.
	UserEventSpecifics_Translation_IGNORED UserEventSpecifics_Translation_Interaction = 3
	// This happens when user choose to close the translation window without
	// translation.
	UserEventSpecifics_Translation_DISMISSED UserEventSpecifics_Translation_Interaction = 4
	// User manually entered either language.
	// In this case, from_language_code and to_language_code will be user
	// chosen values.
	UserEventSpecifics_Translation_MANUAL UserEventSpecifics_Translation_Interaction = 5
	// User choose to revert the translation, in this case, from_language_code
	// and to_language_code will be previous chosen values.
	UserEventSpecifics_Translation_TRANSLATION_REVERTED UserEventSpecifics_Translation_Interaction = 6
	// Automatically triggered translation.
	// User sets always translate in user settings.
	UserEventSpecifics_Translation_AUTO_TRANSLATION_BY_PREF UserEventSpecifics_Translation_Interaction = 7
	// User navigated through a click from a translated page.
	UserEventSpecifics_Translation_AUTO_TRANSLATION_BY_LINK UserEventSpecifics_Translation_Interaction = 8
	// Failed to initialize the translate script, this can happen for iOS due
	// to CSPs.
	UserEventSpecifics_Translation_INITIALIZATION_ERROR UserEventSpecifics_Translation_Interaction = 9
)

var UserEventSpecifics_Translation_Interaction_name = map[int32]string{
	0: "UNKNOWN",
	1: "ACCEPT",
	2: "DECLINE",
	3: "IGNORED",
	4: "DISMISSED",
	5: "MANUAL",
	6: "TRANSLATION_REVERTED",
	7: "AUTO_TRANSLATION_BY_PREF",
	8: "AUTO_TRANSLATION_BY_LINK",
	9: "INITIALIZATION_ERROR",
}
var UserEventSpecifics_Translation_Interaction_value = map[string]int32{
	"UNKNOWN":                  0,
	"ACCEPT":                   1,
	"DECLINE":                  2,
	"IGNORED":                  3,
	"DISMISSED":                4,
	"MANUAL":                   5,
	"TRANSLATION_REVERTED":     6,
	"AUTO_TRANSLATION_BY_PREF": 7,
	"AUTO_TRANSLATION_BY_LINK": 8,
	"INITIALIZATION_ERROR":     9,
}

func (x UserEventSpecifics_Translation_Interaction) Enum() *UserEventSpecifics_Translation_Interaction {
	p := new(UserEventSpecifics_Translation_Interaction)
	*p = x
	return p
}
func (x UserEventSpecifics_Translation_Interaction) String() string {
	return proto.EnumName(UserEventSpecifics_Translation_Interaction_name, int32(x))
}
func (x *UserEventSpecifics_Translation_Interaction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserEventSpecifics_Translation_Interaction_value, data, "UserEventSpecifics_Translation_Interaction")
	if err != nil {
		return err
	}
	*x = UserEventSpecifics_Translation_Interaction(value)
	return nil
}
func (UserEventSpecifics_Translation_Interaction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 2, 0}
}

// Which feature does the consent apply to?
type UserEventSpecifics_UserConsent_Feature int32

const (
	UserEventSpecifics_UserConsent_FEATURE_UNSPECIFIED     UserEventSpecifics_UserConsent_Feature = 0
	UserEventSpecifics_UserConsent_CHROME_SYNC             UserEventSpecifics_UserConsent_Feature = 1
	UserEventSpecifics_UserConsent_PLAY_STORE              UserEventSpecifics_UserConsent_Feature = 2
	UserEventSpecifics_UserConsent_BACKUP_AND_RESTORE      UserEventSpecifics_UserConsent_Feature = 3
	UserEventSpecifics_UserConsent_GOOGLE_LOCATION_SERVICE UserEventSpecifics_UserConsent_Feature = 4
	UserEventSpecifics_UserConsent_CHROME_UNIFIED_CONSENT  UserEventSpecifics_UserConsent_Feature = 5
	// TODO(markusheintz): ASSISTANT_ACTIVITY_CONTROL was only added as
	// emergency fallback. Remove if not needed.
	UserEventSpecifics_UserConsent_ASSISTANT_ACTIVITY_CONTROL UserEventSpecifics_UserConsent_Feature = 6
)

var UserEventSpecifics_UserConsent_Feature_name = map[int32]string{
	0: "FEATURE_UNSPECIFIED",
	1: "CHROME_SYNC",
	2: "PLAY_STORE",
	3: "BACKUP_AND_RESTORE",
	4: "GOOGLE_LOCATION_SERVICE",
	5: "CHROME_UNIFIED_CONSENT",
	6: "ASSISTANT_ACTIVITY_CONTROL",
}
var UserEventSpecifics_UserConsent_Feature_value = map[string]int32{
	"FEATURE_UNSPECIFIED":        0,
	"CHROME_SYNC":                1,
	"PLAY_STORE":                 2,
	"BACKUP_AND_RESTORE":         3,
	"GOOGLE_LOCATION_SERVICE":    4,
	"CHROME_UNIFIED_CONSENT":     5,
	"ASSISTANT_ACTIVITY_CONTROL": 6,
}

func (x UserEventSpecifics_UserConsent_Feature) Enum() *UserEventSpecifics_UserConsent_Feature {
	p := new(UserEventSpecifics_UserConsent_Feature)
	*p = x
	return p
}
func (x UserEventSpecifics_UserConsent_Feature) String() string {
	return proto.EnumName(UserEventSpecifics_UserConsent_Feature_name, int32(x))
}
func (x *UserEventSpecifics_UserConsent_Feature) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserEventSpecifics_UserConsent_Feature_value, data, "UserEventSpecifics_UserConsent_Feature")
	if err != nil {
		return err
	}
	*x = UserEventSpecifics_UserConsent_Feature(value)
	return nil
}
func (UserEventSpecifics_UserConsent_Feature) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 3, 0}
}

type UserEventSpecifics_GaiaPasswordCaptured_EventTrigger int32

const (
	UserEventSpecifics_GaiaPasswordCaptured_UNSPECIFIED UserEventSpecifics_GaiaPasswordCaptured_EventTrigger = 0
	// Event added because user logged in.
	UserEventSpecifics_GaiaPasswordCaptured_USER_LOGGED_IN UserEventSpecifics_GaiaPasswordCaptured_EventTrigger = 1
	// Event added because 28d timer fired.
	UserEventSpecifics_GaiaPasswordCaptured_EXPIRED_28D_TIMER UserEventSpecifics_GaiaPasswordCaptured_EventTrigger = 2
)

var UserEventSpecifics_GaiaPasswordCaptured_EventTrigger_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "USER_LOGGED_IN",
	2: "EXPIRED_28D_TIMER",
}
var UserEventSpecifics_GaiaPasswordCaptured_EventTrigger_value = map[string]int32{
	"UNSPECIFIED":       0,
	"USER_LOGGED_IN":    1,
	"EXPIRED_28D_TIMER": 2,
}

func (x UserEventSpecifics_GaiaPasswordCaptured_EventTrigger) Enum() *UserEventSpecifics_GaiaPasswordCaptured_EventTrigger {
	p := new(UserEventSpecifics_GaiaPasswordCaptured_EventTrigger)
	*p = x
	return p
}
func (x UserEventSpecifics_GaiaPasswordCaptured_EventTrigger) String() string {
	return proto.EnumName(UserEventSpecifics_GaiaPasswordCaptured_EventTrigger_name, int32(x))
}
func (x *UserEventSpecifics_GaiaPasswordCaptured_EventTrigger) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserEventSpecifics_GaiaPasswordCaptured_EventTrigger_value, data, "UserEventSpecifics_GaiaPasswordCaptured_EventTrigger")
	if err != nil {
		return err
	}
	*x = UserEventSpecifics_GaiaPasswordCaptured_EventTrigger(value)
	return nil
}
func (UserEventSpecifics_GaiaPasswordCaptured_EventTrigger) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 4, 0}
}

type UserEventSpecifics_FlocIdComputed_EventTrigger int32

const (
	UserEventSpecifics_FlocIdComputed_UNSPECIFIED UserEventSpecifics_FlocIdComputed_EventTrigger = 0
	// Event added because the floc id is computed for the 1st floc session.
	UserEventSpecifics_FlocIdComputed_NEW UserEventSpecifics_FlocIdComputed_EventTrigger = 1
	// Event added because the floc id is re-computed due to a long period of
	// time has passed since the last computation.
	UserEventSpecifics_FlocIdComputed_REFRESHED UserEventSpecifics_FlocIdComputed_EventTrigger = 2
	// Event added because the floc id is re-computed due to history deletion.
	UserEventSpecifics_FlocIdComputed_HISTORY_DELETE UserEventSpecifics_FlocIdComputed_EventTrigger = 3
)

var UserEventSpecifics_FlocIdComputed_EventTrigger_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "NEW",
	2: "REFRESHED",
	3: "HISTORY_DELETE",
}
var UserEventSpecifics_FlocIdComputed_EventTrigger_value = map[string]int32{
	"UNSPECIFIED":    0,
	"NEW":            1,
	"REFRESHED":      2,
	"HISTORY_DELETE": 3,
}

func (x UserEventSpecifics_FlocIdComputed_EventTrigger) Enum() *UserEventSpecifics_FlocIdComputed_EventTrigger {
	p := new(UserEventSpecifics_FlocIdComputed_EventTrigger)
	*p = x
	return p
}
func (x UserEventSpecifics_FlocIdComputed_EventTrigger) String() string {
	return proto.EnumName(UserEventSpecifics_FlocIdComputed_EventTrigger_name, int32(x))
}
func (x *UserEventSpecifics_FlocIdComputed_EventTrigger) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserEventSpecifics_FlocIdComputed_EventTrigger_value, data, "UserEventSpecifics_FlocIdComputed_EventTrigger")
	if err != nil {
		return err
	}
	*x = UserEventSpecifics_FlocIdComputed_EventTrigger(value)
	return nil
}
func (UserEventSpecifics_FlocIdComputed_EventTrigger) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 5, 0}
}

type UserEventSpecifics struct {
	// Time of event, as measured by client in microseconds since Windows epoch.
	EventTimeUsec *int64 `protobuf:"varint,1,opt,name=event_time_usec,json=eventTimeUsec" json:"event_time_usec,omitempty"`
	// The |global_id| field of the associated navigation, if there is one.
	NavigationId *int64 `protobuf:"varint,2,opt,name=navigation_id,json=navigationId" json:"navigation_id,omitempty"`
	// On startup we generate a new random id to identify which FieldTrialEvents
	// other events belonged to.
	SessionId *uint64 `protobuf:"fixed64,3,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*UserEventSpecifics_TestEvent
	//	*UserEventSpecifics_LanguageDetectionEvent
	//	*UserEventSpecifics_TranslationEvent
	//	*UserEventSpecifics_UserConsent_
	//	*UserEventSpecifics_GaiaPasswordReuseEvent
	//	*UserEventSpecifics_GaiaPasswordCapturedEvent
	//	*UserEventSpecifics_FlocIdComputedEvent
	Event                isUserEventSpecifics_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UserEventSpecifics) Reset()         { *m = UserEventSpecifics{} }
func (m *UserEventSpecifics) String() string { return proto.CompactTextString(m) }
func (*UserEventSpecifics) ProtoMessage()    {}
func (*UserEventSpecifics) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0}
}
func (m *UserEventSpecifics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics.Unmarshal(m, b)
}
func (m *UserEventSpecifics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics.Merge(dst, src)
}
func (m *UserEventSpecifics) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics.Size(m)
}
func (m *UserEventSpecifics) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics proto.InternalMessageInfo

type isUserEventSpecifics_Event interface {
	isUserEventSpecifics_Event()
}

type UserEventSpecifics_TestEvent struct {
	TestEvent *UserEventSpecifics_Test `protobuf:"bytes,8,opt,name=test_event,json=testEvent,oneof"`
}
type UserEventSpecifics_LanguageDetectionEvent struct {
	LanguageDetectionEvent *UserEventSpecifics_LanguageDetection `protobuf:"bytes,10,opt,name=language_detection_event,json=languageDetectionEvent,oneof"`
}
type UserEventSpecifics_TranslationEvent struct {
	TranslationEvent *UserEventSpecifics_Translation `protobuf:"bytes,11,opt,name=translation_event,json=translationEvent,oneof"`
}
type UserEventSpecifics_UserConsent_ struct {
	UserConsent *UserEventSpecifics_UserConsent `protobuf:"bytes,12,opt,name=user_consent,json=userConsent,oneof"`
}
type UserEventSpecifics_GaiaPasswordReuseEvent struct {
	GaiaPasswordReuseEvent *GaiaPasswordReuse `protobuf:"bytes,104,opt,name=gaia_password_reuse_event,json=gaiaPasswordReuseEvent,oneof"`
}
type UserEventSpecifics_GaiaPasswordCapturedEvent struct {
	GaiaPasswordCapturedEvent *UserEventSpecifics_GaiaPasswordCaptured `protobuf:"bytes,15,opt,name=gaia_password_captured_event,json=gaiaPasswordCapturedEvent,oneof"`
}
type UserEventSpecifics_FlocIdComputedEvent struct {
	FlocIdComputedEvent *UserEventSpecifics_FlocIdComputed `protobuf:"bytes,16,opt,name=floc_id_computed_event,json=flocIdComputedEvent,oneof"`
}

func (*UserEventSpecifics_TestEvent) isUserEventSpecifics_Event()                 {}
func (*UserEventSpecifics_LanguageDetectionEvent) isUserEventSpecifics_Event()    {}
func (*UserEventSpecifics_TranslationEvent) isUserEventSpecifics_Event()          {}
func (*UserEventSpecifics_UserConsent_) isUserEventSpecifics_Event()              {}
func (*UserEventSpecifics_GaiaPasswordReuseEvent) isUserEventSpecifics_Event()    {}
func (*UserEventSpecifics_GaiaPasswordCapturedEvent) isUserEventSpecifics_Event() {}
func (*UserEventSpecifics_FlocIdComputedEvent) isUserEventSpecifics_Event()       {}

func (m *UserEventSpecifics) GetEvent() isUserEventSpecifics_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *UserEventSpecifics) GetEventTimeUsec() int64 {
	if m != nil && m.EventTimeUsec != nil {
		return *m.EventTimeUsec
	}
	return 0
}

func (m *UserEventSpecifics) GetNavigationId() int64 {
	if m != nil && m.NavigationId != nil {
		return *m.NavigationId
	}
	return 0
}

func (m *UserEventSpecifics) GetSessionId() uint64 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *UserEventSpecifics) GetTestEvent() *UserEventSpecifics_Test {
	if x, ok := m.GetEvent().(*UserEventSpecifics_TestEvent); ok {
		return x.TestEvent
	}
	return nil
}

// Deprecated: Do not use.
func (m *UserEventSpecifics) GetLanguageDetectionEvent() *UserEventSpecifics_LanguageDetection {
	if x, ok := m.GetEvent().(*UserEventSpecifics_LanguageDetectionEvent); ok {
		return x.LanguageDetectionEvent
	}
	return nil
}

// Deprecated: Do not use.
func (m *UserEventSpecifics) GetTranslationEvent() *UserEventSpecifics_Translation {
	if x, ok := m.GetEvent().(*UserEventSpecifics_TranslationEvent); ok {
		return x.TranslationEvent
	}
	return nil
}

// Deprecated: Do not use.
func (m *UserEventSpecifics) GetUserConsent() *UserEventSpecifics_UserConsent {
	if x, ok := m.GetEvent().(*UserEventSpecifics_UserConsent_); ok {
		return x.UserConsent
	}
	return nil
}

func (m *UserEventSpecifics) GetGaiaPasswordReuseEvent() *GaiaPasswordReuse {
	if x, ok := m.GetEvent().(*UserEventSpecifics_GaiaPasswordReuseEvent); ok {
		return x.GaiaPasswordReuseEvent
	}
	return nil
}

func (m *UserEventSpecifics) GetGaiaPasswordCapturedEvent() *UserEventSpecifics_GaiaPasswordCaptured {
	if x, ok := m.GetEvent().(*UserEventSpecifics_GaiaPasswordCapturedEvent); ok {
		return x.GaiaPasswordCapturedEvent
	}
	return nil
}

func (m *UserEventSpecifics) GetFlocIdComputedEvent() *UserEventSpecifics_FlocIdComputed {
	if x, ok := m.GetEvent().(*UserEventSpecifics_FlocIdComputedEvent); ok {
		return x.FlocIdComputedEvent
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UserEventSpecifics) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UserEventSpecifics_OneofMarshaler, _UserEventSpecifics_OneofUnmarshaler, _UserEventSpecifics_OneofSizer, []interface{}{
		(*UserEventSpecifics_TestEvent)(nil),
		(*UserEventSpecifics_LanguageDetectionEvent)(nil),
		(*UserEventSpecifics_TranslationEvent)(nil),
		(*UserEventSpecifics_UserConsent_)(nil),
		(*UserEventSpecifics_GaiaPasswordReuseEvent)(nil),
		(*UserEventSpecifics_GaiaPasswordCapturedEvent)(nil),
		(*UserEventSpecifics_FlocIdComputedEvent)(nil),
	}
}

func _UserEventSpecifics_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UserEventSpecifics)
	// event
	switch x := m.Event.(type) {
	case *UserEventSpecifics_TestEvent:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TestEvent); err != nil {
			return err
		}
	case *UserEventSpecifics_LanguageDetectionEvent:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LanguageDetectionEvent); err != nil {
			return err
		}
	case *UserEventSpecifics_TranslationEvent:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TranslationEvent); err != nil {
			return err
		}
	case *UserEventSpecifics_UserConsent_:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserConsent); err != nil {
			return err
		}
	case *UserEventSpecifics_GaiaPasswordReuseEvent:
		b.EncodeVarint(104<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GaiaPasswordReuseEvent); err != nil {
			return err
		}
	case *UserEventSpecifics_GaiaPasswordCapturedEvent:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GaiaPasswordCapturedEvent); err != nil {
			return err
		}
	case *UserEventSpecifics_FlocIdComputedEvent:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FlocIdComputedEvent); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UserEventSpecifics.Event has unexpected type %T", x)
	}
	return nil
}

func _UserEventSpecifics_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UserEventSpecifics)
	switch tag {
	case 8: // event.test_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEventSpecifics_Test)
		err := b.DecodeMessage(msg)
		m.Event = &UserEventSpecifics_TestEvent{msg}
		return true, err
	case 10: // event.language_detection_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEventSpecifics_LanguageDetection)
		err := b.DecodeMessage(msg)
		m.Event = &UserEventSpecifics_LanguageDetectionEvent{msg}
		return true, err
	case 11: // event.translation_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEventSpecifics_Translation)
		err := b.DecodeMessage(msg)
		m.Event = &UserEventSpecifics_TranslationEvent{msg}
		return true, err
	case 12: // event.user_consent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEventSpecifics_UserConsent)
		err := b.DecodeMessage(msg)
		m.Event = &UserEventSpecifics_UserConsent_{msg}
		return true, err
	case 104: // event.gaia_password_reuse_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GaiaPasswordReuse)
		err := b.DecodeMessage(msg)
		m.Event = &UserEventSpecifics_GaiaPasswordReuseEvent{msg}
		return true, err
	case 15: // event.gaia_password_captured_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEventSpecifics_GaiaPasswordCaptured)
		err := b.DecodeMessage(msg)
		m.Event = &UserEventSpecifics_GaiaPasswordCapturedEvent{msg}
		return true, err
	case 16: // event.floc_id_computed_event
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserEventSpecifics_FlocIdComputed)
		err := b.DecodeMessage(msg)
		m.Event = &UserEventSpecifics_FlocIdComputedEvent{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UserEventSpecifics_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UserEventSpecifics)
	// event
	switch x := m.Event.(type) {
	case *UserEventSpecifics_TestEvent:
		s := proto.Size(x.TestEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_LanguageDetectionEvent:
		s := proto.Size(x.LanguageDetectionEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_TranslationEvent:
		s := proto.Size(x.TranslationEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_UserConsent_:
		s := proto.Size(x.UserConsent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_GaiaPasswordReuseEvent:
		s := proto.Size(x.GaiaPasswordReuseEvent)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_GaiaPasswordCapturedEvent:
		s := proto.Size(x.GaiaPasswordCapturedEvent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_FlocIdComputedEvent:
		s := proto.Size(x.FlocIdComputedEvent)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Used for testing and debugging EventLog system.
type UserEventSpecifics_Test struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEventSpecifics_Test) Reset()         { *m = UserEventSpecifics_Test{} }
func (m *UserEventSpecifics_Test) String() string { return proto.CompactTextString(m) }
func (*UserEventSpecifics_Test) ProtoMessage()    {}
func (*UserEventSpecifics_Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 0}
}
func (m *UserEventSpecifics_Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics_Test.Unmarshal(m, b)
}
func (m *UserEventSpecifics_Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics_Test.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics_Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics_Test.Merge(dst, src)
}
func (m *UserEventSpecifics_Test) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics_Test.Size(m)
}
func (m *UserEventSpecifics_Test) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics_Test.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics_Test proto.InternalMessageInfo

// Language detection output.
//
// Deprecated: Do not use.
type UserEventSpecifics_LanguageDetection struct {
	// Top n languages. Typically we just log the top language, but for page
	// that we're not confident about, we may log up to 3 top languages in
	// descending order.
	DetectedLanguages []*UserEventSpecifics_LanguageDetection_Language `protobuf:"bytes,1,rep,name=detected_languages,json=detectedLanguages" json:"detected_languages,omitempty"`
	// Adopted language code is the code of final determined language.
	// It will be stored only if it's different from the first detected
	// language.
	AdoptedLanguageCode  *string  `protobuf:"bytes,2,opt,name=adopted_language_code,json=adoptedLanguageCode" json:"adopted_language_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEventSpecifics_LanguageDetection) Reset()         { *m = UserEventSpecifics_LanguageDetection{} }
func (m *UserEventSpecifics_LanguageDetection) String() string { return proto.CompactTextString(m) }
func (*UserEventSpecifics_LanguageDetection) ProtoMessage()    {}
func (*UserEventSpecifics_LanguageDetection) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 1}
}
func (m *UserEventSpecifics_LanguageDetection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics_LanguageDetection.Unmarshal(m, b)
}
func (m *UserEventSpecifics_LanguageDetection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics_LanguageDetection.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics_LanguageDetection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics_LanguageDetection.Merge(dst, src)
}
func (m *UserEventSpecifics_LanguageDetection) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics_LanguageDetection.Size(m)
}
func (m *UserEventSpecifics_LanguageDetection) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics_LanguageDetection.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics_LanguageDetection proto.InternalMessageInfo

func (m *UserEventSpecifics_LanguageDetection) GetDetectedLanguages() []*UserEventSpecifics_LanguageDetection_Language {
	if m != nil {
		return m.DetectedLanguages
	}
	return nil
}

func (m *UserEventSpecifics_LanguageDetection) GetAdoptedLanguageCode() string {
	if m != nil && m.AdoptedLanguageCode != nil {
		return *m.AdoptedLanguageCode
	}
	return ""
}

type UserEventSpecifics_LanguageDetection_Language struct {
	// ISO 639 language code will be used.
	LanguageCode *string `protobuf:"bytes,1,opt,name=language_code,json=languageCode" json:"language_code,omitempty"`
	// Whether the detected language is reliable, note this is determined by
	// the CLD3.
	IsReliable           *bool    `protobuf:"varint,2,opt,name=is_reliable,json=isReliable" json:"is_reliable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEventSpecifics_LanguageDetection_Language) Reset() {
	*m = UserEventSpecifics_LanguageDetection_Language{}
}
func (m *UserEventSpecifics_LanguageDetection_Language) String() string {
	return proto.CompactTextString(m)
}
func (*UserEventSpecifics_LanguageDetection_Language) ProtoMessage() {}
func (*UserEventSpecifics_LanguageDetection_Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 1, 0}
}
func (m *UserEventSpecifics_LanguageDetection_Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics_LanguageDetection_Language.Unmarshal(m, b)
}
func (m *UserEventSpecifics_LanguageDetection_Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics_LanguageDetection_Language.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics_LanguageDetection_Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics_LanguageDetection_Language.Merge(dst, src)
}
func (m *UserEventSpecifics_LanguageDetection_Language) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics_LanguageDetection_Language.Size(m)
}
func (m *UserEventSpecifics_LanguageDetection_Language) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics_LanguageDetection_Language.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics_LanguageDetection_Language proto.InternalMessageInfo

func (m *UserEventSpecifics_LanguageDetection_Language) GetLanguageCode() string {
	if m != nil && m.LanguageCode != nil {
		return *m.LanguageCode
	}
	return ""
}

func (m *UserEventSpecifics_LanguageDetection_Language) GetIsReliable() bool {
	if m != nil && m.IsReliable != nil {
		return *m.IsReliable
	}
	return false
}

// User translated a page or interacted with translate suggestion.
//
// Deprecated: Do not use.
type UserEventSpecifics_Translation struct {
	// Source language of the translation.
	FromLanguageCode *string `protobuf:"bytes,1,opt,name=from_language_code,json=fromLanguageCode" json:"from_language_code,omitempty"`
	// Target language of the translation.
	ToLanguageCode       *string                                     `protobuf:"bytes,2,opt,name=to_language_code,json=toLanguageCode" json:"to_language_code,omitempty"`
	Interaction          *UserEventSpecifics_Translation_Interaction `protobuf:"varint,3,opt,name=interaction,enum=sync_pb.UserEventSpecifics_Translation_Interaction" json:"interaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *UserEventSpecifics_Translation) Reset()         { *m = UserEventSpecifics_Translation{} }
func (m *UserEventSpecifics_Translation) String() string { return proto.CompactTextString(m) }
func (*UserEventSpecifics_Translation) ProtoMessage()    {}
func (*UserEventSpecifics_Translation) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 2}
}
func (m *UserEventSpecifics_Translation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics_Translation.Unmarshal(m, b)
}
func (m *UserEventSpecifics_Translation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics_Translation.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics_Translation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics_Translation.Merge(dst, src)
}
func (m *UserEventSpecifics_Translation) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics_Translation.Size(m)
}
func (m *UserEventSpecifics_Translation) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics_Translation.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics_Translation proto.InternalMessageInfo

func (m *UserEventSpecifics_Translation) GetFromLanguageCode() string {
	if m != nil && m.FromLanguageCode != nil {
		return *m.FromLanguageCode
	}
	return ""
}

func (m *UserEventSpecifics_Translation) GetToLanguageCode() string {
	if m != nil && m.ToLanguageCode != nil {
		return *m.ToLanguageCode
	}
	return ""
}

func (m *UserEventSpecifics_Translation) GetInteraction() UserEventSpecifics_Translation_Interaction {
	if m != nil && m.Interaction != nil {
		return *m.Interaction
	}
	return UserEventSpecifics_Translation_UNKNOWN
}

// User consented to the usage of a feature or denied/revoked a consent.
// This is not used anymore; consents were migrated to a separate data type.
// The message has to stay though since the server must keep supporting legacy
// consent formats like this.
// Next id: 14
//
// Deprecated: Do not use.
type UserEventSpecifics_UserConsent struct {
	// The UI language Chrome is using, represented as the IETF language tag
	// defined in BCP 47. The region subtag is not included when it adds no
	// distinguishing information to the language tag (e.g. both "en-US"
	// and "fr" are correct here).
	Locale *string `protobuf:"bytes,4,opt,name=locale" json:"locale,omitempty"`
	// The local time on the client when the user consent was recorded. The time
	// as measured by client is given in microseconds since Windows epoch. This
	// is needed since user consent recording may happen when a client is
	// offline.
	ClientConsentTimeUsec *int64 `protobuf:"varint,12,opt,name=client_consent_time_usec,json=clientConsentTimeUsec" json:"client_consent_time_usec,omitempty"`
	// Types that are valid to be assigned to Consent:
	//	*UserEventSpecifics_UserConsent_SyncConsent
	//	*UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent
	//	*UserEventSpecifics_UserConsent_ArcLocationServiceConsent
	//	*UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent
	//	*UserEventSpecifics_UserConsent_UnifiedConsent
	Consent isUserEventSpecifics_UserConsent_Consent `protobuf_oneof:"consent"`
	Feature *UserEventSpecifics_UserConsent_Feature  `protobuf:"varint,1,opt,name=feature,enum=sync_pb.UserEventSpecifics_UserConsent_Feature" json:"feature,omitempty"` // Deprecated: Do not use.
	// Ids of the strings of the consent text presented to the user.
	DescriptionGrdIds []int32 `protobuf:"varint,2,rep,name=description_grd_ids,json=descriptionGrdIds" json:"description_grd_ids,omitempty"` // Deprecated: Do not use.
	// Id of the string of the UI element the user clicked when consenting.
	ConfirmationGrdId *int32 `protobuf:"varint,3,opt,name=confirmation_grd_id,json=confirmationGrdId" json:"confirmation_grd_id,omitempty"` // Deprecated: Do not use.
	// Was the consent for |feature| given or not given (denied/revoked)?
	Status               *UserConsentTypes_ConsentStatus `protobuf:"varint,5,opt,name=status,enum=sync_pb.UserConsentTypes_ConsentStatus" json:"status,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UserEventSpecifics_UserConsent) Reset()         { *m = UserEventSpecifics_UserConsent{} }
func (m *UserEventSpecifics_UserConsent) String() string { return proto.CompactTextString(m) }
func (*UserEventSpecifics_UserConsent) ProtoMessage()    {}
func (*UserEventSpecifics_UserConsent) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 3}
}
func (m *UserEventSpecifics_UserConsent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics_UserConsent.Unmarshal(m, b)
}
func (m *UserEventSpecifics_UserConsent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics_UserConsent.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics_UserConsent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics_UserConsent.Merge(dst, src)
}
func (m *UserEventSpecifics_UserConsent) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics_UserConsent.Size(m)
}
func (m *UserEventSpecifics_UserConsent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics_UserConsent.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics_UserConsent proto.InternalMessageInfo

type isUserEventSpecifics_UserConsent_Consent interface {
	isUserEventSpecifics_UserConsent_Consent()
}

type UserEventSpecifics_UserConsent_SyncConsent struct {
	SyncConsent *UserConsentTypes_SyncConsent `protobuf:"bytes,7,opt,name=sync_consent,json=syncConsent,oneof"`
}
type UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent struct {
	ArcBackupAndRestoreConsent *UserConsentTypes_ArcBackupAndRestoreConsent `protobuf:"bytes,8,opt,name=arc_backup_and_restore_consent,json=arcBackupAndRestoreConsent,oneof"`
}
type UserEventSpecifics_UserConsent_ArcLocationServiceConsent struct {
	ArcLocationServiceConsent *UserConsentTypes_ArcGoogleLocationServiceConsent `protobuf:"bytes,9,opt,name=arc_location_service_consent,json=arcLocationServiceConsent,oneof"`
}
type UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent struct {
	ArcPlayTermsOfServiceConsent *UserConsentTypes_ArcPlayTermsOfServiceConsent `protobuf:"bytes,10,opt,name=arc_play_terms_of_service_consent,json=arcPlayTermsOfServiceConsent,oneof"`
}
type UserEventSpecifics_UserConsent_UnifiedConsent struct {
	UnifiedConsent *UserConsentTypes_UnifiedConsent `protobuf:"bytes,13,opt,name=unified_consent,json=unifiedConsent,oneof"`
}

func (*UserEventSpecifics_UserConsent_SyncConsent) isUserEventSpecifics_UserConsent_Consent() {}
func (*UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent) isUserEventSpecifics_UserConsent_Consent() {
}
func (*UserEventSpecifics_UserConsent_ArcLocationServiceConsent) isUserEventSpecifics_UserConsent_Consent() {
}
func (*UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent) isUserEventSpecifics_UserConsent_Consent() {
}
func (*UserEventSpecifics_UserConsent_UnifiedConsent) isUserEventSpecifics_UserConsent_Consent() {}

func (m *UserEventSpecifics_UserConsent) GetConsent() isUserEventSpecifics_UserConsent_Consent {
	if m != nil {
		return m.Consent
	}
	return nil
}

func (m *UserEventSpecifics_UserConsent) GetLocale() string {
	if m != nil && m.Locale != nil {
		return *m.Locale
	}
	return ""
}

func (m *UserEventSpecifics_UserConsent) GetClientConsentTimeUsec() int64 {
	if m != nil && m.ClientConsentTimeUsec != nil {
		return *m.ClientConsentTimeUsec
	}
	return 0
}

func (m *UserEventSpecifics_UserConsent) GetSyncConsent() *UserConsentTypes_SyncConsent {
	if x, ok := m.GetConsent().(*UserEventSpecifics_UserConsent_SyncConsent); ok {
		return x.SyncConsent
	}
	return nil
}

func (m *UserEventSpecifics_UserConsent) GetArcBackupAndRestoreConsent() *UserConsentTypes_ArcBackupAndRestoreConsent {
	if x, ok := m.GetConsent().(*UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent); ok {
		return x.ArcBackupAndRestoreConsent
	}
	return nil
}

func (m *UserEventSpecifics_UserConsent) GetArcLocationServiceConsent() *UserConsentTypes_ArcGoogleLocationServiceConsent {
	if x, ok := m.GetConsent().(*UserEventSpecifics_UserConsent_ArcLocationServiceConsent); ok {
		return x.ArcLocationServiceConsent
	}
	return nil
}

func (m *UserEventSpecifics_UserConsent) GetArcPlayTermsOfServiceConsent() *UserConsentTypes_ArcPlayTermsOfServiceConsent {
	if x, ok := m.GetConsent().(*UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent); ok {
		return x.ArcPlayTermsOfServiceConsent
	}
	return nil
}

func (m *UserEventSpecifics_UserConsent) GetUnifiedConsent() *UserConsentTypes_UnifiedConsent {
	if x, ok := m.GetConsent().(*UserEventSpecifics_UserConsent_UnifiedConsent); ok {
		return x.UnifiedConsent
	}
	return nil
}

// Deprecated: Do not use.
func (m *UserEventSpecifics_UserConsent) GetFeature() UserEventSpecifics_UserConsent_Feature {
	if m != nil && m.Feature != nil {
		return *m.Feature
	}
	return UserEventSpecifics_UserConsent_FEATURE_UNSPECIFIED
}

// Deprecated: Do not use.
func (m *UserEventSpecifics_UserConsent) GetDescriptionGrdIds() []int32 {
	if m != nil {
		return m.DescriptionGrdIds
	}
	return nil
}

// Deprecated: Do not use.
func (m *UserEventSpecifics_UserConsent) GetConfirmationGrdId() int32 {
	if m != nil && m.ConfirmationGrdId != nil {
		return *m.ConfirmationGrdId
	}
	return 0
}

// Deprecated: Do not use.
func (m *UserEventSpecifics_UserConsent) GetStatus() UserConsentTypes_ConsentStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return UserConsentTypes_CONSENT_STATUS_UNSPECIFIED
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UserEventSpecifics_UserConsent) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UserEventSpecifics_UserConsent_OneofMarshaler, _UserEventSpecifics_UserConsent_OneofUnmarshaler, _UserEventSpecifics_UserConsent_OneofSizer, []interface{}{
		(*UserEventSpecifics_UserConsent_SyncConsent)(nil),
		(*UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent)(nil),
		(*UserEventSpecifics_UserConsent_ArcLocationServiceConsent)(nil),
		(*UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent)(nil),
		(*UserEventSpecifics_UserConsent_UnifiedConsent)(nil),
	}
}

func _UserEventSpecifics_UserConsent_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UserEventSpecifics_UserConsent)
	// consent
	switch x := m.Consent.(type) {
	case *UserEventSpecifics_UserConsent_SyncConsent:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SyncConsent); err != nil {
			return err
		}
	case *UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ArcBackupAndRestoreConsent); err != nil {
			return err
		}
	case *UserEventSpecifics_UserConsent_ArcLocationServiceConsent:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ArcLocationServiceConsent); err != nil {
			return err
		}
	case *UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ArcPlayTermsOfServiceConsent); err != nil {
			return err
		}
	case *UserEventSpecifics_UserConsent_UnifiedConsent:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UnifiedConsent); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UserEventSpecifics_UserConsent.Consent has unexpected type %T", x)
	}
	return nil
}

func _UserEventSpecifics_UserConsent_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UserEventSpecifics_UserConsent)
	switch tag {
	case 7: // consent.sync_consent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserConsentTypes_SyncConsent)
		err := b.DecodeMessage(msg)
		m.Consent = &UserEventSpecifics_UserConsent_SyncConsent{msg}
		return true, err
	case 8: // consent.arc_backup_and_restore_consent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserConsentTypes_ArcBackupAndRestoreConsent)
		err := b.DecodeMessage(msg)
		m.Consent = &UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent{msg}
		return true, err
	case 9: // consent.arc_location_service_consent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserConsentTypes_ArcGoogleLocationServiceConsent)
		err := b.DecodeMessage(msg)
		m.Consent = &UserEventSpecifics_UserConsent_ArcLocationServiceConsent{msg}
		return true, err
	case 10: // consent.arc_play_terms_of_service_consent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserConsentTypes_ArcPlayTermsOfServiceConsent)
		err := b.DecodeMessage(msg)
		m.Consent = &UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent{msg}
		return true, err
	case 13: // consent.unified_consent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UserConsentTypes_UnifiedConsent)
		err := b.DecodeMessage(msg)
		m.Consent = &UserEventSpecifics_UserConsent_UnifiedConsent{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UserEventSpecifics_UserConsent_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UserEventSpecifics_UserConsent)
	// consent
	switch x := m.Consent.(type) {
	case *UserEventSpecifics_UserConsent_SyncConsent:
		s := proto.Size(x.SyncConsent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_UserConsent_ArcBackupAndRestoreConsent:
		s := proto.Size(x.ArcBackupAndRestoreConsent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_UserConsent_ArcLocationServiceConsent:
		s := proto.Size(x.ArcLocationServiceConsent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_UserConsent_ArcPlayTermsOfServiceConsent:
		s := proto.Size(x.ArcPlayTermsOfServiceConsent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UserEventSpecifics_UserConsent_UnifiedConsent:
		s := proto.Size(x.UnifiedConsent)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Logged when the user logs into Google, and at least once per 28d.
type UserEventSpecifics_GaiaPasswordCaptured struct {
	EventTrigger         *UserEventSpecifics_GaiaPasswordCaptured_EventTrigger `protobuf:"varint,1,opt,name=event_trigger,json=eventTrigger,enum=sync_pb.UserEventSpecifics_GaiaPasswordCaptured_EventTrigger" json:"event_trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                              `json:"-"`
	XXX_unrecognized     []byte                                                `json:"-"`
	XXX_sizecache        int32                                                 `json:"-"`
}

func (m *UserEventSpecifics_GaiaPasswordCaptured) Reset() {
	*m = UserEventSpecifics_GaiaPasswordCaptured{}
}
func (m *UserEventSpecifics_GaiaPasswordCaptured) String() string { return proto.CompactTextString(m) }
func (*UserEventSpecifics_GaiaPasswordCaptured) ProtoMessage()    {}
func (*UserEventSpecifics_GaiaPasswordCaptured) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 4}
}
func (m *UserEventSpecifics_GaiaPasswordCaptured) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics_GaiaPasswordCaptured.Unmarshal(m, b)
}
func (m *UserEventSpecifics_GaiaPasswordCaptured) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics_GaiaPasswordCaptured.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics_GaiaPasswordCaptured) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics_GaiaPasswordCaptured.Merge(dst, src)
}
func (m *UserEventSpecifics_GaiaPasswordCaptured) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics_GaiaPasswordCaptured.Size(m)
}
func (m *UserEventSpecifics_GaiaPasswordCaptured) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics_GaiaPasswordCaptured.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics_GaiaPasswordCaptured proto.InternalMessageInfo

func (m *UserEventSpecifics_GaiaPasswordCaptured) GetEventTrigger() UserEventSpecifics_GaiaPasswordCaptured_EventTrigger {
	if m != nil && m.EventTrigger != nil {
		return *m.EventTrigger
	}
	return UserEventSpecifics_GaiaPasswordCaptured_UNSPECIFIED
}

type UserEventSpecifics_FlocIdComputed struct {
	// If not set, it means that the floc is disabled.
	FlocId               *uint64  `protobuf:"varint,2,opt,name=floc_id,json=flocId" json:"floc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEventSpecifics_FlocIdComputed) Reset()         { *m = UserEventSpecifics_FlocIdComputed{} }
func (m *UserEventSpecifics_FlocIdComputed) String() string { return proto.CompactTextString(m) }
func (*UserEventSpecifics_FlocIdComputed) ProtoMessage()    {}
func (*UserEventSpecifics_FlocIdComputed) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_event_specifics_35fed2019fb7e677, []int{0, 5}
}
func (m *UserEventSpecifics_FlocIdComputed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEventSpecifics_FlocIdComputed.Unmarshal(m, b)
}
func (m *UserEventSpecifics_FlocIdComputed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEventSpecifics_FlocIdComputed.Marshal(b, m, deterministic)
}
func (dst *UserEventSpecifics_FlocIdComputed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEventSpecifics_FlocIdComputed.Merge(dst, src)
}
func (m *UserEventSpecifics_FlocIdComputed) XXX_Size() int {
	return xxx_messageInfo_UserEventSpecifics_FlocIdComputed.Size(m)
}
func (m *UserEventSpecifics_FlocIdComputed) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEventSpecifics_FlocIdComputed.DiscardUnknown(m)
}

var xxx_messageInfo_UserEventSpecifics_FlocIdComputed proto.InternalMessageInfo

func (m *UserEventSpecifics_FlocIdComputed) GetFlocId() uint64 {
	if m != nil && m.FlocId != nil {
		return *m.FlocId
	}
	return 0
}

func init() {
	proto.RegisterType((*UserEventSpecifics)(nil), "sync_pb.UserEventSpecifics")
	proto.RegisterType((*UserEventSpecifics_Test)(nil), "sync_pb.UserEventSpecifics.Test")
	proto.RegisterType((*UserEventSpecifics_LanguageDetection)(nil), "sync_pb.UserEventSpecifics.LanguageDetection")
	proto.RegisterType((*UserEventSpecifics_LanguageDetection_Language)(nil), "sync_pb.UserEventSpecifics.LanguageDetection.Language")
	proto.RegisterType((*UserEventSpecifics_Translation)(nil), "sync_pb.UserEventSpecifics.Translation")
	proto.RegisterType((*UserEventSpecifics_UserConsent)(nil), "sync_pb.UserEventSpecifics.UserConsent")
	proto.RegisterType((*UserEventSpecifics_GaiaPasswordCaptured)(nil), "sync_pb.UserEventSpecifics.GaiaPasswordCaptured")
	proto.RegisterType((*UserEventSpecifics_FlocIdComputed)(nil), "sync_pb.UserEventSpecifics.FlocIdComputed")
	proto.RegisterEnum("sync_pb.UserEventSpecifics_Translation_Interaction", UserEventSpecifics_Translation_Interaction_name, UserEventSpecifics_Translation_Interaction_value)
	proto.RegisterEnum("sync_pb.UserEventSpecifics_UserConsent_Feature", UserEventSpecifics_UserConsent_Feature_name, UserEventSpecifics_UserConsent_Feature_value)
	proto.RegisterEnum("sync_pb.UserEventSpecifics_GaiaPasswordCaptured_EventTrigger", UserEventSpecifics_GaiaPasswordCaptured_EventTrigger_name, UserEventSpecifics_GaiaPasswordCaptured_EventTrigger_value)
	proto.RegisterEnum("sync_pb.UserEventSpecifics_FlocIdComputed_EventTrigger", UserEventSpecifics_FlocIdComputed_EventTrigger_name, UserEventSpecifics_FlocIdComputed_EventTrigger_value)
}

func init() {
	proto.RegisterFile("components/sync/protocol/user_event_specifics.proto", fileDescriptor_user_event_specifics_35fed2019fb7e677)
}

var fileDescriptor_user_event_specifics_35fed2019fb7e677 = []byte{
	// 1412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcb, 0x6e, 0xdb, 0xcc,
	0x15, 0x36, 0x25, 0x59, 0x97, 0x23, 0xd9, 0xa6, 0xc7, 0x7f, 0x6c, 0x45, 0xcd, 0x9f, 0xba, 0x2e,
	0xd2, 0x18, 0xbd, 0xc8, 0xad, 0x52, 0xa4, 0x17, 0xa0, 0x0b, 0x9a, 0x1a, 0x4b, 0xb4, 0x65, 0x4a,
	0x18, 0x52, 0x49, 0x9d, 0xcd, 0x80, 0x26, 0x47, 0x0a, 0x51, 0x8a, 0x14, 0x38, 0x54, 0x0a, 0x17,
	0xdd, 0x14, 0xe8, 0xae, 0x40, 0x5f, 0xa2, 0xaf, 0xd0, 0x67, 0xe8, 0xa6, 0xef, 0xd3, 0x75, 0x31,
	0x43, 0x4a, 0xa2, 0xe2, 0x4b, 0x92, 0x25, 0xcf, 0x77, 0xbe, 0xef, 0x3b, 0x3c, 0x33, 0x73, 0x66,
	0xe0, 0x8d, 0x1b, 0xcd, 0xe6, 0x51, 0xc8, 0xc2, 0x84, 0x9f, 0xf1, 0xbb, 0xd0, 0x3d, 0x9b, 0xc7,
	0x51, 0x12, 0xb9, 0x51, 0x70, 0xb6, 0xe0, 0x2c, 0xa6, 0xec, 0x13, 0x0b, 0x13, 0xca, 0xe7, 0xcc,
	0xf5, 0x27, 0xbe, 0xcb, 0xdb, 0x12, 0x45, 0x15, 0x91, 0x49, 0xe7, 0xb7, 0xad, 0x5f, 0x3d, 0xcd,
	0x76, 0xa3, 0x90, 0x0b, 0x7e, 0x72, 0x37, 0x67, 0x19, 0xb7, 0xd5, 0x79, 0x94, 0x32, 0x75, 0x7c,
	0x87, 0xce, 0x1d, 0xce, 0xff, 0x1c, 0xc5, 0x1e, 0x8d, 0xd9, 0x82, 0xb3, 0x94, 0x73, 0xf2, 0xaf,
	0x23, 0x40, 0x63, 0xce, 0x62, 0x2c, 0xaa, 0xb1, 0x96, 0xc5, 0xa0, 0x9f, 0xc0, 0x5e, 0x5a, 0x5f,
	0xe2, 0xcf, 0x18, 0x5d, 0x70, 0xe6, 0x36, 0x95, 0x63, 0xe5, 0xb4, 0x48, 0x76, 0x64, 0xd8, 0xf6,
	0x67, 0x6c, 0xcc, 0x99, 0x8b, 0x7e, 0x0c, 0x3b, 0xa1, 0xf3, 0xc9, 0x9f, 0x3a, 0x89, 0x1f, 0x85,
	0xd4, 0xf7, 0x9a, 0x05, 0x99, 0xd5, 0x58, 0x07, 0x0d, 0x0f, 0x7d, 0x0f, 0xc0, 0x19, 0xe7, 0x59,
	0x46, 0xf1, 0x58, 0x39, 0x2d, 0x93, 0x5a, 0x16, 0x31, 0x3c, 0xa4, 0x01, 0x24, 0x8c, 0x27, 0x69,
	0x43, 0x9a, 0xd5, 0x63, 0xe5, 0xb4, 0xde, 0x39, 0x6e, 0x67, 0x7d, 0x68, 0xdf, 0x2f, 0xae, 0x6d,
	0x33, 0x9e, 0xf4, 0xb7, 0x48, 0x4d, 0xb0, 0x24, 0x84, 0x66, 0xd0, 0x0c, 0x9c, 0x70, 0xba, 0x70,
	0xa6, 0x8c, 0x7a, 0x2c, 0x61, 0xae, 0x2c, 0x27, 0x15, 0x04, 0x29, 0xf8, 0x8b, 0xa7, 0x04, 0x07,
	0x19, 0xb7, 0xbb, 0xa4, 0x9e, 0x17, 0x9a, 0x4a, 0x7f, 0x8b, 0x1c, 0x06, 0x9f, 0x03, 0xa9, 0xdd,
	0x07, 0xd8, 0x4f, 0x62, 0x27, 0xe4, 0x81, 0x93, 0xf3, 0xa9, 0x4b, 0x9f, 0xd7, 0x4f, 0x16, 0xbe,
	0x26, 0x65, 0x0e, 0x6a, 0x4e, 0x27, 0xd5, 0x1e, 0x41, 0x23, 0xbf, 0xc0, 0xcd, 0xc6, 0x97, 0x65,
	0x45, 0x48, 0x4f, 0xd3, 0x33, 0xd9, 0xfa, 0x62, 0x1d, 0x42, 0xef, 0xe1, 0xf9, 0x03, 0xeb, 0x9f,
	0x55, 0xfd, 0x51, 0xca, 0xb7, 0x56, 0xf2, 0x3d, 0xc7, 0x77, 0x46, 0x59, 0x22, 0x11, 0x79, 0xa2,
	0x0d, 0xd3, 0xcf, 0x83, 0x69, 0xa9, 0x1c, 0x5e, 0x6c, 0x0a, 0xbb, 0xce, 0x3c, 0x59, 0xc4, 0xcc,
	0xcb, 0xb4, 0xf7, 0xa4, 0xf6, 0x2f, 0x9f, 0x2a, 0x3d, 0x6f, 0xa7, 0x67, 0xec, 0xfe, 0x16, 0x79,
	0x3e, 0x7d, 0x20, 0x9e, 0x9a, 0x3a, 0x70, 0x38, 0x09, 0x22, 0x97, 0xfa, 0x1e, 0x15, 0xdb, 0x7d,
	0x91, 0xac, 0xec, 0x54, 0x69, 0xf7, 0xd3, 0xa7, 0xec, 0x2e, 0x82, 0xc8, 0x35, 0x3c, 0x3d, 0xe3,
	0xf5, 0xb7, 0xc8, 0xc1, 0x64, 0x23, 0x22, 0xd3, 0x5b, 0x65, 0x28, 0x89, 0x2d, 0xd6, 0xfa, 0x7b,
	0x01, 0xf6, 0xef, 0x6d, 0x0d, 0xc4, 0x00, 0xa5, 0x5b, 0x8c, 0x79, 0x74, 0xb9, 0x3f, 0x78, 0x53,
	0x39, 0x2e, 0x9e, 0xd6, 0x3b, 0x6f, 0xbf, 0x69, 0x97, 0xad, 0x22, 0x64, 0x7f, 0xa9, 0xb8, 0x8c,
	0x70, 0xd4, 0x81, 0x67, 0x8e, 0x17, 0xcd, 0xf3, 0x2e, 0xd4, 0x8d, 0x3c, 0x26, 0x4f, 0x58, 0x8d,
	0x1c, 0x64, 0xe0, 0x92, 0xa0, 0x47, 0x1e, 0x6b, 0x8d, 0xa0, 0xba, 0xfc, 0x16, 0x27, 0x73, 0x93,
	0xa7, 0x48, 0x5e, 0x23, 0xc8, 0x11, 0xd0, 0x0f, 0xa1, 0xee, 0x73, 0x1a, 0xb3, 0xc0, 0x77, 0x6e,
	0x83, 0x54, 0xba, 0x4a, 0xc0, 0xe7, 0x24, 0x8b, 0xfc, 0xbe, 0xd0, 0x54, 0x5a, 0xff, 0x2c, 0x42,
	0x3d, 0xb7, 0x73, 0xd1, 0xcf, 0x01, 0x4d, 0xe2, 0x68, 0x46, 0x1f, 0x92, 0x57, 0x05, 0x92, 0xaf,
	0x09, 0x9d, 0x82, 0x9a, 0x44, 0x0f, 0xfe, 0xc2, 0x6e, 0x12, 0x6d, 0x64, 0x8e, 0xa1, 0xee, 0x87,
	0x09, 0x8b, 0x1d, 0xd9, 0x1c, 0x39, 0x27, 0x76, 0x3b, 0x6f, 0xbe, 0xf2, 0x3c, 0xb5, 0x8d, 0x35,
	0x95, 0xe4, 0x75, 0x4e, 0xfe, 0xab, 0x40, 0x3d, 0x07, 0xa2, 0x3a, 0x54, 0xc6, 0xe6, 0x95, 0x39,
	0x7c, 0x6f, 0xaa, 0x5b, 0x08, 0xa0, 0xac, 0xe9, 0x3a, 0x1e, 0xd9, 0xaa, 0x22, 0x80, 0x2e, 0xd6,
	0x07, 0x86, 0x89, 0xd5, 0x82, 0xf8, 0x30, 0x7a, 0xe6, 0x90, 0xe0, 0xae, 0x5a, 0x44, 0x3b, 0x50,
	0xeb, 0x1a, 0xd6, 0xb5, 0x61, 0x59, 0xb8, 0xab, 0x96, 0x04, 0xe9, 0x5a, 0x33, 0xc7, 0xda, 0x40,
	0xdd, 0x46, 0x4d, 0xf8, 0xce, 0x26, 0x9a, 0x69, 0x0d, 0x34, 0xdb, 0x18, 0x9a, 0x94, 0xe0, 0x77,
	0x98, 0xd8, 0xb8, 0xab, 0x96, 0xd1, 0x0b, 0x68, 0x6a, 0x63, 0x7b, 0x48, 0xf3, 0xf0, 0xf9, 0x0d,
	0x1d, 0x11, 0x7c, 0xa1, 0x56, 0x1e, 0x43, 0x07, 0x86, 0x79, 0xa5, 0x56, 0x85, 0xaa, 0x61, 0x1a,
	0xb6, 0xa1, 0x0d, 0x8c, 0x0f, 0x29, 0x86, 0x09, 0x19, 0x12, 0xb5, 0x26, 0x17, 0xe4, 0x7f, 0x55,
	0xa8, 0xe7, 0xce, 0x3c, 0x3a, 0x84, 0x72, 0x10, 0xb9, 0x4e, 0xc0, 0x9a, 0x25, 0xd9, 0xd8, 0xec,
	0x0b, 0xfd, 0x06, 0x9a, 0x6e, 0xe0, 0x8b, 0x29, 0xbe, 0xba, 0x2d, 0x56, 0xd3, 0xbc, 0x21, 0xe7,
	0xf4, 0xb3, 0x14, 0xcf, 0x84, 0x56, 0x53, 0xfd, 0x12, 0x1a, 0xb2, 0xeb, 0xcb, 0x19, 0x54, 0x91,
	0x27, 0xeb, 0xd5, 0xc6, 0x52, 0x2c, 0x39, 0xf2, 0xfe, 0xb1, 0xee, 0x42, 0x37, 0x0b, 0x88, 0xe9,
	0xc3, 0xd7, 0x9f, 0xe8, 0x2f, 0xf0, 0xd2, 0x89, 0x5d, 0x7a, 0xeb, 0xb8, 0x7f, 0x5a, 0xcc, 0xa9,
	0x13, 0x8a, 0xf1, 0xc3, 0x93, 0x28, 0x66, 0x2b, 0xf5, 0x74, 0xe2, 0xff, 0xfa, 0x71, 0x75, 0x2d,
	0x76, 0xcf, 0x25, 0x5d, 0x0b, 0x3d, 0x92, 0x92, 0xd7, 0x66, 0x2d, 0xe7, 0x51, 0x14, 0xfd, 0x15,
	0x5e, 0x08, 0x6f, 0xd1, 0x0e, 0x39, 0xa8, 0x39, 0x8b, 0x3f, 0xf9, 0xee, 0xda, 0xb9, 0x26, 0x9d,
	0x7f, 0xf7, 0xa4, 0x73, 0x2f, 0x8a, 0xa6, 0x01, 0x1b, 0x64, 0x12, 0x56, 0xaa, 0xb0, 0xb6, 0x7f,
	0xee, 0xc4, 0xee, 0xc3, 0x20, 0xfa, 0x9b, 0x02, 0x3f, 0x12, 0xf6, 0xf3, 0xc0, 0xb9, 0xa3, 0x09,
	0x8b, 0x67, 0x9c, 0x46, 0x93, 0x7b, 0x35, 0xa4, 0xd7, 0xd3, 0xdb, 0x27, 0x6b, 0x18, 0x05, 0xce,
	0x9d, 0x2d, 0x04, 0x86, 0x93, 0x7b, 0x05, 0x88, 0x3f, 0x7c, 0x14, 0x47, 0x16, 0xec, 0x2d, 0x42,
	0x7f, 0xe2, 0x33, 0x6f, 0x65, 0xb8, 0x23, 0x0d, 0x4f, 0x1f, 0x37, 0x1c, 0xa7, 0x84, 0xb5, 0xc5,
	0xee, 0x62, 0x23, 0x82, 0xae, 0xa1, 0x32, 0x61, 0x8e, 0x98, 0xc9, 0xf2, 0xd4, 0xef, 0x76, 0xce,
	0xbe, 0xf2, 0x76, 0x6a, 0x5f, 0xa4, 0x34, 0x71, 0x4b, 0x91, 0xa5, 0x06, 0xea, 0xc0, 0x81, 0xc7,
	0xb8, 0x1b, 0xfb, 0x73, 0xb9, 0x48, 0xd3, 0xd8, 0xa3, 0xbe, 0xc7, 0x9b, 0x85, 0xe3, 0xe2, 0xe9,
	0xb6, 0xcc, 0xdc, 0xcf, 0xc1, 0xbd, 0xd8, 0x33, 0x3c, 0x31, 0x1d, 0x0f, 0xdc, 0x28, 0x9c, 0xf8,
	0xf1, 0xcc, 0xc9, 0x91, 0xe4, 0xcc, 0xc8, 0x38, 0x79, 0x58, 0x92, 0x90, 0x0e, 0x65, 0x9e, 0x38,
	0xc9, 0x82, 0x37, 0xb7, 0x65, 0xd5, 0xaf, 0x1f, 0x6f, 0x41, 0xf6, 0x61, 0xc9, 0x74, 0xa9, 0x97,
	0x51, 0x4f, 0xfe, 0xad, 0x40, 0x25, 0xfb, 0x0b, 0x74, 0x04, 0x07, 0x17, 0x58, 0xb3, 0xc7, 0x04,
	0xd3, 0xb1, 0x69, 0x8d, 0xb0, 0x6e, 0x5c, 0x18, 0xb8, 0xab, 0x6e, 0xa1, 0x3d, 0xa8, 0xeb, 0x7d,
	0x32, 0xbc, 0xc6, 0xd4, 0xba, 0x31, 0x75, 0x55, 0x41, 0xbb, 0x00, 0xa3, 0x81, 0x76, 0x43, 0x2d,
	0x7b, 0x48, 0xc4, 0x74, 0x39, 0x04, 0x74, 0xae, 0xe9, 0x57, 0xe3, 0x11, 0xd5, 0xcc, 0x2e, 0x25,
	0x38, 0x8d, 0x17, 0xd1, 0x0f, 0xe0, 0xa8, 0x37, 0x1c, 0xf6, 0x06, 0x98, 0x0e, 0x86, 0x7a, 0x7a,
	0xf0, 0x2d, 0x4c, 0xde, 0x19, 0x3a, 0x56, 0x4b, 0xa8, 0x05, 0x87, 0x99, 0xea, 0xd8, 0x94, 0x4e,
	0x54, 0x1f, 0x9a, 0x16, 0x36, 0x6d, 0x75, 0x1b, 0xbd, 0x84, 0x96, 0x66, 0x59, 0x86, 0x65, 0x6b,
	0xa6, 0x4d, 0x35, 0xdd, 0x36, 0xde, 0x19, 0xf6, 0x8d, 0xc0, 0x6d, 0x32, 0x1c, 0xa8, 0x65, 0x31,
	0x36, 0xce, 0x6b, 0x50, 0xc9, 0xf6, 0xc0, 0x65, 0xa9, 0x5a, 0x57, 0x1b, 0x97, 0xa5, 0x6a, 0x59,
	0xad, 0x90, 0xef, 0xc5, 0x1e, 0x9d, 0xb1, 0x24, 0xf6, 0x5d, 0x2e, 0xcf, 0xe7, 0x82, 0xa7, 0x83,
	0x5a, 0xa6, 0x12, 0x70, 0x5c, 0x37, 0x5a, 0x84, 0x09, 0xf5, 0xbd, 0xd6, 0x7f, 0x14, 0xf8, 0xee,
	0xa1, 0x1b, 0x1b, 0xdd, 0xc2, 0x4e, 0xf6, 0x5c, 0x8c, 0xfd, 0xe9, 0x94, 0xc5, 0xd9, 0xbe, 0xf8,
	0xc3, 0xb7, 0x5e, 0xfd, 0x6d, 0x99, 0x63, 0xa7, 0x22, 0xa4, 0xc1, 0x72, 0x5f, 0x27, 0x97, 0xd0,
	0xc8, 0xa3, 0xa2, 0xc9, 0x9b, 0x5d, 0x47, 0xb0, 0x3b, 0xb6, 0x30, 0xa1, 0x83, 0x61, 0xaf, 0x87,
	0xbb, 0xd4, 0x30, 0x55, 0x05, 0x3d, 0x83, 0x7d, 0xfc, 0xc7, 0x91, 0x41, 0x70, 0x97, 0x76, 0x7e,
	0xdb, 0xa5, 0xb6, 0x71, 0x8d, 0x89, 0x5a, 0x68, 0xfd, 0x43, 0x81, 0xdd, 0xcd, 0xb7, 0x00, 0x3a,
	0x82, 0x4a, 0xf6, 0xae, 0x90, 0xd7, 0x53, 0x89, 0x94, 0xd3, 0xa7, 0xc1, 0xc9, 0xd5, 0x97, 0x7c,
	0x2b, 0x50, 0x34, 0xf1, 0x7b, 0x55, 0x11, 0xd7, 0x04, 0xc1, 0x17, 0x04, 0x5b, 0x7d, 0xdc, 0x55,
	0x0b, 0xa2, 0x9e, 0xbe, 0x21, 0x56, 0xf6, 0x86, 0x76, 0xf1, 0x00, 0xdb, 0x58, 0x2d, 0x5e, 0x96,
	0xaa, 0x8a, 0x5a, 0x20, 0x9b, 0xcd, 0x3a, 0xaf, 0xc0, 0xb6, 0x0c, 0x5c, 0x96, 0xaa, 0x35, 0x15,
	0xc8, 0xfe, 0xc4, 0x67, 0x81, 0x27, 0x50, 0x27, 0x48, 0x9f, 0x36, 0xe7, 0x3f, 0x83, 0x57, 0x51,
	0x3c, 0x6d, 0xbb, 0x1f, 0xe3, 0x68, 0xe6, 0x2f, 0x66, 0xed, 0xf5, 0x43, 0x5f, 0x76, 0xb8, 0xbd,
	0x7c, 0xe8, 0xf7, 0x8b, 0x23, 0xe5, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xc4, 0x3f, 0xbc,
	0x78, 0x0c, 0x00, 0x00,
}
